[package]
authors = ["Karuna Murti <karuna.murti@gmail.com>"]
description = "A full featured messaging engine for the FIX protocol implemented in Rust"
edition = "2024"
homepage = "https://github.com/fixer-rs/fixer.git"
license = "Apache-2.0"
name = "fixer"
readme = "README.md"
repository = "https://github.com/fixer-rs/fixer.git"
rust-version = "1.85"
version = "0.1.0"

[lib]
name = "fixer"
path = "src/lib.rs"

[dependencies]
addr = "0.15"
async-recursion = "1.0"
atoi_simd = "0.18"
chrono = { version = "0.4", features = ["default", "serde"] }
chrono-tz = "0.10"
dashmap = "6.1"
delegate = "0.13"
dyn-clone = "1.0"
enum_dispatch = "0.3"
fast-float = "0.2"
futures = "0.3"
itoa = "1.0"
log = "0.4"
maplit = "1.0"
memmem = "0.1.1"
owning_ref = "0.4"
parking_lot = "0.12"
parse_duration = "2.1"
quick-xml = { version = "0.37", features = ["serialize"] }
ramhorns = "1.0"
regex = "1.12"
rust_decimal = "1.40"
scopeguard = "1.2"
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0"
simple-error = "0.3"
sscanf = "0.4"
thiserror = "2.0"
tokio = { version = "1.49", features = [
  "io-util",
  "io-std",
  "fs",
  "rt",
  "rt-multi-thread",
  "sync",
  "macros",
  "time",
] }

[dev-dependencies]
async_once = "0.2"
criterion = "0.5"
mockall = "0.13"
pprof = { version = "0.14", features = ["flamegraph", "criterion"] }
serial_test = "3.0"

[[bench]]
harness = false
name = "fixer_benchmark"
