[package]
authors = ["Karuna Murti <karuna.murti@gmail.com>"]
description = "A full featured messaging engine for the FIX protocol implemented in Rust"
edition = "2021"
homepage = "https://github.com/karuna/fixer.git"
license = "Apache-2.0"
name = "fixer"
readme = "README.md"
repository = "https://github.com/karuna/fixer.git"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.20"
delegate = "0.7.0"
dyn-clone = "1.0.9"
fast-float = "0.2.0"
intertrait = "0.2"
lazy_static = "1.4.0"
linkme = "0.2"
quick-xml = {version = "0.23", features = ["serialize"]}
rust_decimal = "1.25.0"
serde = {version = "1.0", features = ["derive"]}
serde_derive = "1.0.143"
simple-error = "0.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
harness = false
name = "fixer_benchmark"
