// Code generated by fixer-gen. DO NOT EDIT.
#![allow(clippy::new_without_default)]
#![allow(clippy::needless_pass_by_value)]
#![allow(clippy::too_many_arguments)]
#![allow(unused_imports)]

use fixer::message::Message;
use fixer::fix_string::FIXString;
use fixer::errors::MessageRejectErrorEnum;
use fixer::session::session_id::SessionID;
use fixer::repeating_group::{Group, GroupTemplate, RepeatingGroup, group_element};
use std::borrow::{Borrow, BorrowMut};

use rust_decimal::Decimal;


use crate::field;
use crate::tag;

/// `ListStrikePrice` is the `fix44` `ListStrikePrice` type, `MsgType` = m.
pub struct ListStrikePrice {
    pub message: Message,
}

impl ListStrikePrice {
    /// Creates a new `ListStrikePrice` with required fields.
    pub fn new(list_id: field::ListIDField, tot_no_strikes: field::TotNoStrikesField) -> Self {
        let mut msg = Message::new();
        msg.header.set_field(tag::MSG_TYPE, FIXString::from("m".to_string()));

        msg.body.set_field(tag::LIST_ID, list_id.0);

        msg.body.set_field(tag::TOT_NO_STRIKES, tot_no_strikes.0);

        Self { message: msg }
    }

    /// Creates a `ListStrikePrice` from an existing `Message`.
    pub fn from_message(msg: Message) -> Self {
        Self { message: msg }
    }

    /// Returns the underlying `Message`.
    pub fn to_message(self) -> Message {
        self.message
    }




    /// Sets `LastFragment`, Tag 893.
    pub fn set_last_fragment(&mut self, v: bool) {
        self.message.body.set_field(tag::LAST_FRAGMENT, fixer::fix_boolean::FIXBoolean::from(v));
    }

    /// Gets `LastFragment`, Tag 893.
    pub fn get_last_fragment(&self) -> Result<bool, MessageRejectErrorEnum> {
        let mut fld = field::LastFragmentField::new(false);
        self.message.body.get_field(tag::LAST_FRAGMENT, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `LastFragment` is present, Tag 893.
    pub fn has_last_fragment(&self) -> bool {
        self.message.body.has(tag::LAST_FRAGMENT)
    }




    /// Sets `ListID`, Tag 66.
    pub fn set_list_id(&mut self, v: String) {
        self.message.body.set_field(tag::LIST_ID, FIXString::from(v));
    }

    /// Gets `ListID`, Tag 66.
    pub fn get_list_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::ListIDField::new(String::new());
        self.message.body.get_field(tag::LIST_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `ListID` is present, Tag 66.
    pub fn has_list_id(&self) -> bool {
        self.message.body.has(tag::LIST_ID)
    }




    /// Sets `NoStrikes`, Tag 428.
    pub fn set_no_strikes(&mut self, f: NoStrikesRepeatingGroup) {
        self.message.body.set_group(f.0);
    }

    /// Gets `NoStrikes`, Tag 428.
    pub fn get_no_strikes(&self) -> Result<NoStrikesRepeatingGroup, MessageRejectErrorEnum> {
        let g = NoStrikesRepeatingGroup::new();
        Ok(NoStrikesRepeatingGroup(self.message.body.get_group(g.0)?))
    }


    /// Returns true if `NoStrikes` is present, Tag 428.
    pub fn has_no_strikes(&self) -> bool {
        self.message.body.has(tag::NO_STRIKES)
    }




    /// Sets `NoUnderlyings`, Tag 711.
    pub fn set_no_underlyings(&mut self, f: NoUnderlyingsRepeatingGroup) {
        self.message.body.set_group(f.0);
    }

    /// Gets `NoUnderlyings`, Tag 711.
    pub fn get_no_underlyings(&self) -> Result<NoUnderlyingsRepeatingGroup, MessageRejectErrorEnum> {
        let g = NoUnderlyingsRepeatingGroup::new();
        Ok(NoUnderlyingsRepeatingGroup(self.message.body.get_group(g.0)?))
    }


    /// Returns true if `NoUnderlyings` is present, Tag 711.
    pub fn has_no_underlyings(&self) -> bool {
        self.message.body.has(tag::NO_UNDERLYINGS)
    }




    /// Sets `TotNoStrikes`, Tag 422.
    pub fn set_tot_no_strikes(&mut self, v: isize) {
        self.message.body.set_field(tag::TOT_NO_STRIKES, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `TotNoStrikes`, Tag 422.
    pub fn get_tot_no_strikes(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::TotNoStrikesField::new(0);
        self.message.body.get_field(tag::TOT_NO_STRIKES, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `TotNoStrikes` is present, Tag 422.
    pub fn has_tot_no_strikes(&self) -> bool {
        self.message.body.has(tag::TOT_NO_STRIKES)
    }


}

/// `RouteOut` is the callback type for routing `ListStrikePrice` messages.
pub type RouteOut = fn(msg: ListStrikePrice, session_id: SessionID) -> Result<(), MessageRejectErrorEnum>;

/// Route type returned by the `route` function.
pub type Route = (&'static str, &'static str, Box<dyn Fn(&Message, SessionID) -> Result<(), MessageRejectErrorEnum> + Send>);

/// Returns the begin string, message type, and route function for `ListStrikePrice`.
pub fn route(router: RouteOut) -> Route {
    let r = move |msg: &Message, session_id: SessionID| -> Result<(), MessageRejectErrorEnum> {
        router(ListStrikePrice::from_message(msg.clone()), session_id)
    };
    ("FIX.4.4", "m", Box::new(r))
}


/// `NoSecurityAltID` is an entry in the `NoSecurityAltID` repeating group, Tag 454.
pub struct NoStrikesNoSecurityAltID<G>(pub G);

impl<G: Borrow<Group>> NoStrikesNoSecurityAltID<G> {
    fn group(&self) -> &Group {
        self.0.borrow()
    }



    /// Gets `SecurityAltID`, Tag 455.
    pub fn get_security_alt_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityAltIDField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_ALT_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityAltID` is present, Tag 455.
    pub fn has_security_alt_id(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_ALT_ID)
    }




    /// Gets `SecurityAltIDSource`, Tag 456.
    pub fn get_security_alt_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityAltIDSourceField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_ALT_ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityAltIDSource` is present, Tag 456.
    pub fn has_security_alt_id_source(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_ALT_ID_SOURCE)
    }


}

impl<G: BorrowMut<Group>> NoStrikesNoSecurityAltID<G> {
    fn group_mut(&mut self) -> &mut Group {
        self.0.borrow_mut()
    }



    /// Sets `SecurityAltID`, Tag 455.
    pub fn set_security_alt_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_ALT_ID, FIXString::from(v));
    }





    /// Sets `SecurityAltIDSource`, Tag 456.
    pub fn set_security_alt_id_source(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_ALT_ID_SOURCE, FIXString::from(v));
    }



}

/// `NoStrikesNoSecurityAltIDRepeatingGroup` is the `NoSecurityAltID` repeating group, Tag 454.
pub struct NoStrikesNoSecurityAltIDRepeatingGroup(pub RepeatingGroup);

impl NoStrikesNoSecurityAltIDRepeatingGroup {
    /// Creates an empty `NoSecurityAltID` group with the template from the FIX spec.
    pub fn new() -> Self {
        let template: GroupTemplate = vec![


            group_element(tag::SECURITY_ALT_ID),



            group_element(tag::SECURITY_ALT_ID_SOURCE),


        ];
        Self(RepeatingGroup::new(tag::NO_SECURITY_ALT_ID, template))
    }

    /// Appends an entry and returns it for population.
    pub fn add(&mut self) -> NoStrikesNoSecurityAltID<&mut Group> {
        NoStrikesNoSecurityAltID(self.0.add())
    }

    /// Returns the `i`th entry.
    pub fn get(&self, i: usize) -> NoStrikesNoSecurityAltID<&Group> {
        NoStrikesNoSecurityAltID(self.0.get(i))
    }

    /// Returns the number of entries.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns true if the group has no entries.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl Default for NoStrikesNoSecurityAltIDRepeatingGroup {
    fn default() -> Self {
        Self::new()
    }
}



/// `NoEvents` is an entry in the `NoEvents` repeating group, Tag 864.
pub struct NoStrikesNoEvents<G>(pub G);

impl<G: Borrow<Group>> NoStrikesNoEvents<G> {
    fn group(&self) -> &Group {
        self.0.borrow()
    }



    /// Gets `EventType`, Tag 865.
    pub fn get_event_type(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EventTypeField::new(0);
        self.group().field_map.get_field(tag::EVENT_TYPE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EventType` is present, Tag 865.
    pub fn has_event_type(&self) -> bool {
        self.group().field_map.has(tag::EVENT_TYPE)
    }




    /// Gets `EventDate`, Tag 866.
    pub fn get_event_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EventDateField::new(String::new());
        self.group().field_map.get_field(tag::EVENT_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EventDate` is present, Tag 866.
    pub fn has_event_date(&self) -> bool {
        self.group().field_map.has(tag::EVENT_DATE)
    }




    /// Gets `EventPx`, Tag 867.
    pub fn get_event_px(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::EventPxField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::EVENT_PX, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EventPx` is present, Tag 867.
    pub fn has_event_px(&self) -> bool {
        self.group().field_map.has(tag::EVENT_PX)
    }




    /// Gets `EventText`, Tag 868.
    pub fn get_event_text(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EventTextField::new(String::new());
        self.group().field_map.get_field(tag::EVENT_TEXT, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EventText` is present, Tag 868.
    pub fn has_event_text(&self) -> bool {
        self.group().field_map.has(tag::EVENT_TEXT)
    }


}

impl<G: BorrowMut<Group>> NoStrikesNoEvents<G> {
    fn group_mut(&mut self) -> &mut Group {
        self.0.borrow_mut()
    }



    /// Sets `EventType`, Tag 865.
    pub fn set_event_type(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::EVENT_TYPE, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `EventDate`, Tag 866.
    pub fn set_event_date(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::EVENT_DATE, FIXString::from(v));
    }





    /// Sets `EventPx`, Tag 867.
    pub fn set_event_px(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::EVENT_PX, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `EventText`, Tag 868.
    pub fn set_event_text(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::EVENT_TEXT, FIXString::from(v));
    }



}

/// `NoStrikesNoEventsRepeatingGroup` is the `NoEvents` repeating group, Tag 864.
pub struct NoStrikesNoEventsRepeatingGroup(pub RepeatingGroup);

impl NoStrikesNoEventsRepeatingGroup {
    /// Creates an empty `NoEvents` group with the template from the FIX spec.
    pub fn new() -> Self {
        let template: GroupTemplate = vec![


            group_element(tag::EVENT_TYPE),



            group_element(tag::EVENT_DATE),



            group_element(tag::EVENT_PX),



            group_element(tag::EVENT_TEXT),


        ];
        Self(RepeatingGroup::new(tag::NO_EVENTS, template))
    }

    /// Appends an entry and returns it for population.
    pub fn add(&mut self) -> NoStrikesNoEvents<&mut Group> {
        NoStrikesNoEvents(self.0.add())
    }

    /// Returns the `i`th entry.
    pub fn get(&self, i: usize) -> NoStrikesNoEvents<&Group> {
        NoStrikesNoEvents(self.0.get(i))
    }

    /// Returns the number of entries.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns true if the group has no entries.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl Default for NoStrikesNoEventsRepeatingGroup {
    fn default() -> Self {
        Self::new()
    }
}



/// `NoStrikes` is an entry in the `NoStrikes` repeating group, Tag 428.
pub struct NoStrikes<G>(pub G);

impl<G: Borrow<Group>> NoStrikes<G> {
    fn group(&self) -> &Group {
        self.0.borrow()
    }



    /// Gets `Symbol`, Tag 55.
    pub fn get_symbol(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolField::new(String::new());
        self.group().field_map.get_field(tag::SYMBOL, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Symbol` is present, Tag 55.
    pub fn has_symbol(&self) -> bool {
        self.group().field_map.has(tag::SYMBOL)
    }




    /// Gets `SymbolSfx`, Tag 65.
    pub fn get_symbol_sfx(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolSfxField::new(String::new());
        self.group().field_map.get_field(tag::SYMBOL_SFX, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SymbolSfx` is present, Tag 65.
    pub fn has_symbol_sfx(&self) -> bool {
        self.group().field_map.has(tag::SYMBOL_SFX)
    }




    /// Gets `SecurityID`, Tag 48.
    pub fn get_security_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityIDField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityID` is present, Tag 48.
    pub fn has_security_id(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_ID)
    }




    /// Gets `SecurityIDSource`, Tag 22.
    pub fn get_security_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityIDSourceField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityIDSource` is present, Tag 22.
    pub fn has_security_id_source(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_ID_SOURCE)
    }




    /// Gets `NoSecurityAltID`, Tag 454.
    pub fn get_no_security_alt_id(&self) -> Result<NoStrikesNoSecurityAltIDRepeatingGroup, MessageRejectErrorEnum> {
        let g = NoStrikesNoSecurityAltIDRepeatingGroup::new();
        Ok(NoStrikesNoSecurityAltIDRepeatingGroup(self.group().field_map.get_group(g.0)?))
    }


    /// Returns true if `NoSecurityAltID` is present, Tag 454.
    pub fn has_no_security_alt_id(&self) -> bool {
        self.group().field_map.has(tag::NO_SECURITY_ALT_ID)
    }




    /// Gets `Product`, Tag 460.
    pub fn get_product(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::ProductField::new(0);
        self.group().field_map.get_field(tag::PRODUCT, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Product` is present, Tag 460.
    pub fn has_product(&self) -> bool {
        self.group().field_map.has(tag::PRODUCT)
    }




    /// Gets `CFICode`, Tag 461.
    pub fn get_cfi_code(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CFICodeField::new(String::new());
        self.group().field_map.get_field(tag::CFI_CODE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CFICode` is present, Tag 461.
    pub fn has_cfi_code(&self) -> bool {
        self.group().field_map.has(tag::CFI_CODE)
    }




    /// Gets `SecurityType`, Tag 167.
    pub fn get_security_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityTypeField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityType` is present, Tag 167.
    pub fn has_security_type(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_TYPE)
    }




    /// Gets `SecuritySubType`, Tag 762.
    pub fn get_security_sub_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecuritySubTypeField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_SUB_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecuritySubType` is present, Tag 762.
    pub fn has_security_sub_type(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_SUB_TYPE)
    }




    /// Gets `MaturityMonthYear`, Tag 200.
    pub fn get_maturity_month_year(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MaturityMonthYearField::new(String::new());
        self.group().field_map.get_field(tag::MATURITY_MONTH_YEAR, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MaturityMonthYear` is present, Tag 200.
    pub fn has_maturity_month_year(&self) -> bool {
        self.group().field_map.has(tag::MATURITY_MONTH_YEAR)
    }




    /// Gets `MaturityDate`, Tag 541.
    pub fn get_maturity_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MaturityDateField::new(String::new());
        self.group().field_map.get_field(tag::MATURITY_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MaturityDate` is present, Tag 541.
    pub fn has_maturity_date(&self) -> bool {
        self.group().field_map.has(tag::MATURITY_DATE)
    }




    /// Gets `CouponPaymentDate`, Tag 224.
    pub fn get_coupon_payment_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CouponPaymentDateField::new(String::new());
        self.group().field_map.get_field(tag::COUPON_PAYMENT_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CouponPaymentDate` is present, Tag 224.
    pub fn has_coupon_payment_date(&self) -> bool {
        self.group().field_map.has(tag::COUPON_PAYMENT_DATE)
    }




    /// Gets `IssueDate`, Tag 225.
    pub fn get_issue_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IssueDateField::new(String::new());
        self.group().field_map.get_field(tag::ISSUE_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `IssueDate` is present, Tag 225.
    pub fn has_issue_date(&self) -> bool {
        self.group().field_map.has(tag::ISSUE_DATE)
    }




    /// Gets `RepoCollateralSecurityType`, Tag 239.
    pub fn get_repo_collateral_security_type(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::RepoCollateralSecurityTypeField::new(0);
        self.group().field_map.get_field(tag::REPO_COLLATERAL_SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RepoCollateralSecurityType` is present, Tag 239.
    pub fn has_repo_collateral_security_type(&self) -> bool {
        self.group().field_map.has(tag::REPO_COLLATERAL_SECURITY_TYPE)
    }




    /// Gets `RepurchaseTerm`, Tag 226.
    pub fn get_repurchase_term(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::RepurchaseTermField::new(0);
        self.group().field_map.get_field(tag::REPURCHASE_TERM, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RepurchaseTerm` is present, Tag 226.
    pub fn has_repurchase_term(&self) -> bool {
        self.group().field_map.has(tag::REPURCHASE_TERM)
    }




    /// Gets `RepurchaseRate`, Tag 227.
    pub fn get_repurchase_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::RepurchaseRateField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::REPURCHASE_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RepurchaseRate` is present, Tag 227.
    pub fn has_repurchase_rate(&self) -> bool {
        self.group().field_map.has(tag::REPURCHASE_RATE)
    }




    /// Gets `Factor`, Tag 228.
    pub fn get_factor(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::FactorField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::FACTOR, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Factor` is present, Tag 228.
    pub fn has_factor(&self) -> bool {
        self.group().field_map.has(tag::FACTOR)
    }




    /// Gets `CreditRating`, Tag 255.
    pub fn get_credit_rating(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CreditRatingField::new(String::new());
        self.group().field_map.get_field(tag::CREDIT_RATING, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CreditRating` is present, Tag 255.
    pub fn has_credit_rating(&self) -> bool {
        self.group().field_map.has(tag::CREDIT_RATING)
    }




    /// Gets `InstrRegistry`, Tag 543.
    pub fn get_instr_registry(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::InstrRegistryField::new(String::new());
        self.group().field_map.get_field(tag::INSTR_REGISTRY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `InstrRegistry` is present, Tag 543.
    pub fn has_instr_registry(&self) -> bool {
        self.group().field_map.has(tag::INSTR_REGISTRY)
    }




    /// Gets `CountryOfIssue`, Tag 470.
    pub fn get_country_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CountryOfIssueField::new(String::new());
        self.group().field_map.get_field(tag::COUNTRY_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CountryOfIssue` is present, Tag 470.
    pub fn has_country_of_issue(&self) -> bool {
        self.group().field_map.has(tag::COUNTRY_OF_ISSUE)
    }




    /// Gets `StateOrProvinceOfIssue`, Tag 471.
    pub fn get_state_or_province_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::StateOrProvinceOfIssueField::new(String::new());
        self.group().field_map.get_field(tag::STATE_OR_PROVINCE_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `StateOrProvinceOfIssue` is present, Tag 471.
    pub fn has_state_or_province_of_issue(&self) -> bool {
        self.group().field_map.has(tag::STATE_OR_PROVINCE_OF_ISSUE)
    }




    /// Gets `LocaleOfIssue`, Tag 472.
    pub fn get_locale_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::LocaleOfIssueField::new(String::new());
        self.group().field_map.get_field(tag::LOCALE_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `LocaleOfIssue` is present, Tag 472.
    pub fn has_locale_of_issue(&self) -> bool {
        self.group().field_map.has(tag::LOCALE_OF_ISSUE)
    }




    /// Gets `RedemptionDate`, Tag 240.
    pub fn get_redemption_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::RedemptionDateField::new(String::new());
        self.group().field_map.get_field(tag::REDEMPTION_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `RedemptionDate` is present, Tag 240.
    pub fn has_redemption_date(&self) -> bool {
        self.group().field_map.has(tag::REDEMPTION_DATE)
    }




    /// Gets `StrikePrice`, Tag 202.
    pub fn get_strike_price(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::StrikePriceField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::STRIKE_PRICE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `StrikePrice` is present, Tag 202.
    pub fn has_strike_price(&self) -> bool {
        self.group().field_map.has(tag::STRIKE_PRICE)
    }




    /// Gets `StrikeCurrency`, Tag 947.
    pub fn get_strike_currency(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::StrikeCurrencyField::new(String::new());
        self.group().field_map.get_field(tag::STRIKE_CURRENCY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `StrikeCurrency` is present, Tag 947.
    pub fn has_strike_currency(&self) -> bool {
        self.group().field_map.has(tag::STRIKE_CURRENCY)
    }




    /// Gets `OptAttribute`, Tag 206.
    pub fn get_opt_attribute(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::OptAttributeField::new(String::new());
        self.group().field_map.get_field(tag::OPT_ATTRIBUTE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `OptAttribute` is present, Tag 206.
    pub fn has_opt_attribute(&self) -> bool {
        self.group().field_map.has(tag::OPT_ATTRIBUTE)
    }




    /// Gets `ContractMultiplier`, Tag 231.
    pub fn get_contract_multiplier(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::ContractMultiplierField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::CONTRACT_MULTIPLIER, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `ContractMultiplier` is present, Tag 231.
    pub fn has_contract_multiplier(&self) -> bool {
        self.group().field_map.has(tag::CONTRACT_MULTIPLIER)
    }




    /// Gets `CouponRate`, Tag 223.
    pub fn get_coupon_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::CouponRateField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::COUPON_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `CouponRate` is present, Tag 223.
    pub fn has_coupon_rate(&self) -> bool {
        self.group().field_map.has(tag::COUPON_RATE)
    }




    /// Gets `SecurityExchange`, Tag 207.
    pub fn get_security_exchange(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityExchangeField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_EXCHANGE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityExchange` is present, Tag 207.
    pub fn has_security_exchange(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_EXCHANGE)
    }




    /// Gets `Issuer`, Tag 106.
    pub fn get_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IssuerField::new(String::new());
        self.group().field_map.get_field(tag::ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Issuer` is present, Tag 106.
    pub fn has_issuer(&self) -> bool {
        self.group().field_map.has(tag::ISSUER)
    }




    /// Gets `EncodedIssuerLen`, Tag 348.
    pub fn get_encoded_issuer_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedIssuerLenField::new(0);
        self.group().field_map.get_field(tag::ENCODED_ISSUER_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedIssuerLen` is present, Tag 348.
    pub fn has_encoded_issuer_len(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_ISSUER_LEN)
    }




    /// Gets `EncodedIssuer`, Tag 349.
    pub fn get_encoded_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedIssuerField::new(String::new());
        self.group().field_map.get_field(tag::ENCODED_ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedIssuer` is present, Tag 349.
    pub fn has_encoded_issuer(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_ISSUER)
    }




    /// Gets `SecurityDesc`, Tag 107.
    pub fn get_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityDescField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityDesc` is present, Tag 107.
    pub fn has_security_desc(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_DESC)
    }




    /// Gets `EncodedSecurityDescLen`, Tag 350.
    pub fn get_encoded_security_desc_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedSecurityDescLenField::new(0);
        self.group().field_map.get_field(tag::ENCODED_SECURITY_DESC_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedSecurityDescLen` is present, Tag 350.
    pub fn has_encoded_security_desc_len(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_SECURITY_DESC_LEN)
    }




    /// Gets `EncodedSecurityDesc`, Tag 351.
    pub fn get_encoded_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedSecurityDescField::new(String::new());
        self.group().field_map.get_field(tag::ENCODED_SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedSecurityDesc` is present, Tag 351.
    pub fn has_encoded_security_desc(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_SECURITY_DESC)
    }




    /// Gets `Pool`, Tag 691.
    pub fn get_pool(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::PoolField::new(String::new());
        self.group().field_map.get_field(tag::POOL, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Pool` is present, Tag 691.
    pub fn has_pool(&self) -> bool {
        self.group().field_map.has(tag::POOL)
    }




    /// Gets `ContractSettlMonth`, Tag 667.
    pub fn get_contract_settl_month(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::ContractSettlMonthField::new(String::new());
        self.group().field_map.get_field(tag::CONTRACT_SETTL_MONTH, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `ContractSettlMonth` is present, Tag 667.
    pub fn has_contract_settl_month(&self) -> bool {
        self.group().field_map.has(tag::CONTRACT_SETTL_MONTH)
    }




    /// Gets `CPProgram`, Tag 875.
    pub fn get_cp_program(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::CPProgramField::new(0);
        self.group().field_map.get_field(tag::CP_PROGRAM, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `CPProgram` is present, Tag 875.
    pub fn has_cp_program(&self) -> bool {
        self.group().field_map.has(tag::CP_PROGRAM)
    }




    /// Gets `CPRegType`, Tag 876.
    pub fn get_cp_reg_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CPRegTypeField::new(String::new());
        self.group().field_map.get_field(tag::CP_REG_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CPRegType` is present, Tag 876.
    pub fn has_cp_reg_type(&self) -> bool {
        self.group().field_map.has(tag::CP_REG_TYPE)
    }




    /// Gets `NoEvents`, Tag 864.
    pub fn get_no_events(&self) -> Result<NoStrikesNoEventsRepeatingGroup, MessageRejectErrorEnum> {
        let g = NoStrikesNoEventsRepeatingGroup::new();
        Ok(NoStrikesNoEventsRepeatingGroup(self.group().field_map.get_group(g.0)?))
    }


    /// Returns true if `NoEvents` is present, Tag 864.
    pub fn has_no_events(&self) -> bool {
        self.group().field_map.has(tag::NO_EVENTS)
    }




    /// Gets `DatedDate`, Tag 873.
    pub fn get_dated_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::DatedDateField::new(String::new());
        self.group().field_map.get_field(tag::DATED_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `DatedDate` is present, Tag 873.
    pub fn has_dated_date(&self) -> bool {
        self.group().field_map.has(tag::DATED_DATE)
    }




    /// Gets `InterestAccrualDate`, Tag 874.
    pub fn get_interest_accrual_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::InterestAccrualDateField::new(String::new());
        self.group().field_map.get_field(tag::INTEREST_ACCRUAL_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `InterestAccrualDate` is present, Tag 874.
    pub fn has_interest_accrual_date(&self) -> bool {
        self.group().field_map.has(tag::INTEREST_ACCRUAL_DATE)
    }


}

impl<G: BorrowMut<Group>> NoStrikes<G> {
    fn group_mut(&mut self) -> &mut Group {
        self.0.borrow_mut()
    }



    /// Sets `Symbol`, Tag 55.
    pub fn set_symbol(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SYMBOL, FIXString::from(v));
    }





    /// Sets `SymbolSfx`, Tag 65.
    pub fn set_symbol_sfx(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SYMBOL_SFX, FIXString::from(v));
    }





    /// Sets `SecurityID`, Tag 48.
    pub fn set_security_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_ID, FIXString::from(v));
    }





    /// Sets `SecurityIDSource`, Tag 22.
    pub fn set_security_id_source(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_ID_SOURCE, FIXString::from(v));
    }





    /// Sets `NoSecurityAltID`, Tag 454.
    pub fn set_no_security_alt_id(&mut self, f: NoStrikesNoSecurityAltIDRepeatingGroup) {
        self.group_mut().field_map.set_group(f.0);
    }





    /// Sets `Product`, Tag 460.
    pub fn set_product(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::PRODUCT, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `CFICode`, Tag 461.
    pub fn set_cfi_code(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::CFI_CODE, FIXString::from(v));
    }





    /// Sets `SecurityType`, Tag 167.
    pub fn set_security_type(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_TYPE, FIXString::from(v));
    }





    /// Sets `SecuritySubType`, Tag 762.
    pub fn set_security_sub_type(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_SUB_TYPE, FIXString::from(v));
    }





    /// Sets `MaturityMonthYear`, Tag 200.
    pub fn set_maturity_month_year(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::MATURITY_MONTH_YEAR, FIXString::from(v));
    }





    /// Sets `MaturityDate`, Tag 541.
    pub fn set_maturity_date(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::MATURITY_DATE, FIXString::from(v));
    }





    /// Sets `CouponPaymentDate`, Tag 224.
    pub fn set_coupon_payment_date(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::COUPON_PAYMENT_DATE, FIXString::from(v));
    }





    /// Sets `IssueDate`, Tag 225.
    pub fn set_issue_date(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ISSUE_DATE, FIXString::from(v));
    }





    /// Sets `RepoCollateralSecurityType`, Tag 239.
    pub fn set_repo_collateral_security_type(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::REPO_COLLATERAL_SECURITY_TYPE, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `RepurchaseTerm`, Tag 226.
    pub fn set_repurchase_term(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::REPURCHASE_TERM, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `RepurchaseRate`, Tag 227.
    pub fn set_repurchase_rate(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::REPURCHASE_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `Factor`, Tag 228.
    pub fn set_factor(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::FACTOR, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `CreditRating`, Tag 255.
    pub fn set_credit_rating(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::CREDIT_RATING, FIXString::from(v));
    }





    /// Sets `InstrRegistry`, Tag 543.
    pub fn set_instr_registry(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::INSTR_REGISTRY, FIXString::from(v));
    }





    /// Sets `CountryOfIssue`, Tag 470.
    pub fn set_country_of_issue(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::COUNTRY_OF_ISSUE, FIXString::from(v));
    }





    /// Sets `StateOrProvinceOfIssue`, Tag 471.
    pub fn set_state_or_province_of_issue(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::STATE_OR_PROVINCE_OF_ISSUE, FIXString::from(v));
    }





    /// Sets `LocaleOfIssue`, Tag 472.
    pub fn set_locale_of_issue(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::LOCALE_OF_ISSUE, FIXString::from(v));
    }





    /// Sets `RedemptionDate`, Tag 240.
    pub fn set_redemption_date(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::REDEMPTION_DATE, FIXString::from(v));
    }





    /// Sets `StrikePrice`, Tag 202.
    pub fn set_strike_price(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::STRIKE_PRICE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `StrikeCurrency`, Tag 947.
    pub fn set_strike_currency(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::STRIKE_CURRENCY, FIXString::from(v));
    }





    /// Sets `OptAttribute`, Tag 206.
    pub fn set_opt_attribute(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::OPT_ATTRIBUTE, FIXString::from(v));
    }





    /// Sets `ContractMultiplier`, Tag 231.
    pub fn set_contract_multiplier(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::CONTRACT_MULTIPLIER, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `CouponRate`, Tag 223.
    pub fn set_coupon_rate(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::COUPON_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `SecurityExchange`, Tag 207.
    pub fn set_security_exchange(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_EXCHANGE, FIXString::from(v));
    }





    /// Sets `Issuer`, Tag 106.
    pub fn set_issuer(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ISSUER, FIXString::from(v));
    }





    /// Sets `EncodedIssuerLen`, Tag 348.
    pub fn set_encoded_issuer_len(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::ENCODED_ISSUER_LEN, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `EncodedIssuer`, Tag 349.
    pub fn set_encoded_issuer(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ENCODED_ISSUER, FIXString::from(v));
    }





    /// Sets `SecurityDesc`, Tag 107.
    pub fn set_security_desc(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_DESC, FIXString::from(v));
    }





    /// Sets `EncodedSecurityDescLen`, Tag 350.
    pub fn set_encoded_security_desc_len(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::ENCODED_SECURITY_DESC_LEN, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `EncodedSecurityDesc`, Tag 351.
    pub fn set_encoded_security_desc(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ENCODED_SECURITY_DESC, FIXString::from(v));
    }





    /// Sets `Pool`, Tag 691.
    pub fn set_pool(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::POOL, FIXString::from(v));
    }





    /// Sets `ContractSettlMonth`, Tag 667.
    pub fn set_contract_settl_month(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::CONTRACT_SETTL_MONTH, FIXString::from(v));
    }





    /// Sets `CPProgram`, Tag 875.
    pub fn set_cp_program(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::CP_PROGRAM, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `CPRegType`, Tag 876.
    pub fn set_cp_reg_type(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::CP_REG_TYPE, FIXString::from(v));
    }





    /// Sets `NoEvents`, Tag 864.
    pub fn set_no_events(&mut self, f: NoStrikesNoEventsRepeatingGroup) {
        self.group_mut().field_map.set_group(f.0);
    }





    /// Sets `DatedDate`, Tag 873.
    pub fn set_dated_date(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::DATED_DATE, FIXString::from(v));
    }





    /// Sets `InterestAccrualDate`, Tag 874.
    pub fn set_interest_accrual_date(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::INTEREST_ACCRUAL_DATE, FIXString::from(v));
    }



}

/// `NoStrikesRepeatingGroup` is the `NoStrikes` repeating group, Tag 428.
pub struct NoStrikesRepeatingGroup(pub RepeatingGroup);

impl NoStrikesRepeatingGroup {
    /// Creates an empty `NoStrikes` group with the template from the FIX spec.
    pub fn new() -> Self {
        let template: GroupTemplate = vec![


            group_element(tag::SYMBOL),



            group_element(tag::SYMBOL_SFX),



            group_element(tag::SECURITY_ID),



            group_element(tag::SECURITY_ID_SOURCE),



            Box::new(NoStrikesNoSecurityAltIDRepeatingGroup::new().0),



            group_element(tag::PRODUCT),



            group_element(tag::CFI_CODE),



            group_element(tag::SECURITY_TYPE),



            group_element(tag::SECURITY_SUB_TYPE),



            group_element(tag::MATURITY_MONTH_YEAR),



            group_element(tag::MATURITY_DATE),



            group_element(tag::COUPON_PAYMENT_DATE),



            group_element(tag::ISSUE_DATE),



            group_element(tag::REPO_COLLATERAL_SECURITY_TYPE),



            group_element(tag::REPURCHASE_TERM),



            group_element(tag::REPURCHASE_RATE),



            group_element(tag::FACTOR),



            group_element(tag::CREDIT_RATING),



            group_element(tag::INSTR_REGISTRY),



            group_element(tag::COUNTRY_OF_ISSUE),



            group_element(tag::STATE_OR_PROVINCE_OF_ISSUE),



            group_element(tag::LOCALE_OF_ISSUE),



            group_element(tag::REDEMPTION_DATE),



            group_element(tag::STRIKE_PRICE),



            group_element(tag::STRIKE_CURRENCY),



            group_element(tag::OPT_ATTRIBUTE),



            group_element(tag::CONTRACT_MULTIPLIER),



            group_element(tag::COUPON_RATE),



            group_element(tag::SECURITY_EXCHANGE),



            group_element(tag::ISSUER),



            group_element(tag::ENCODED_ISSUER_LEN),



            group_element(tag::ENCODED_ISSUER),



            group_element(tag::SECURITY_DESC),



            group_element(tag::ENCODED_SECURITY_DESC_LEN),



            group_element(tag::ENCODED_SECURITY_DESC),



            group_element(tag::POOL),



            group_element(tag::CONTRACT_SETTL_MONTH),



            group_element(tag::CP_PROGRAM),



            group_element(tag::CP_REG_TYPE),



            Box::new(NoStrikesNoEventsRepeatingGroup::new().0),



            group_element(tag::DATED_DATE),



            group_element(tag::INTEREST_ACCRUAL_DATE),


        ];
        Self(RepeatingGroup::new(tag::NO_STRIKES, template))
    }

    /// Appends an entry and returns it for population.
    pub fn add(&mut self) -> NoStrikes<&mut Group> {
        NoStrikes(self.0.add())
    }

    /// Returns the `i`th entry.
    pub fn get(&self, i: usize) -> NoStrikes<&Group> {
        NoStrikes(self.0.get(i))
    }

    /// Returns the number of entries.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns true if the group has no entries.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl Default for NoStrikesRepeatingGroup {
    fn default() -> Self {
        Self::new()
    }
}



/// `NoUnderlyingSecurityAltID` is an entry in the `NoUnderlyingSecurityAltID` repeating group, Tag 457.
pub struct NoUnderlyingsNoUnderlyingSecurityAltID<G>(pub G);

impl<G: Borrow<Group>> NoUnderlyingsNoUnderlyingSecurityAltID<G> {
    fn group(&self) -> &Group {
        self.0.borrow()
    }



    /// Gets `UnderlyingSecurityAltID`, Tag 458.
    pub fn get_underlying_security_alt_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSecurityAltIDField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_SECURITY_ALT_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSecurityAltID` is present, Tag 458.
    pub fn has_underlying_security_alt_id(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_SECURITY_ALT_ID)
    }




    /// Gets `UnderlyingSecurityAltIDSource`, Tag 459.
    pub fn get_underlying_security_alt_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSecurityAltIDSourceField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_SECURITY_ALT_ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSecurityAltIDSource` is present, Tag 459.
    pub fn has_underlying_security_alt_id_source(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_SECURITY_ALT_ID_SOURCE)
    }


}

impl<G: BorrowMut<Group>> NoUnderlyingsNoUnderlyingSecurityAltID<G> {
    fn group_mut(&mut self) -> &mut Group {
        self.0.borrow_mut()
    }



    /// Sets `UnderlyingSecurityAltID`, Tag 458.
    pub fn set_underlying_security_alt_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_SECURITY_ALT_ID, FIXString::from(v));
    }





    /// Sets `UnderlyingSecurityAltIDSource`, Tag 459.
    pub fn set_underlying_security_alt_id_source(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_SECURITY_ALT_ID_SOURCE, FIXString::from(v));
    }



}

/// `NoUnderlyingsNoUnderlyingSecurityAltIDRepeatingGroup` is the `NoUnderlyingSecurityAltID` repeating group, Tag 457.
pub struct NoUnderlyingsNoUnderlyingSecurityAltIDRepeatingGroup(pub RepeatingGroup);

impl NoUnderlyingsNoUnderlyingSecurityAltIDRepeatingGroup {
    /// Creates an empty `NoUnderlyingSecurityAltID` group with the template from the FIX spec.
    pub fn new() -> Self {
        let template: GroupTemplate = vec![


            group_element(tag::UNDERLYING_SECURITY_ALT_ID),



            group_element(tag::UNDERLYING_SECURITY_ALT_ID_SOURCE),


        ];
        Self(RepeatingGroup::new(tag::NO_UNDERLYING_SECURITY_ALT_ID, template))
    }

    /// Appends an entry and returns it for population.
    pub fn add(&mut self) -> NoUnderlyingsNoUnderlyingSecurityAltID<&mut Group> {
        NoUnderlyingsNoUnderlyingSecurityAltID(self.0.add())
    }

    /// Returns the `i`th entry.
    pub fn get(&self, i: usize) -> NoUnderlyingsNoUnderlyingSecurityAltID<&Group> {
        NoUnderlyingsNoUnderlyingSecurityAltID(self.0.get(i))
    }

    /// Returns the number of entries.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns true if the group has no entries.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl Default for NoUnderlyingsNoUnderlyingSecurityAltIDRepeatingGroup {
    fn default() -> Self {
        Self::new()
    }
}



/// `NoUnderlyingStips` is an entry in the `NoUnderlyingStips` repeating group, Tag 887.
pub struct NoUnderlyingsNoUnderlyingStips<G>(pub G);

impl<G: Borrow<Group>> NoUnderlyingsNoUnderlyingStips<G> {
    fn group(&self) -> &Group {
        self.0.borrow()
    }



    /// Gets `UnderlyingStipType`, Tag 888.
    pub fn get_underlying_stip_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingStipTypeField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_STIP_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingStipType` is present, Tag 888.
    pub fn has_underlying_stip_type(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_STIP_TYPE)
    }




    /// Gets `UnderlyingStipValue`, Tag 889.
    pub fn get_underlying_stip_value(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingStipValueField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_STIP_VALUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingStipValue` is present, Tag 889.
    pub fn has_underlying_stip_value(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_STIP_VALUE)
    }


}

impl<G: BorrowMut<Group>> NoUnderlyingsNoUnderlyingStips<G> {
    fn group_mut(&mut self) -> &mut Group {
        self.0.borrow_mut()
    }



    /// Sets `UnderlyingStipType`, Tag 888.
    pub fn set_underlying_stip_type(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_STIP_TYPE, FIXString::from(v));
    }





    /// Sets `UnderlyingStipValue`, Tag 889.
    pub fn set_underlying_stip_value(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_STIP_VALUE, FIXString::from(v));
    }



}

/// `NoUnderlyingsNoUnderlyingStipsRepeatingGroup` is the `NoUnderlyingStips` repeating group, Tag 887.
pub struct NoUnderlyingsNoUnderlyingStipsRepeatingGroup(pub RepeatingGroup);

impl NoUnderlyingsNoUnderlyingStipsRepeatingGroup {
    /// Creates an empty `NoUnderlyingStips` group with the template from the FIX spec.
    pub fn new() -> Self {
        let template: GroupTemplate = vec![


            group_element(tag::UNDERLYING_STIP_TYPE),



            group_element(tag::UNDERLYING_STIP_VALUE),


        ];
        Self(RepeatingGroup::new(tag::NO_UNDERLYING_STIPS, template))
    }

    /// Appends an entry and returns it for population.
    pub fn add(&mut self) -> NoUnderlyingsNoUnderlyingStips<&mut Group> {
        NoUnderlyingsNoUnderlyingStips(self.0.add())
    }

    /// Returns the `i`th entry.
    pub fn get(&self, i: usize) -> NoUnderlyingsNoUnderlyingStips<&Group> {
        NoUnderlyingsNoUnderlyingStips(self.0.get(i))
    }

    /// Returns the number of entries.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns true if the group has no entries.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl Default for NoUnderlyingsNoUnderlyingStipsRepeatingGroup {
    fn default() -> Self {
        Self::new()
    }
}



/// `NoUnderlyings` is an entry in the `NoUnderlyings` repeating group, Tag 711.
pub struct NoUnderlyings<G>(pub G);

impl<G: Borrow<Group>> NoUnderlyings<G> {
    fn group(&self) -> &Group {
        self.0.borrow()
    }



    /// Gets `UnderlyingSymbol`, Tag 311.
    pub fn get_underlying_symbol(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSymbolField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_SYMBOL, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSymbol` is present, Tag 311.
    pub fn has_underlying_symbol(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_SYMBOL)
    }




    /// Gets `UnderlyingSymbolSfx`, Tag 312.
    pub fn get_underlying_symbol_sfx(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSymbolSfxField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_SYMBOL_SFX, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSymbolSfx` is present, Tag 312.
    pub fn has_underlying_symbol_sfx(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_SYMBOL_SFX)
    }




    /// Gets `UnderlyingSecurityID`, Tag 309.
    pub fn get_underlying_security_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSecurityIDField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_SECURITY_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSecurityID` is present, Tag 309.
    pub fn has_underlying_security_id(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_SECURITY_ID)
    }




    /// Gets `UnderlyingSecurityIDSource`, Tag 305.
    pub fn get_underlying_security_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSecurityIDSourceField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_SECURITY_ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSecurityIDSource` is present, Tag 305.
    pub fn has_underlying_security_id_source(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_SECURITY_ID_SOURCE)
    }




    /// Gets `NoUnderlyingSecurityAltID`, Tag 457.
    pub fn get_no_underlying_security_alt_id(&self) -> Result<NoUnderlyingsNoUnderlyingSecurityAltIDRepeatingGroup, MessageRejectErrorEnum> {
        let g = NoUnderlyingsNoUnderlyingSecurityAltIDRepeatingGroup::new();
        Ok(NoUnderlyingsNoUnderlyingSecurityAltIDRepeatingGroup(self.group().field_map.get_group(g.0)?))
    }


    /// Returns true if `NoUnderlyingSecurityAltID` is present, Tag 457.
    pub fn has_no_underlying_security_alt_id(&self) -> bool {
        self.group().field_map.has(tag::NO_UNDERLYING_SECURITY_ALT_ID)
    }




    /// Gets `UnderlyingProduct`, Tag 462.
    pub fn get_underlying_product(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingProductField::new(0);
        self.group().field_map.get_field(tag::UNDERLYING_PRODUCT, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingProduct` is present, Tag 462.
    pub fn has_underlying_product(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_PRODUCT)
    }




    /// Gets `UnderlyingCFICode`, Tag 463.
    pub fn get_underlying_cfi_code(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingCFICodeField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_CFI_CODE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingCFICode` is present, Tag 463.
    pub fn has_underlying_cfi_code(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_CFI_CODE)
    }




    /// Gets `UnderlyingSecurityType`, Tag 310.
    pub fn get_underlying_security_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSecurityTypeField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSecurityType` is present, Tag 310.
    pub fn has_underlying_security_type(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_SECURITY_TYPE)
    }




    /// Gets `UnderlyingSecuritySubType`, Tag 763.
    pub fn get_underlying_security_sub_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSecuritySubTypeField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_SECURITY_SUB_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSecuritySubType` is present, Tag 763.
    pub fn has_underlying_security_sub_type(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_SECURITY_SUB_TYPE)
    }




    /// Gets `UnderlyingMaturityMonthYear`, Tag 313.
    pub fn get_underlying_maturity_month_year(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingMaturityMonthYearField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_MATURITY_MONTH_YEAR, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingMaturityMonthYear` is present, Tag 313.
    pub fn has_underlying_maturity_month_year(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_MATURITY_MONTH_YEAR)
    }




    /// Gets `UnderlyingMaturityDate`, Tag 542.
    pub fn get_underlying_maturity_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingMaturityDateField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_MATURITY_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingMaturityDate` is present, Tag 542.
    pub fn has_underlying_maturity_date(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_MATURITY_DATE)
    }




    /// Gets `UnderlyingCouponPaymentDate`, Tag 241.
    pub fn get_underlying_coupon_payment_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingCouponPaymentDateField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_COUPON_PAYMENT_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingCouponPaymentDate` is present, Tag 241.
    pub fn has_underlying_coupon_payment_date(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_COUPON_PAYMENT_DATE)
    }




    /// Gets `UnderlyingIssueDate`, Tag 242.
    pub fn get_underlying_issue_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingIssueDateField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_ISSUE_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingIssueDate` is present, Tag 242.
    pub fn has_underlying_issue_date(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_ISSUE_DATE)
    }




    /// Gets `UnderlyingRepoCollateralSecurityType`, Tag 243.
    pub fn get_underlying_repo_collateral_security_type(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingRepoCollateralSecurityTypeField::new(0);
        self.group().field_map.get_field(tag::UNDERLYING_REPO_COLLATERAL_SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingRepoCollateralSecurityType` is present, Tag 243.
    pub fn has_underlying_repo_collateral_security_type(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_REPO_COLLATERAL_SECURITY_TYPE)
    }




    /// Gets `UnderlyingRepurchaseTerm`, Tag 244.
    pub fn get_underlying_repurchase_term(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingRepurchaseTermField::new(0);
        self.group().field_map.get_field(tag::UNDERLYING_REPURCHASE_TERM, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingRepurchaseTerm` is present, Tag 244.
    pub fn has_underlying_repurchase_term(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_REPURCHASE_TERM)
    }




    /// Gets `UnderlyingRepurchaseRate`, Tag 245.
    pub fn get_underlying_repurchase_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingRepurchaseRateField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::UNDERLYING_REPURCHASE_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingRepurchaseRate` is present, Tag 245.
    pub fn has_underlying_repurchase_rate(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_REPURCHASE_RATE)
    }




    /// Gets `UnderlyingFactor`, Tag 246.
    pub fn get_underlying_factor(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingFactorField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::UNDERLYING_FACTOR, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingFactor` is present, Tag 246.
    pub fn has_underlying_factor(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_FACTOR)
    }




    /// Gets `UnderlyingCreditRating`, Tag 256.
    pub fn get_underlying_credit_rating(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingCreditRatingField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_CREDIT_RATING, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingCreditRating` is present, Tag 256.
    pub fn has_underlying_credit_rating(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_CREDIT_RATING)
    }




    /// Gets `UnderlyingInstrRegistry`, Tag 595.
    pub fn get_underlying_instr_registry(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingInstrRegistryField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_INSTR_REGISTRY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingInstrRegistry` is present, Tag 595.
    pub fn has_underlying_instr_registry(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_INSTR_REGISTRY)
    }




    /// Gets `UnderlyingCountryOfIssue`, Tag 592.
    pub fn get_underlying_country_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingCountryOfIssueField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_COUNTRY_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingCountryOfIssue` is present, Tag 592.
    pub fn has_underlying_country_of_issue(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_COUNTRY_OF_ISSUE)
    }




    /// Gets `UnderlyingStateOrProvinceOfIssue`, Tag 593.
    pub fn get_underlying_state_or_province_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingStateOrProvinceOfIssueField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_STATE_OR_PROVINCE_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingStateOrProvinceOfIssue` is present, Tag 593.
    pub fn has_underlying_state_or_province_of_issue(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_STATE_OR_PROVINCE_OF_ISSUE)
    }




    /// Gets `UnderlyingLocaleOfIssue`, Tag 594.
    pub fn get_underlying_locale_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingLocaleOfIssueField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_LOCALE_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingLocaleOfIssue` is present, Tag 594.
    pub fn has_underlying_locale_of_issue(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_LOCALE_OF_ISSUE)
    }




    /// Gets `UnderlyingRedemptionDate`, Tag 247.
    pub fn get_underlying_redemption_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingRedemptionDateField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_REDEMPTION_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingRedemptionDate` is present, Tag 247.
    pub fn has_underlying_redemption_date(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_REDEMPTION_DATE)
    }




    /// Gets `UnderlyingStrikePrice`, Tag 316.
    pub fn get_underlying_strike_price(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingStrikePriceField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::UNDERLYING_STRIKE_PRICE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingStrikePrice` is present, Tag 316.
    pub fn has_underlying_strike_price(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_STRIKE_PRICE)
    }




    /// Gets `UnderlyingStrikeCurrency`, Tag 941.
    pub fn get_underlying_strike_currency(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingStrikeCurrencyField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_STRIKE_CURRENCY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingStrikeCurrency` is present, Tag 941.
    pub fn has_underlying_strike_currency(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_STRIKE_CURRENCY)
    }




    /// Gets `UnderlyingOptAttribute`, Tag 317.
    pub fn get_underlying_opt_attribute(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingOptAttributeField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_OPT_ATTRIBUTE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingOptAttribute` is present, Tag 317.
    pub fn has_underlying_opt_attribute(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_OPT_ATTRIBUTE)
    }




    /// Gets `UnderlyingContractMultiplier`, Tag 436.
    pub fn get_underlying_contract_multiplier(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingContractMultiplierField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::UNDERLYING_CONTRACT_MULTIPLIER, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingContractMultiplier` is present, Tag 436.
    pub fn has_underlying_contract_multiplier(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_CONTRACT_MULTIPLIER)
    }




    /// Gets `UnderlyingCouponRate`, Tag 435.
    pub fn get_underlying_coupon_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingCouponRateField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::UNDERLYING_COUPON_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingCouponRate` is present, Tag 435.
    pub fn has_underlying_coupon_rate(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_COUPON_RATE)
    }




    /// Gets `UnderlyingSecurityExchange`, Tag 308.
    pub fn get_underlying_security_exchange(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSecurityExchangeField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_SECURITY_EXCHANGE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSecurityExchange` is present, Tag 308.
    pub fn has_underlying_security_exchange(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_SECURITY_EXCHANGE)
    }




    /// Gets `UnderlyingIssuer`, Tag 306.
    pub fn get_underlying_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingIssuerField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingIssuer` is present, Tag 306.
    pub fn has_underlying_issuer(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_ISSUER)
    }




    /// Gets `EncodedUnderlyingIssuerLen`, Tag 362.
    pub fn get_encoded_underlying_issuer_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedUnderlyingIssuerLenField::new(0);
        self.group().field_map.get_field(tag::ENCODED_UNDERLYING_ISSUER_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedUnderlyingIssuerLen` is present, Tag 362.
    pub fn has_encoded_underlying_issuer_len(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_UNDERLYING_ISSUER_LEN)
    }




    /// Gets `EncodedUnderlyingIssuer`, Tag 363.
    pub fn get_encoded_underlying_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedUnderlyingIssuerField::new(String::new());
        self.group().field_map.get_field(tag::ENCODED_UNDERLYING_ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedUnderlyingIssuer` is present, Tag 363.
    pub fn has_encoded_underlying_issuer(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_UNDERLYING_ISSUER)
    }




    /// Gets `UnderlyingSecurityDesc`, Tag 307.
    pub fn get_underlying_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSecurityDescField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSecurityDesc` is present, Tag 307.
    pub fn has_underlying_security_desc(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_SECURITY_DESC)
    }




    /// Gets `EncodedUnderlyingSecurityDescLen`, Tag 364.
    pub fn get_encoded_underlying_security_desc_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedUnderlyingSecurityDescLenField::new(0);
        self.group().field_map.get_field(tag::ENCODED_UNDERLYING_SECURITY_DESC_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedUnderlyingSecurityDescLen` is present, Tag 364.
    pub fn has_encoded_underlying_security_desc_len(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_UNDERLYING_SECURITY_DESC_LEN)
    }




    /// Gets `EncodedUnderlyingSecurityDesc`, Tag 365.
    pub fn get_encoded_underlying_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedUnderlyingSecurityDescField::new(String::new());
        self.group().field_map.get_field(tag::ENCODED_UNDERLYING_SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedUnderlyingSecurityDesc` is present, Tag 365.
    pub fn has_encoded_underlying_security_desc(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_UNDERLYING_SECURITY_DESC)
    }




    /// Gets `UnderlyingCPProgram`, Tag 877.
    pub fn get_underlying_cp_program(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingCPProgramField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_CP_PROGRAM, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingCPProgram` is present, Tag 877.
    pub fn has_underlying_cp_program(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_CP_PROGRAM)
    }




    /// Gets `UnderlyingCPRegType`, Tag 878.
    pub fn get_underlying_cp_reg_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingCPRegTypeField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_CP_REG_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingCPRegType` is present, Tag 878.
    pub fn has_underlying_cp_reg_type(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_CP_REG_TYPE)
    }




    /// Gets `UnderlyingCurrency`, Tag 318.
    pub fn get_underlying_currency(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingCurrencyField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_CURRENCY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingCurrency` is present, Tag 318.
    pub fn has_underlying_currency(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_CURRENCY)
    }




    /// Gets `UnderlyingQty`, Tag 879.
    pub fn get_underlying_qty(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingQtyField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::UNDERLYING_QTY, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingQty` is present, Tag 879.
    pub fn has_underlying_qty(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_QTY)
    }




    /// Gets `UnderlyingPx`, Tag 810.
    pub fn get_underlying_px(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingPxField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::UNDERLYING_PX, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingPx` is present, Tag 810.
    pub fn has_underlying_px(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_PX)
    }




    /// Gets `UnderlyingDirtyPrice`, Tag 882.
    pub fn get_underlying_dirty_price(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingDirtyPriceField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::UNDERLYING_DIRTY_PRICE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingDirtyPrice` is present, Tag 882.
    pub fn has_underlying_dirty_price(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_DIRTY_PRICE)
    }




    /// Gets `UnderlyingEndPrice`, Tag 883.
    pub fn get_underlying_end_price(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingEndPriceField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::UNDERLYING_END_PRICE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingEndPrice` is present, Tag 883.
    pub fn has_underlying_end_price(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_END_PRICE)
    }




    /// Gets `UnderlyingStartValue`, Tag 884.
    pub fn get_underlying_start_value(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingStartValueField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::UNDERLYING_START_VALUE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingStartValue` is present, Tag 884.
    pub fn has_underlying_start_value(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_START_VALUE)
    }




    /// Gets `UnderlyingCurrentValue`, Tag 885.
    pub fn get_underlying_current_value(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingCurrentValueField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::UNDERLYING_CURRENT_VALUE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingCurrentValue` is present, Tag 885.
    pub fn has_underlying_current_value(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_CURRENT_VALUE)
    }




    /// Gets `UnderlyingEndValue`, Tag 886.
    pub fn get_underlying_end_value(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingEndValueField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::UNDERLYING_END_VALUE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingEndValue` is present, Tag 886.
    pub fn has_underlying_end_value(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_END_VALUE)
    }




    /// Gets `NoUnderlyingStips`, Tag 887.
    pub fn get_no_underlying_stips(&self) -> Result<NoUnderlyingsNoUnderlyingStipsRepeatingGroup, MessageRejectErrorEnum> {
        let g = NoUnderlyingsNoUnderlyingStipsRepeatingGroup::new();
        Ok(NoUnderlyingsNoUnderlyingStipsRepeatingGroup(self.group().field_map.get_group(g.0)?))
    }


    /// Returns true if `NoUnderlyingStips` is present, Tag 887.
    pub fn has_no_underlying_stips(&self) -> bool {
        self.group().field_map.has(tag::NO_UNDERLYING_STIPS)
    }




    /// Gets `PrevClosePx`, Tag 140.
    pub fn get_prev_close_px(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::PrevClosePxField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::PREV_CLOSE_PX, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `PrevClosePx` is present, Tag 140.
    pub fn has_prev_close_px(&self) -> bool {
        self.group().field_map.has(tag::PREV_CLOSE_PX)
    }




    /// Gets `ClOrdID`, Tag 11.
    pub fn get_cl_ord_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::ClOrdIDField::new(String::new());
        self.group().field_map.get_field(tag::CL_ORD_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `ClOrdID` is present, Tag 11.
    pub fn has_cl_ord_id(&self) -> bool {
        self.group().field_map.has(tag::CL_ORD_ID)
    }




    /// Gets `SecondaryClOrdID`, Tag 526.
    pub fn get_secondary_cl_ord_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecondaryClOrdIDField::new(String::new());
        self.group().field_map.get_field(tag::SECONDARY_CL_ORD_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecondaryClOrdID` is present, Tag 526.
    pub fn has_secondary_cl_ord_id(&self) -> bool {
        self.group().field_map.has(tag::SECONDARY_CL_ORD_ID)
    }




    /// Gets `Side`, Tag 54.
    pub fn get_side(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SideField::new(String::new());
        self.group().field_map.get_field(tag::SIDE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Side` is present, Tag 54.
    pub fn has_side(&self) -> bool {
        self.group().field_map.has(tag::SIDE)
    }




    /// Gets `Price`, Tag 44.
    pub fn get_price(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::PriceField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::PRICE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Price` is present, Tag 44.
    pub fn has_price(&self) -> bool {
        self.group().field_map.has(tag::PRICE)
    }




    /// Gets `Currency`, Tag 15.
    pub fn get_currency(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CurrencyField::new(String::new());
        self.group().field_map.get_field(tag::CURRENCY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Currency` is present, Tag 15.
    pub fn has_currency(&self) -> bool {
        self.group().field_map.has(tag::CURRENCY)
    }




    /// Gets `Text`, Tag 58.
    pub fn get_text(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TextField::new(String::new());
        self.group().field_map.get_field(tag::TEXT, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Text` is present, Tag 58.
    pub fn has_text(&self) -> bool {
        self.group().field_map.has(tag::TEXT)
    }




    /// Gets `EncodedTextLen`, Tag 354.
    pub fn get_encoded_text_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedTextLenField::new(0);
        self.group().field_map.get_field(tag::ENCODED_TEXT_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedTextLen` is present, Tag 354.
    pub fn has_encoded_text_len(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_TEXT_LEN)
    }




    /// Gets `EncodedText`, Tag 355.
    pub fn get_encoded_text(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedTextField::new(String::new());
        self.group().field_map.get_field(tag::ENCODED_TEXT, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedText` is present, Tag 355.
    pub fn has_encoded_text(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_TEXT)
    }


}

impl<G: BorrowMut<Group>> NoUnderlyings<G> {
    fn group_mut(&mut self) -> &mut Group {
        self.0.borrow_mut()
    }



    /// Sets `UnderlyingSymbol`, Tag 311.
    pub fn set_underlying_symbol(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_SYMBOL, FIXString::from(v));
    }





    /// Sets `UnderlyingSymbolSfx`, Tag 312.
    pub fn set_underlying_symbol_sfx(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_SYMBOL_SFX, FIXString::from(v));
    }





    /// Sets `UnderlyingSecurityID`, Tag 309.
    pub fn set_underlying_security_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_SECURITY_ID, FIXString::from(v));
    }





    /// Sets `UnderlyingSecurityIDSource`, Tag 305.
    pub fn set_underlying_security_id_source(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_SECURITY_ID_SOURCE, FIXString::from(v));
    }





    /// Sets `NoUnderlyingSecurityAltID`, Tag 457.
    pub fn set_no_underlying_security_alt_id(&mut self, f: NoUnderlyingsNoUnderlyingSecurityAltIDRepeatingGroup) {
        self.group_mut().field_map.set_group(f.0);
    }





    /// Sets `UnderlyingProduct`, Tag 462.
    pub fn set_underlying_product(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_PRODUCT, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `UnderlyingCFICode`, Tag 463.
    pub fn set_underlying_cfi_code(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_CFI_CODE, FIXString::from(v));
    }





    /// Sets `UnderlyingSecurityType`, Tag 310.
    pub fn set_underlying_security_type(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_SECURITY_TYPE, FIXString::from(v));
    }





    /// Sets `UnderlyingSecuritySubType`, Tag 763.
    pub fn set_underlying_security_sub_type(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_SECURITY_SUB_TYPE, FIXString::from(v));
    }





    /// Sets `UnderlyingMaturityMonthYear`, Tag 313.
    pub fn set_underlying_maturity_month_year(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_MATURITY_MONTH_YEAR, FIXString::from(v));
    }





    /// Sets `UnderlyingMaturityDate`, Tag 542.
    pub fn set_underlying_maturity_date(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_MATURITY_DATE, FIXString::from(v));
    }





    /// Sets `UnderlyingCouponPaymentDate`, Tag 241.
    pub fn set_underlying_coupon_payment_date(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_COUPON_PAYMENT_DATE, FIXString::from(v));
    }





    /// Sets `UnderlyingIssueDate`, Tag 242.
    pub fn set_underlying_issue_date(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_ISSUE_DATE, FIXString::from(v));
    }





    /// Sets `UnderlyingRepoCollateralSecurityType`, Tag 243.
    pub fn set_underlying_repo_collateral_security_type(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_REPO_COLLATERAL_SECURITY_TYPE, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `UnderlyingRepurchaseTerm`, Tag 244.
    pub fn set_underlying_repurchase_term(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_REPURCHASE_TERM, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `UnderlyingRepurchaseRate`, Tag 245.
    pub fn set_underlying_repurchase_rate(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_REPURCHASE_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `UnderlyingFactor`, Tag 246.
    pub fn set_underlying_factor(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_FACTOR, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `UnderlyingCreditRating`, Tag 256.
    pub fn set_underlying_credit_rating(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_CREDIT_RATING, FIXString::from(v));
    }





    /// Sets `UnderlyingInstrRegistry`, Tag 595.
    pub fn set_underlying_instr_registry(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_INSTR_REGISTRY, FIXString::from(v));
    }





    /// Sets `UnderlyingCountryOfIssue`, Tag 592.
    pub fn set_underlying_country_of_issue(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_COUNTRY_OF_ISSUE, FIXString::from(v));
    }





    /// Sets `UnderlyingStateOrProvinceOfIssue`, Tag 593.
    pub fn set_underlying_state_or_province_of_issue(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_STATE_OR_PROVINCE_OF_ISSUE, FIXString::from(v));
    }





    /// Sets `UnderlyingLocaleOfIssue`, Tag 594.
    pub fn set_underlying_locale_of_issue(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_LOCALE_OF_ISSUE, FIXString::from(v));
    }





    /// Sets `UnderlyingRedemptionDate`, Tag 247.
    pub fn set_underlying_redemption_date(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_REDEMPTION_DATE, FIXString::from(v));
    }





    /// Sets `UnderlyingStrikePrice`, Tag 316.
    pub fn set_underlying_strike_price(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_STRIKE_PRICE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `UnderlyingStrikeCurrency`, Tag 941.
    pub fn set_underlying_strike_currency(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_STRIKE_CURRENCY, FIXString::from(v));
    }





    /// Sets `UnderlyingOptAttribute`, Tag 317.
    pub fn set_underlying_opt_attribute(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_OPT_ATTRIBUTE, FIXString::from(v));
    }





    /// Sets `UnderlyingContractMultiplier`, Tag 436.
    pub fn set_underlying_contract_multiplier(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_CONTRACT_MULTIPLIER, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `UnderlyingCouponRate`, Tag 435.
    pub fn set_underlying_coupon_rate(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_COUPON_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `UnderlyingSecurityExchange`, Tag 308.
    pub fn set_underlying_security_exchange(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_SECURITY_EXCHANGE, FIXString::from(v));
    }





    /// Sets `UnderlyingIssuer`, Tag 306.
    pub fn set_underlying_issuer(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_ISSUER, FIXString::from(v));
    }





    /// Sets `EncodedUnderlyingIssuerLen`, Tag 362.
    pub fn set_encoded_underlying_issuer_len(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::ENCODED_UNDERLYING_ISSUER_LEN, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `EncodedUnderlyingIssuer`, Tag 363.
    pub fn set_encoded_underlying_issuer(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ENCODED_UNDERLYING_ISSUER, FIXString::from(v));
    }





    /// Sets `UnderlyingSecurityDesc`, Tag 307.
    pub fn set_underlying_security_desc(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_SECURITY_DESC, FIXString::from(v));
    }





    /// Sets `EncodedUnderlyingSecurityDescLen`, Tag 364.
    pub fn set_encoded_underlying_security_desc_len(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::ENCODED_UNDERLYING_SECURITY_DESC_LEN, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `EncodedUnderlyingSecurityDesc`, Tag 365.
    pub fn set_encoded_underlying_security_desc(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ENCODED_UNDERLYING_SECURITY_DESC, FIXString::from(v));
    }





    /// Sets `UnderlyingCPProgram`, Tag 877.
    pub fn set_underlying_cp_program(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_CP_PROGRAM, FIXString::from(v));
    }





    /// Sets `UnderlyingCPRegType`, Tag 878.
    pub fn set_underlying_cp_reg_type(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_CP_REG_TYPE, FIXString::from(v));
    }





    /// Sets `UnderlyingCurrency`, Tag 318.
    pub fn set_underlying_currency(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_CURRENCY, FIXString::from(v));
    }





    /// Sets `UnderlyingQty`, Tag 879.
    pub fn set_underlying_qty(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_QTY, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `UnderlyingPx`, Tag 810.
    pub fn set_underlying_px(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_PX, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `UnderlyingDirtyPrice`, Tag 882.
    pub fn set_underlying_dirty_price(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_DIRTY_PRICE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `UnderlyingEndPrice`, Tag 883.
    pub fn set_underlying_end_price(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_END_PRICE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `UnderlyingStartValue`, Tag 884.
    pub fn set_underlying_start_value(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_START_VALUE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `UnderlyingCurrentValue`, Tag 885.
    pub fn set_underlying_current_value(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_CURRENT_VALUE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `UnderlyingEndValue`, Tag 886.
    pub fn set_underlying_end_value(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_END_VALUE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `NoUnderlyingStips`, Tag 887.
    pub fn set_no_underlying_stips(&mut self, f: NoUnderlyingsNoUnderlyingStipsRepeatingGroup) {
        self.group_mut().field_map.set_group(f.0);
    }





    /// Sets `PrevClosePx`, Tag 140.
    pub fn set_prev_close_px(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::PREV_CLOSE_PX, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `ClOrdID`, Tag 11.
    pub fn set_cl_ord_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::CL_ORD_ID, FIXString::from(v));
    }





    /// Sets `SecondaryClOrdID`, Tag 526.
    pub fn set_secondary_cl_ord_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECONDARY_CL_ORD_ID, FIXString::from(v));
    }





    /// Sets `Side`, Tag 54.
    pub fn set_side(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SIDE, FIXString::from(v));
    }





    /// Sets `Price`, Tag 44.
    pub fn set_price(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::PRICE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `Currency`, Tag 15.
    pub fn set_currency(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::CURRENCY, FIXString::from(v));
    }





    /// Sets `Text`, Tag 58.
    pub fn set_text(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::TEXT, FIXString::from(v));
    }





    /// Sets `EncodedTextLen`, Tag 354.
    pub fn set_encoded_text_len(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::ENCODED_TEXT_LEN, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `EncodedText`, Tag 355.
    pub fn set_encoded_text(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ENCODED_TEXT, FIXString::from(v));
    }



}

/// `NoUnderlyingsRepeatingGroup` is the `NoUnderlyings` repeating group, Tag 711.
pub struct NoUnderlyingsRepeatingGroup(pub RepeatingGroup);

impl NoUnderlyingsRepeatingGroup {
    /// Creates an empty `NoUnderlyings` group with the template from the FIX spec.
    pub fn new() -> Self {
        let template: GroupTemplate = vec![


            group_element(tag::UNDERLYING_SYMBOL),



            group_element(tag::UNDERLYING_SYMBOL_SFX),



            group_element(tag::UNDERLYING_SECURITY_ID),



            group_element(tag::UNDERLYING_SECURITY_ID_SOURCE),



            Box::new(NoUnderlyingsNoUnderlyingSecurityAltIDRepeatingGroup::new().0),



            group_element(tag::UNDERLYING_PRODUCT),



            group_element(tag::UNDERLYING_CFI_CODE),



            group_element(tag::UNDERLYING_SECURITY_TYPE),



            group_element(tag::UNDERLYING_SECURITY_SUB_TYPE),



            group_element(tag::UNDERLYING_MATURITY_MONTH_YEAR),



            group_element(tag::UNDERLYING_MATURITY_DATE),



            group_element(tag::UNDERLYING_COUPON_PAYMENT_DATE),



            group_element(tag::UNDERLYING_ISSUE_DATE),



            group_element(tag::UNDERLYING_REPO_COLLATERAL_SECURITY_TYPE),



            group_element(tag::UNDERLYING_REPURCHASE_TERM),



            group_element(tag::UNDERLYING_REPURCHASE_RATE),



            group_element(tag::UNDERLYING_FACTOR),



            group_element(tag::UNDERLYING_CREDIT_RATING),



            group_element(tag::UNDERLYING_INSTR_REGISTRY),



            group_element(tag::UNDERLYING_COUNTRY_OF_ISSUE),



            group_element(tag::UNDERLYING_STATE_OR_PROVINCE_OF_ISSUE),



            group_element(tag::UNDERLYING_LOCALE_OF_ISSUE),



            group_element(tag::UNDERLYING_REDEMPTION_DATE),



            group_element(tag::UNDERLYING_STRIKE_PRICE),



            group_element(tag::UNDERLYING_STRIKE_CURRENCY),



            group_element(tag::UNDERLYING_OPT_ATTRIBUTE),



            group_element(tag::UNDERLYING_CONTRACT_MULTIPLIER),



            group_element(tag::UNDERLYING_COUPON_RATE),



            group_element(tag::UNDERLYING_SECURITY_EXCHANGE),



            group_element(tag::UNDERLYING_ISSUER),



            group_element(tag::ENCODED_UNDERLYING_ISSUER_LEN),



            group_element(tag::ENCODED_UNDERLYING_ISSUER),



            group_element(tag::UNDERLYING_SECURITY_DESC),



            group_element(tag::ENCODED_UNDERLYING_SECURITY_DESC_LEN),



            group_element(tag::ENCODED_UNDERLYING_SECURITY_DESC),



            group_element(tag::UNDERLYING_CP_PROGRAM),



            group_element(tag::UNDERLYING_CP_REG_TYPE),



            group_element(tag::UNDERLYING_CURRENCY),



            group_element(tag::UNDERLYING_QTY),



            group_element(tag::UNDERLYING_PX),



            group_element(tag::UNDERLYING_DIRTY_PRICE),



            group_element(tag::UNDERLYING_END_PRICE),



            group_element(tag::UNDERLYING_START_VALUE),



            group_element(tag::UNDERLYING_CURRENT_VALUE),



            group_element(tag::UNDERLYING_END_VALUE),



            Box::new(NoUnderlyingsNoUnderlyingStipsRepeatingGroup::new().0),



            group_element(tag::PREV_CLOSE_PX),



            group_element(tag::CL_ORD_ID),



            group_element(tag::SECONDARY_CL_ORD_ID),



            group_element(tag::SIDE),



            group_element(tag::PRICE),



            group_element(tag::CURRENCY),



            group_element(tag::TEXT),



            group_element(tag::ENCODED_TEXT_LEN),



            group_element(tag::ENCODED_TEXT),


        ];
        Self(RepeatingGroup::new(tag::NO_UNDERLYINGS, template))
    }

    /// Appends an entry and returns it for population.
    pub fn add(&mut self) -> NoUnderlyings<&mut Group> {
        NoUnderlyings(self.0.add())
    }

    /// Returns the `i`th entry.
    pub fn get(&self, i: usize) -> NoUnderlyings<&Group> {
        NoUnderlyings(self.0.get(i))
    }

    /// Returns the number of entries.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns true if the group has no entries.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl Default for NoUnderlyingsRepeatingGroup {
    fn default() -> Self {
        Self::new()
    }
}

