// Code generated by fixer-gen. DO NOT EDIT.
#![allow(clippy::new_without_default)]
#![allow(clippy::needless_pass_by_value)]
#![allow(clippy::too_many_arguments)]
#![allow(unused_imports)]

use fixer::message::Message;
use fixer::fix_string::FIXString;
use fixer::errors::MessageRejectErrorEnum;
use fixer::session::session_id::SessionID;

use rust_decimal::Decimal;


use jiff::Timestamp;

use crate::field;
use crate::tag;

/// `Advertisement` is the `fix42` `Advertisement` type, `MsgType` = 7.
pub struct Advertisement {
    pub message: Message,
}

impl Advertisement {
    /// Creates a new `Advertisement` with required fields.
    pub fn new(adv_id: field::AdvIdField, adv_trans_type: field::AdvTransTypeField, symbol: field::SymbolField, adv_side: field::AdvSideField, shares: field::SharesField) -> Self {
        let mut msg = Message::new();
        msg.header.set_field(tag::MSG_TYPE, FIXString::from("7".to_string()));

        msg.body.set_field(tag::ADV_ID, adv_id.0);

        msg.body.set_field(tag::ADV_TRANS_TYPE, adv_trans_type.0);

        msg.body.set_field(tag::SYMBOL, symbol.0);

        msg.body.set_field(tag::ADV_SIDE, adv_side.0);

        msg.body.set_field(tag::SHARES, shares.0);

        Self { message: msg }
    }

    /// Creates a `Advertisement` from an existing `Message`.
    pub fn from_message(msg: Message) -> Self {
        Self { message: msg }
    }

    /// Returns the underlying `Message`.
    pub fn to_message(self) -> Message {
        self.message
    }




    /// Sets `AdvId`, Tag 2.
    pub fn set_adv_id(&mut self, v: String) {
        self.message.body.set_field(tag::ADV_ID, FIXString::from(v));
    }

    /// Gets `AdvId`, Tag 2.
    pub fn get_adv_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::AdvIdField::new(String::new());
        self.message.body.get_field(tag::ADV_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `AdvId` is present, Tag 2.
    pub fn has_adv_id(&self) -> bool {
        self.message.body.has(tag::ADV_ID)
    }




    /// Sets `AdvRefID`, Tag 3.
    pub fn set_adv_ref_id(&mut self, v: String) {
        self.message.body.set_field(tag::ADV_REF_ID, FIXString::from(v));
    }

    /// Gets `AdvRefID`, Tag 3.
    pub fn get_adv_ref_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::AdvRefIDField::new(String::new());
        self.message.body.get_field(tag::ADV_REF_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `AdvRefID` is present, Tag 3.
    pub fn has_adv_ref_id(&self) -> bool {
        self.message.body.has(tag::ADV_REF_ID)
    }




    /// Sets `AdvSide`, Tag 4.
    pub fn set_adv_side(&mut self, v: String) {
        self.message.body.set_field(tag::ADV_SIDE, FIXString::from(v));
    }

    /// Gets `AdvSide`, Tag 4.
    pub fn get_adv_side(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::AdvSideField::new(String::new());
        self.message.body.get_field(tag::ADV_SIDE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `AdvSide` is present, Tag 4.
    pub fn has_adv_side(&self) -> bool {
        self.message.body.has(tag::ADV_SIDE)
    }




    /// Sets `AdvTransType`, Tag 5.
    pub fn set_adv_trans_type(&mut self, v: String) {
        self.message.body.set_field(tag::ADV_TRANS_TYPE, FIXString::from(v));
    }

    /// Gets `AdvTransType`, Tag 5.
    pub fn get_adv_trans_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::AdvTransTypeField::new(String::new());
        self.message.body.get_field(tag::ADV_TRANS_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `AdvTransType` is present, Tag 5.
    pub fn has_adv_trans_type(&self) -> bool {
        self.message.body.has(tag::ADV_TRANS_TYPE)
    }




    /// Sets `ContractMultiplier`, Tag 231.
    pub fn set_contract_multiplier(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::CONTRACT_MULTIPLIER, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `ContractMultiplier`, Tag 231.
    pub fn get_contract_multiplier(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::ContractMultiplierField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::CONTRACT_MULTIPLIER, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `ContractMultiplier` is present, Tag 231.
    pub fn has_contract_multiplier(&self) -> bool {
        self.message.body.has(tag::CONTRACT_MULTIPLIER)
    }




    /// Sets `CouponRate`, Tag 223.
    pub fn set_coupon_rate(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::COUPON_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `CouponRate`, Tag 223.
    pub fn get_coupon_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::CouponRateField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::COUPON_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `CouponRate` is present, Tag 223.
    pub fn has_coupon_rate(&self) -> bool {
        self.message.body.has(tag::COUPON_RATE)
    }




    /// Sets `Currency`, Tag 15.
    pub fn set_currency(&mut self, v: String) {
        self.message.body.set_field(tag::CURRENCY, FIXString::from(v));
    }

    /// Gets `Currency`, Tag 15.
    pub fn get_currency(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CurrencyField::new(String::new());
        self.message.body.get_field(tag::CURRENCY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Currency` is present, Tag 15.
    pub fn has_currency(&self) -> bool {
        self.message.body.has(tag::CURRENCY)
    }




    /// Sets `EncodedIssuer`, Tag 349.
    pub fn set_encoded_issuer(&mut self, v: String) {
        self.message.body.set_field(tag::ENCODED_ISSUER, FIXString::from(v));
    }

    /// Gets `EncodedIssuer`, Tag 349.
    pub fn get_encoded_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedIssuerField::new(String::new());
        self.message.body.get_field(tag::ENCODED_ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedIssuer` is present, Tag 349.
    pub fn has_encoded_issuer(&self) -> bool {
        self.message.body.has(tag::ENCODED_ISSUER)
    }




    /// Sets `EncodedIssuerLen`, Tag 348.
    pub fn set_encoded_issuer_len(&mut self, v: isize) {
        self.message.body.set_field(tag::ENCODED_ISSUER_LEN, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `EncodedIssuerLen`, Tag 348.
    pub fn get_encoded_issuer_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedIssuerLenField::new(0);
        self.message.body.get_field(tag::ENCODED_ISSUER_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedIssuerLen` is present, Tag 348.
    pub fn has_encoded_issuer_len(&self) -> bool {
        self.message.body.has(tag::ENCODED_ISSUER_LEN)
    }




    /// Sets `EncodedSecurityDesc`, Tag 351.
    pub fn set_encoded_security_desc(&mut self, v: String) {
        self.message.body.set_field(tag::ENCODED_SECURITY_DESC, FIXString::from(v));
    }

    /// Gets `EncodedSecurityDesc`, Tag 351.
    pub fn get_encoded_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedSecurityDescField::new(String::new());
        self.message.body.get_field(tag::ENCODED_SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedSecurityDesc` is present, Tag 351.
    pub fn has_encoded_security_desc(&self) -> bool {
        self.message.body.has(tag::ENCODED_SECURITY_DESC)
    }




    /// Sets `EncodedSecurityDescLen`, Tag 350.
    pub fn set_encoded_security_desc_len(&mut self, v: isize) {
        self.message.body.set_field(tag::ENCODED_SECURITY_DESC_LEN, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `EncodedSecurityDescLen`, Tag 350.
    pub fn get_encoded_security_desc_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedSecurityDescLenField::new(0);
        self.message.body.get_field(tag::ENCODED_SECURITY_DESC_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedSecurityDescLen` is present, Tag 350.
    pub fn has_encoded_security_desc_len(&self) -> bool {
        self.message.body.has(tag::ENCODED_SECURITY_DESC_LEN)
    }




    /// Sets `EncodedText`, Tag 355.
    pub fn set_encoded_text(&mut self, v: String) {
        self.message.body.set_field(tag::ENCODED_TEXT, FIXString::from(v));
    }

    /// Gets `EncodedText`, Tag 355.
    pub fn get_encoded_text(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedTextField::new(String::new());
        self.message.body.get_field(tag::ENCODED_TEXT, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedText` is present, Tag 355.
    pub fn has_encoded_text(&self) -> bool {
        self.message.body.has(tag::ENCODED_TEXT)
    }




    /// Sets `EncodedTextLen`, Tag 354.
    pub fn set_encoded_text_len(&mut self, v: isize) {
        self.message.body.set_field(tag::ENCODED_TEXT_LEN, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `EncodedTextLen`, Tag 354.
    pub fn get_encoded_text_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedTextLenField::new(0);
        self.message.body.get_field(tag::ENCODED_TEXT_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedTextLen` is present, Tag 354.
    pub fn has_encoded_text_len(&self) -> bool {
        self.message.body.has(tag::ENCODED_TEXT_LEN)
    }




    /// Sets `IDSource`, Tag 22.
    pub fn set_id_source(&mut self, v: String) {
        self.message.body.set_field(tag::ID_SOURCE, FIXString::from(v));
    }

    /// Gets `IDSource`, Tag 22.
    pub fn get_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IDSourceField::new(String::new());
        self.message.body.get_field(tag::ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `IDSource` is present, Tag 22.
    pub fn has_id_source(&self) -> bool {
        self.message.body.has(tag::ID_SOURCE)
    }




    /// Sets `Issuer`, Tag 106.
    pub fn set_issuer(&mut self, v: String) {
        self.message.body.set_field(tag::ISSUER, FIXString::from(v));
    }

    /// Gets `Issuer`, Tag 106.
    pub fn get_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IssuerField::new(String::new());
        self.message.body.get_field(tag::ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Issuer` is present, Tag 106.
    pub fn has_issuer(&self) -> bool {
        self.message.body.has(tag::ISSUER)
    }




    /// Sets `LastMkt`, Tag 30.
    pub fn set_last_mkt(&mut self, v: String) {
        self.message.body.set_field(tag::LAST_MKT, FIXString::from(v));
    }

    /// Gets `LastMkt`, Tag 30.
    pub fn get_last_mkt(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::LastMktField::new(String::new());
        self.message.body.get_field(tag::LAST_MKT, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `LastMkt` is present, Tag 30.
    pub fn has_last_mkt(&self) -> bool {
        self.message.body.has(tag::LAST_MKT)
    }




    /// Sets `MaturityDay`, Tag 205.
    pub fn set_maturity_day(&mut self, v: isize) {
        self.message.body.set_field(tag::MATURITY_DAY, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `MaturityDay`, Tag 205.
    pub fn get_maturity_day(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::MaturityDayField::new(0);
        self.message.body.get_field(tag::MATURITY_DAY, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `MaturityDay` is present, Tag 205.
    pub fn has_maturity_day(&self) -> bool {
        self.message.body.has(tag::MATURITY_DAY)
    }




    /// Sets `MaturityMonthYear`, Tag 200.
    pub fn set_maturity_month_year(&mut self, v: String) {
        self.message.body.set_field(tag::MATURITY_MONTH_YEAR, FIXString::from(v));
    }

    /// Gets `MaturityMonthYear`, Tag 200.
    pub fn get_maturity_month_year(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MaturityMonthYearField::new(String::new());
        self.message.body.get_field(tag::MATURITY_MONTH_YEAR, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MaturityMonthYear` is present, Tag 200.
    pub fn has_maturity_month_year(&self) -> bool {
        self.message.body.has(tag::MATURITY_MONTH_YEAR)
    }




    /// Sets `OptAttribute`, Tag 206.
    pub fn set_opt_attribute(&mut self, v: String) {
        self.message.body.set_field(tag::OPT_ATTRIBUTE, FIXString::from(v));
    }

    /// Gets `OptAttribute`, Tag 206.
    pub fn get_opt_attribute(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::OptAttributeField::new(String::new());
        self.message.body.get_field(tag::OPT_ATTRIBUTE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `OptAttribute` is present, Tag 206.
    pub fn has_opt_attribute(&self) -> bool {
        self.message.body.has(tag::OPT_ATTRIBUTE)
    }




    /// Sets `Price`, Tag 44.
    pub fn set_price(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::PRICE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `Price`, Tag 44.
    pub fn get_price(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::PriceField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::PRICE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Price` is present, Tag 44.
    pub fn has_price(&self) -> bool {
        self.message.body.has(tag::PRICE)
    }




    /// Sets `PutOrCall`, Tag 201.
    pub fn set_put_or_call(&mut self, v: isize) {
        self.message.body.set_field(tag::PUT_OR_CALL, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `PutOrCall`, Tag 201.
    pub fn get_put_or_call(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::PutOrCallField::new(0);
        self.message.body.get_field(tag::PUT_OR_CALL, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `PutOrCall` is present, Tag 201.
    pub fn has_put_or_call(&self) -> bool {
        self.message.body.has(tag::PUT_OR_CALL)
    }




    /// Sets `SecurityDesc`, Tag 107.
    pub fn set_security_desc(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_DESC, FIXString::from(v));
    }

    /// Gets `SecurityDesc`, Tag 107.
    pub fn get_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityDescField::new(String::new());
        self.message.body.get_field(tag::SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityDesc` is present, Tag 107.
    pub fn has_security_desc(&self) -> bool {
        self.message.body.has(tag::SECURITY_DESC)
    }




    /// Sets `SecurityExchange`, Tag 207.
    pub fn set_security_exchange(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_EXCHANGE, FIXString::from(v));
    }

    /// Gets `SecurityExchange`, Tag 207.
    pub fn get_security_exchange(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityExchangeField::new(String::new());
        self.message.body.get_field(tag::SECURITY_EXCHANGE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityExchange` is present, Tag 207.
    pub fn has_security_exchange(&self) -> bool {
        self.message.body.has(tag::SECURITY_EXCHANGE)
    }




    /// Sets `SecurityID`, Tag 48.
    pub fn set_security_id(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_ID, FIXString::from(v));
    }

    /// Gets `SecurityID`, Tag 48.
    pub fn get_security_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityIDField::new(String::new());
        self.message.body.get_field(tag::SECURITY_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityID` is present, Tag 48.
    pub fn has_security_id(&self) -> bool {
        self.message.body.has(tag::SECURITY_ID)
    }




    /// Sets `SecurityType`, Tag 167.
    pub fn set_security_type(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_TYPE, FIXString::from(v));
    }

    /// Gets `SecurityType`, Tag 167.
    pub fn get_security_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityTypeField::new(String::new());
        self.message.body.get_field(tag::SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityType` is present, Tag 167.
    pub fn has_security_type(&self) -> bool {
        self.message.body.has(tag::SECURITY_TYPE)
    }




    /// Sets `Shares`, Tag 53.
    pub fn set_shares(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::SHARES, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `Shares`, Tag 53.
    pub fn get_shares(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::SharesField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::SHARES, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Shares` is present, Tag 53.
    pub fn has_shares(&self) -> bool {
        self.message.body.has(tag::SHARES)
    }




    /// Sets `StrikePrice`, Tag 202.
    pub fn set_strike_price(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::STRIKE_PRICE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `StrikePrice`, Tag 202.
    pub fn get_strike_price(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::StrikePriceField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::STRIKE_PRICE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `StrikePrice` is present, Tag 202.
    pub fn has_strike_price(&self) -> bool {
        self.message.body.has(tag::STRIKE_PRICE)
    }




    /// Sets `Symbol`, Tag 55.
    pub fn set_symbol(&mut self, v: String) {
        self.message.body.set_field(tag::SYMBOL, FIXString::from(v));
    }

    /// Gets `Symbol`, Tag 55.
    pub fn get_symbol(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolField::new(String::new());
        self.message.body.get_field(tag::SYMBOL, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Symbol` is present, Tag 55.
    pub fn has_symbol(&self) -> bool {
        self.message.body.has(tag::SYMBOL)
    }




    /// Sets `SymbolSfx`, Tag 65.
    pub fn set_symbol_sfx(&mut self, v: String) {
        self.message.body.set_field(tag::SYMBOL_SFX, FIXString::from(v));
    }

    /// Gets `SymbolSfx`, Tag 65.
    pub fn get_symbol_sfx(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolSfxField::new(String::new());
        self.message.body.get_field(tag::SYMBOL_SFX, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SymbolSfx` is present, Tag 65.
    pub fn has_symbol_sfx(&self) -> bool {
        self.message.body.has(tag::SYMBOL_SFX)
    }




    /// Sets `Text`, Tag 58.
    pub fn set_text(&mut self, v: String) {
        self.message.body.set_field(tag::TEXT, FIXString::from(v));
    }

    /// Gets `Text`, Tag 58.
    pub fn get_text(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TextField::new(String::new());
        self.message.body.get_field(tag::TEXT, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Text` is present, Tag 58.
    pub fn has_text(&self) -> bool {
        self.message.body.has(tag::TEXT)
    }




    /// Sets `TradeDate`, Tag 75.
    pub fn set_trade_date(&mut self, v: String) {
        self.message.body.set_field(tag::TRADE_DATE, FIXString::from(v));
    }

    /// Gets `TradeDate`, Tag 75.
    pub fn get_trade_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TradeDateField::new(String::new());
        self.message.body.get_field(tag::TRADE_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `TradeDate` is present, Tag 75.
    pub fn has_trade_date(&self) -> bool {
        self.message.body.has(tag::TRADE_DATE)
    }




    /// Sets `TradingSessionID`, Tag 336.
    pub fn set_trading_session_id(&mut self, v: String) {
        self.message.body.set_field(tag::TRADING_SESSION_ID, FIXString::from(v));
    }

    /// Gets `TradingSessionID`, Tag 336.
    pub fn get_trading_session_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TradingSessionIDField::new(String::new());
        self.message.body.get_field(tag::TRADING_SESSION_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `TradingSessionID` is present, Tag 336.
    pub fn has_trading_session_id(&self) -> bool {
        self.message.body.has(tag::TRADING_SESSION_ID)
    }




    /// Sets `TransactTime`, Tag 60.
    pub fn set_transact_time(&mut self, v: Timestamp) {
        self.message.body.set_field(tag::TRANSACT_TIME, fixer::fix_utc_timestamp::FIXUTCTimestamp {
            time: v,
            precision: fixer::fix_utc_timestamp::TimestampPrecision::Millis,
        });
    }

    /// Gets `TransactTime`, Tag 60.
    pub fn get_transact_time(&self) -> Result<Timestamp, MessageRejectErrorEnum> {
        let mut fld = field::TransactTimeField::new(Timestamp::UNIX_EPOCH);
        self.message.body.get_field(tag::TRANSACT_TIME, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `TransactTime` is present, Tag 60.
    pub fn has_transact_time(&self) -> bool {
        self.message.body.has(tag::TRANSACT_TIME)
    }




    /// Sets `URLLink`, Tag 149.
    pub fn set_url_link(&mut self, v: String) {
        self.message.body.set_field(tag::URL_LINK, FIXString::from(v));
    }

    /// Gets `URLLink`, Tag 149.
    pub fn get_url_link(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::URLLinkField::new(String::new());
        self.message.body.get_field(tag::URL_LINK, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `URLLink` is present, Tag 149.
    pub fn has_url_link(&self) -> bool {
        self.message.body.has(tag::URL_LINK)
    }


}

/// `RouteOut` is the callback type for routing `Advertisement` messages.
pub type RouteOut = fn(msg: Advertisement, session_id: SessionID) -> Result<(), MessageRejectErrorEnum>;

/// Route type returned by the `route` function.
pub type Route = (&'static str, &'static str, Box<dyn Fn(&Message, SessionID) -> Result<(), MessageRejectErrorEnum> + Send>);

/// Returns the begin string, message type, and route function for `Advertisement`.
pub fn route(router: RouteOut) -> Route {
    let r = move |msg: &Message, session_id: SessionID| -> Result<(), MessageRejectErrorEnum> {
        router(Advertisement::from_message(msg.clone()), session_id)
    };
    ("FIX.4.2", "7", Box::new(r))
}
