// Code generated by fixer-gen. DO NOT EDIT.
#![allow(clippy::new_without_default)]
#![allow(clippy::needless_pass_by_value)]
#![allow(clippy::too_many_arguments)]
#![allow(unused_imports)]

use fixer::message::Message;
use fixer::fix_string::FIXString;
use fixer::errors::MessageRejectErrorEnum;
use fixer::session::session_id::SessionID;


use jiff::Timestamp;

use crate::field;
use crate::tag;

/// `News` is the `fix42` `News` type, `MsgType` = B.
pub struct News {
    pub message: Message,
}

impl News {
    /// Creates a new `News` with required fields.
    pub fn new(headline: field::HeadlineField, lines_of_text: field::LinesOfTextField) -> Self {
        let mut msg = Message::new();
        msg.header.set_field(tag::MSG_TYPE, FIXString::from("B".to_string()));

        msg.body.set_field(tag::HEADLINE, headline.0);

        msg.body.set_field(tag::LINES_OF_TEXT, lines_of_text.0);

        Self { message: msg }
    }

    /// Creates a `News` from an existing `Message`.
    pub fn from_message(msg: Message) -> Self {
        Self { message: msg }
    }

    /// Returns the underlying `Message`.
    pub fn to_message(self) -> Message {
        self.message
    }




    /// Sets `EncodedHeadline`, Tag 359.
    pub fn set_encoded_headline(&mut self, v: String) {
        self.message.body.set_field(tag::ENCODED_HEADLINE, FIXString::from(v));
    }

    /// Gets `EncodedHeadline`, Tag 359.
    pub fn get_encoded_headline(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedHeadlineField::new(String::new());
        self.message.body.get_field(tag::ENCODED_HEADLINE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedHeadline` is present, Tag 359.
    pub fn has_encoded_headline(&self) -> bool {
        self.message.body.has(tag::ENCODED_HEADLINE)
    }




    /// Sets `EncodedHeadlineLen`, Tag 358.
    pub fn set_encoded_headline_len(&mut self, v: isize) {
        self.message.body.set_field(tag::ENCODED_HEADLINE_LEN, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `EncodedHeadlineLen`, Tag 358.
    pub fn get_encoded_headline_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedHeadlineLenField::new(0);
        self.message.body.get_field(tag::ENCODED_HEADLINE_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedHeadlineLen` is present, Tag 358.
    pub fn has_encoded_headline_len(&self) -> bool {
        self.message.body.has(tag::ENCODED_HEADLINE_LEN)
    }




    /// Sets `Headline`, Tag 148.
    pub fn set_headline(&mut self, v: String) {
        self.message.body.set_field(tag::HEADLINE, FIXString::from(v));
    }

    /// Gets `Headline`, Tag 148.
    pub fn get_headline(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::HeadlineField::new(String::new());
        self.message.body.get_field(tag::HEADLINE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Headline` is present, Tag 148.
    pub fn has_headline(&self) -> bool {
        self.message.body.has(tag::HEADLINE)
    }




    /// Sets `LinesOfText`, Tag 33.
    pub fn set_lines_of_text(&mut self, v: isize) {
        self.message.body.set_field(tag::LINES_OF_TEXT, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `LinesOfText`, Tag 33.
    pub fn get_lines_of_text(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::LinesOfTextField::new(0);
        self.message.body.get_field(tag::LINES_OF_TEXT, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `LinesOfText` is present, Tag 33.
    pub fn has_lines_of_text(&self) -> bool {
        self.message.body.has(tag::LINES_OF_TEXT)
    }




    /// Sets `NoRelatedSym`, Tag 146.
    pub fn set_no_related_sym(&mut self, v: isize) {
        self.message.body.set_field(tag::NO_RELATED_SYM, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `NoRelatedSym`, Tag 146.
    pub fn get_no_related_sym(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::NoRelatedSymField::new(0);
        self.message.body.get_field(tag::NO_RELATED_SYM, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `NoRelatedSym` is present, Tag 146.
    pub fn has_no_related_sym(&self) -> bool {
        self.message.body.has(tag::NO_RELATED_SYM)
    }




    /// Sets `NoRoutingIDs`, Tag 215.
    pub fn set_no_routing_i_ds(&mut self, v: isize) {
        self.message.body.set_field(tag::NO_ROUTING_I_DS, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `NoRoutingIDs`, Tag 215.
    pub fn get_no_routing_i_ds(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::NoRoutingIDsField::new(0);
        self.message.body.get_field(tag::NO_ROUTING_I_DS, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `NoRoutingIDs` is present, Tag 215.
    pub fn has_no_routing_i_ds(&self) -> bool {
        self.message.body.has(tag::NO_ROUTING_I_DS)
    }




    /// Sets `OrigTime`, Tag 42.
    pub fn set_orig_time(&mut self, v: Timestamp) {
        self.message.body.set_field(tag::ORIG_TIME, fixer::fix_utc_timestamp::FIXUTCTimestamp {
            time: v,
            precision: fixer::fix_utc_timestamp::TimestampPrecision::Millis,
        });
    }

    /// Gets `OrigTime`, Tag 42.
    pub fn get_orig_time(&self) -> Result<Timestamp, MessageRejectErrorEnum> {
        let mut fld = field::OrigTimeField::new(Timestamp::UNIX_EPOCH);
        self.message.body.get_field(tag::ORIG_TIME, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `OrigTime` is present, Tag 42.
    pub fn has_orig_time(&self) -> bool {
        self.message.body.has(tag::ORIG_TIME)
    }




    /// Sets `RawData`, Tag 96.
    pub fn set_raw_data(&mut self, v: String) {
        self.message.body.set_field(tag::RAW_DATA, FIXString::from(v));
    }

    /// Gets `RawData`, Tag 96.
    pub fn get_raw_data(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::RawDataField::new(String::new());
        self.message.body.get_field(tag::RAW_DATA, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `RawData` is present, Tag 96.
    pub fn has_raw_data(&self) -> bool {
        self.message.body.has(tag::RAW_DATA)
    }




    /// Sets `RawDataLength`, Tag 95.
    pub fn set_raw_data_length(&mut self, v: isize) {
        self.message.body.set_field(tag::RAW_DATA_LENGTH, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `RawDataLength`, Tag 95.
    pub fn get_raw_data_length(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::RawDataLengthField::new(0);
        self.message.body.get_field(tag::RAW_DATA_LENGTH, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RawDataLength` is present, Tag 95.
    pub fn has_raw_data_length(&self) -> bool {
        self.message.body.has(tag::RAW_DATA_LENGTH)
    }




    /// Sets `URLLink`, Tag 149.
    pub fn set_url_link(&mut self, v: String) {
        self.message.body.set_field(tag::URL_LINK, FIXString::from(v));
    }

    /// Gets `URLLink`, Tag 149.
    pub fn get_url_link(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::URLLinkField::new(String::new());
        self.message.body.get_field(tag::URL_LINK, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `URLLink` is present, Tag 149.
    pub fn has_url_link(&self) -> bool {
        self.message.body.has(tag::URL_LINK)
    }




    /// Sets `Urgency`, Tag 61.
    pub fn set_urgency(&mut self, v: String) {
        self.message.body.set_field(tag::URGENCY, FIXString::from(v));
    }

    /// Gets `Urgency`, Tag 61.
    pub fn get_urgency(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UrgencyField::new(String::new());
        self.message.body.get_field(tag::URGENCY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Urgency` is present, Tag 61.
    pub fn has_urgency(&self) -> bool {
        self.message.body.has(tag::URGENCY)
    }


}

/// `RouteOut` is the callback type for routing `News` messages.
pub type RouteOut = fn(msg: News, session_id: SessionID) -> Result<(), MessageRejectErrorEnum>;

/// Route type returned by the `route` function.
pub type Route = (&'static str, &'static str, Box<dyn Fn(&Message, SessionID) -> Result<(), MessageRejectErrorEnum> + Send>);

/// Returns the begin string, message type, and route function for `News`.
pub fn route(router: RouteOut) -> Route {
    let r = move |msg: &Message, session_id: SessionID| -> Result<(), MessageRejectErrorEnum> {
        router(News::from_message(msg.clone()), session_id)
    };
    ("FIX.4.2", "B", Box::new(r))
}
