// Code generated by fixer-gen. DO NOT EDIT.
#![allow(clippy::new_without_default)]
#![allow(clippy::needless_pass_by_value)]
#![allow(clippy::too_many_arguments)]
#![allow(unused_imports)]

use fixer::message::Message;
use fixer::fix_string::FIXString;
use fixer::errors::MessageRejectErrorEnum;
use fixer::session::session_id::SessionID;
use fixer::repeating_group::{Group, GroupTemplate, RepeatingGroup, group_element};
use std::borrow::{Borrow, BorrowMut};

use rust_decimal::Decimal;


use crate::field;
use crate::tag;

/// `QuoteCancel` is the `fix42` `QuoteCancel` type, `MsgType` = Z.
pub struct QuoteCancel {
    pub message: Message,
}

impl QuoteCancel {
    /// Creates a new `QuoteCancel` with required fields.
    pub fn new(quote_id: field::QuoteIDField, quote_cancel_type: field::QuoteCancelTypeField) -> Self {
        let mut msg = Message::new();
        msg.header.set_field(tag::MSG_TYPE, FIXString::from("Z".to_string()));

        msg.body.set_field(tag::QUOTE_ID, quote_id.0);

        msg.body.set_field(tag::QUOTE_CANCEL_TYPE, quote_cancel_type.0);

        Self { message: msg }
    }

    /// Creates a `QuoteCancel` from an existing `Message`.
    pub fn from_message(msg: Message) -> Self {
        Self { message: msg }
    }

    /// Returns the underlying `Message`.
    pub fn to_message(self) -> Message {
        self.message
    }




    /// Sets `NoQuoteEntries`, Tag 295.
    pub fn set_no_quote_entries(&mut self, f: NoQuoteEntriesRepeatingGroup) {
        self.message.body.set_group(f.0);
    }

    /// Gets `NoQuoteEntries`, Tag 295.
    pub fn get_no_quote_entries(&self) -> Result<NoQuoteEntriesRepeatingGroup, MessageRejectErrorEnum> {
        let g = NoQuoteEntriesRepeatingGroup::new();
        Ok(NoQuoteEntriesRepeatingGroup(self.message.body.get_group(g.0)?))
    }


    /// Returns true if `NoQuoteEntries` is present, Tag 295.
    pub fn has_no_quote_entries(&self) -> bool {
        self.message.body.has(tag::NO_QUOTE_ENTRIES)
    }




    /// Sets `QuoteCancelType`, Tag 298.
    pub fn set_quote_cancel_type(&mut self, v: isize) {
        self.message.body.set_field(tag::QUOTE_CANCEL_TYPE, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `QuoteCancelType`, Tag 298.
    pub fn get_quote_cancel_type(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::QuoteCancelTypeField::new(0);
        self.message.body.get_field(tag::QUOTE_CANCEL_TYPE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `QuoteCancelType` is present, Tag 298.
    pub fn has_quote_cancel_type(&self) -> bool {
        self.message.body.has(tag::QUOTE_CANCEL_TYPE)
    }




    /// Sets `QuoteID`, Tag 117.
    pub fn set_quote_id(&mut self, v: String) {
        self.message.body.set_field(tag::QUOTE_ID, FIXString::from(v));
    }

    /// Gets `QuoteID`, Tag 117.
    pub fn get_quote_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::QuoteIDField::new(String::new());
        self.message.body.get_field(tag::QUOTE_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `QuoteID` is present, Tag 117.
    pub fn has_quote_id(&self) -> bool {
        self.message.body.has(tag::QUOTE_ID)
    }




    /// Sets `QuoteReqID`, Tag 131.
    pub fn set_quote_req_id(&mut self, v: String) {
        self.message.body.set_field(tag::QUOTE_REQ_ID, FIXString::from(v));
    }

    /// Gets `QuoteReqID`, Tag 131.
    pub fn get_quote_req_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::QuoteReqIDField::new(String::new());
        self.message.body.get_field(tag::QUOTE_REQ_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `QuoteReqID` is present, Tag 131.
    pub fn has_quote_req_id(&self) -> bool {
        self.message.body.has(tag::QUOTE_REQ_ID)
    }




    /// Sets `QuoteResponseLevel`, Tag 301.
    pub fn set_quote_response_level(&mut self, v: isize) {
        self.message.body.set_field(tag::QUOTE_RESPONSE_LEVEL, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `QuoteResponseLevel`, Tag 301.
    pub fn get_quote_response_level(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::QuoteResponseLevelField::new(0);
        self.message.body.get_field(tag::QUOTE_RESPONSE_LEVEL, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `QuoteResponseLevel` is present, Tag 301.
    pub fn has_quote_response_level(&self) -> bool {
        self.message.body.has(tag::QUOTE_RESPONSE_LEVEL)
    }




    /// Sets `TradingSessionID`, Tag 336.
    pub fn set_trading_session_id(&mut self, v: String) {
        self.message.body.set_field(tag::TRADING_SESSION_ID, FIXString::from(v));
    }

    /// Gets `TradingSessionID`, Tag 336.
    pub fn get_trading_session_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TradingSessionIDField::new(String::new());
        self.message.body.get_field(tag::TRADING_SESSION_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `TradingSessionID` is present, Tag 336.
    pub fn has_trading_session_id(&self) -> bool {
        self.message.body.has(tag::TRADING_SESSION_ID)
    }


}

/// `RouteOut` is the callback type for routing `QuoteCancel` messages.
pub type RouteOut = fn(msg: QuoteCancel, session_id: SessionID) -> Result<(), MessageRejectErrorEnum>;

/// Route type returned by the `route` function.
pub type Route = (&'static str, &'static str, Box<dyn Fn(&Message, SessionID) -> Result<(), MessageRejectErrorEnum> + Send>);

/// Returns the begin string, message type, and route function for `QuoteCancel`.
pub fn route(router: RouteOut) -> Route {
    let r = move |msg: &Message, session_id: SessionID| -> Result<(), MessageRejectErrorEnum> {
        router(QuoteCancel::from_message(msg.clone()), session_id)
    };
    ("FIX.4.2", "Z", Box::new(r))
}


/// `NoQuoteEntries` is an entry in the `NoQuoteEntries` repeating group, Tag 295.
pub struct NoQuoteEntries<G>(pub G);

impl<G: Borrow<Group>> NoQuoteEntries<G> {
    fn group(&self) -> &Group {
        self.0.borrow()
    }



    /// Gets `Symbol`, Tag 55.
    pub fn get_symbol(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolField::new(String::new());
        self.group().field_map.get_field(tag::SYMBOL, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Symbol` is present, Tag 55.
    pub fn has_symbol(&self) -> bool {
        self.group().field_map.has(tag::SYMBOL)
    }




    /// Gets `SymbolSfx`, Tag 65.
    pub fn get_symbol_sfx(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolSfxField::new(String::new());
        self.group().field_map.get_field(tag::SYMBOL_SFX, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SymbolSfx` is present, Tag 65.
    pub fn has_symbol_sfx(&self) -> bool {
        self.group().field_map.has(tag::SYMBOL_SFX)
    }




    /// Gets `SecurityID`, Tag 48.
    pub fn get_security_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityIDField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityID` is present, Tag 48.
    pub fn has_security_id(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_ID)
    }




    /// Gets `IDSource`, Tag 22.
    pub fn get_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IDSourceField::new(String::new());
        self.group().field_map.get_field(tag::ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `IDSource` is present, Tag 22.
    pub fn has_id_source(&self) -> bool {
        self.group().field_map.has(tag::ID_SOURCE)
    }




    /// Gets `SecurityType`, Tag 167.
    pub fn get_security_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityTypeField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityType` is present, Tag 167.
    pub fn has_security_type(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_TYPE)
    }




    /// Gets `MaturityMonthYear`, Tag 200.
    pub fn get_maturity_month_year(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MaturityMonthYearField::new(String::new());
        self.group().field_map.get_field(tag::MATURITY_MONTH_YEAR, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MaturityMonthYear` is present, Tag 200.
    pub fn has_maturity_month_year(&self) -> bool {
        self.group().field_map.has(tag::MATURITY_MONTH_YEAR)
    }




    /// Gets `MaturityDay`, Tag 205.
    pub fn get_maturity_day(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::MaturityDayField::new(0);
        self.group().field_map.get_field(tag::MATURITY_DAY, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `MaturityDay` is present, Tag 205.
    pub fn has_maturity_day(&self) -> bool {
        self.group().field_map.has(tag::MATURITY_DAY)
    }




    /// Gets `PutOrCall`, Tag 201.
    pub fn get_put_or_call(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::PutOrCallField::new(0);
        self.group().field_map.get_field(tag::PUT_OR_CALL, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `PutOrCall` is present, Tag 201.
    pub fn has_put_or_call(&self) -> bool {
        self.group().field_map.has(tag::PUT_OR_CALL)
    }




    /// Gets `StrikePrice`, Tag 202.
    pub fn get_strike_price(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::StrikePriceField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::STRIKE_PRICE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `StrikePrice` is present, Tag 202.
    pub fn has_strike_price(&self) -> bool {
        self.group().field_map.has(tag::STRIKE_PRICE)
    }




    /// Gets `OptAttribute`, Tag 206.
    pub fn get_opt_attribute(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::OptAttributeField::new(String::new());
        self.group().field_map.get_field(tag::OPT_ATTRIBUTE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `OptAttribute` is present, Tag 206.
    pub fn has_opt_attribute(&self) -> bool {
        self.group().field_map.has(tag::OPT_ATTRIBUTE)
    }




    /// Gets `ContractMultiplier`, Tag 231.
    pub fn get_contract_multiplier(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::ContractMultiplierField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::CONTRACT_MULTIPLIER, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `ContractMultiplier` is present, Tag 231.
    pub fn has_contract_multiplier(&self) -> bool {
        self.group().field_map.has(tag::CONTRACT_MULTIPLIER)
    }




    /// Gets `CouponRate`, Tag 223.
    pub fn get_coupon_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::CouponRateField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::COUPON_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `CouponRate` is present, Tag 223.
    pub fn has_coupon_rate(&self) -> bool {
        self.group().field_map.has(tag::COUPON_RATE)
    }




    /// Gets `SecurityExchange`, Tag 207.
    pub fn get_security_exchange(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityExchangeField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_EXCHANGE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityExchange` is present, Tag 207.
    pub fn has_security_exchange(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_EXCHANGE)
    }




    /// Gets `Issuer`, Tag 106.
    pub fn get_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IssuerField::new(String::new());
        self.group().field_map.get_field(tag::ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Issuer` is present, Tag 106.
    pub fn has_issuer(&self) -> bool {
        self.group().field_map.has(tag::ISSUER)
    }




    /// Gets `EncodedIssuerLen`, Tag 348.
    pub fn get_encoded_issuer_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedIssuerLenField::new(0);
        self.group().field_map.get_field(tag::ENCODED_ISSUER_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedIssuerLen` is present, Tag 348.
    pub fn has_encoded_issuer_len(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_ISSUER_LEN)
    }




    /// Gets `EncodedIssuer`, Tag 349.
    pub fn get_encoded_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedIssuerField::new(String::new());
        self.group().field_map.get_field(tag::ENCODED_ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedIssuer` is present, Tag 349.
    pub fn has_encoded_issuer(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_ISSUER)
    }




    /// Gets `SecurityDesc`, Tag 107.
    pub fn get_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityDescField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityDesc` is present, Tag 107.
    pub fn has_security_desc(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_DESC)
    }




    /// Gets `EncodedSecurityDescLen`, Tag 350.
    pub fn get_encoded_security_desc_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedSecurityDescLenField::new(0);
        self.group().field_map.get_field(tag::ENCODED_SECURITY_DESC_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedSecurityDescLen` is present, Tag 350.
    pub fn has_encoded_security_desc_len(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_SECURITY_DESC_LEN)
    }




    /// Gets `EncodedSecurityDesc`, Tag 351.
    pub fn get_encoded_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedSecurityDescField::new(String::new());
        self.group().field_map.get_field(tag::ENCODED_SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedSecurityDesc` is present, Tag 351.
    pub fn has_encoded_security_desc(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_SECURITY_DESC)
    }




    /// Gets `UnderlyingSymbol`, Tag 311.
    pub fn get_underlying_symbol(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSymbolField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_SYMBOL, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSymbol` is present, Tag 311.
    pub fn has_underlying_symbol(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_SYMBOL)
    }


}

impl<G: BorrowMut<Group>> NoQuoteEntries<G> {
    fn group_mut(&mut self) -> &mut Group {
        self.0.borrow_mut()
    }



    /// Sets `Symbol`, Tag 55.
    pub fn set_symbol(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SYMBOL, FIXString::from(v));
    }





    /// Sets `SymbolSfx`, Tag 65.
    pub fn set_symbol_sfx(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SYMBOL_SFX, FIXString::from(v));
    }





    /// Sets `SecurityID`, Tag 48.
    pub fn set_security_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_ID, FIXString::from(v));
    }





    /// Sets `IDSource`, Tag 22.
    pub fn set_id_source(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ID_SOURCE, FIXString::from(v));
    }





    /// Sets `SecurityType`, Tag 167.
    pub fn set_security_type(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_TYPE, FIXString::from(v));
    }





    /// Sets `MaturityMonthYear`, Tag 200.
    pub fn set_maturity_month_year(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::MATURITY_MONTH_YEAR, FIXString::from(v));
    }





    /// Sets `MaturityDay`, Tag 205.
    pub fn set_maturity_day(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::MATURITY_DAY, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `PutOrCall`, Tag 201.
    pub fn set_put_or_call(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::PUT_OR_CALL, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `StrikePrice`, Tag 202.
    pub fn set_strike_price(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::STRIKE_PRICE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `OptAttribute`, Tag 206.
    pub fn set_opt_attribute(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::OPT_ATTRIBUTE, FIXString::from(v));
    }





    /// Sets `ContractMultiplier`, Tag 231.
    pub fn set_contract_multiplier(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::CONTRACT_MULTIPLIER, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `CouponRate`, Tag 223.
    pub fn set_coupon_rate(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::COUPON_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `SecurityExchange`, Tag 207.
    pub fn set_security_exchange(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_EXCHANGE, FIXString::from(v));
    }





    /// Sets `Issuer`, Tag 106.
    pub fn set_issuer(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ISSUER, FIXString::from(v));
    }





    /// Sets `EncodedIssuerLen`, Tag 348.
    pub fn set_encoded_issuer_len(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::ENCODED_ISSUER_LEN, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `EncodedIssuer`, Tag 349.
    pub fn set_encoded_issuer(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ENCODED_ISSUER, FIXString::from(v));
    }





    /// Sets `SecurityDesc`, Tag 107.
    pub fn set_security_desc(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_DESC, FIXString::from(v));
    }





    /// Sets `EncodedSecurityDescLen`, Tag 350.
    pub fn set_encoded_security_desc_len(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::ENCODED_SECURITY_DESC_LEN, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `EncodedSecurityDesc`, Tag 351.
    pub fn set_encoded_security_desc(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ENCODED_SECURITY_DESC, FIXString::from(v));
    }





    /// Sets `UnderlyingSymbol`, Tag 311.
    pub fn set_underlying_symbol(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_SYMBOL, FIXString::from(v));
    }



}

/// `NoQuoteEntriesRepeatingGroup` is the `NoQuoteEntries` repeating group, Tag 295.
pub struct NoQuoteEntriesRepeatingGroup(pub RepeatingGroup);

impl NoQuoteEntriesRepeatingGroup {
    /// Creates an empty `NoQuoteEntries` group with the template from the FIX spec.
    pub fn new() -> Self {
        let template: GroupTemplate = vec![


            group_element(tag::SYMBOL),



            group_element(tag::SYMBOL_SFX),



            group_element(tag::SECURITY_ID),



            group_element(tag::ID_SOURCE),



            group_element(tag::SECURITY_TYPE),



            group_element(tag::MATURITY_MONTH_YEAR),



            group_element(tag::MATURITY_DAY),



            group_element(tag::PUT_OR_CALL),



            group_element(tag::STRIKE_PRICE),



            group_element(tag::OPT_ATTRIBUTE),



            group_element(tag::CONTRACT_MULTIPLIER),



            group_element(tag::COUPON_RATE),



            group_element(tag::SECURITY_EXCHANGE),



            group_element(tag::ISSUER),



            group_element(tag::ENCODED_ISSUER_LEN),



            group_element(tag::ENCODED_ISSUER),



            group_element(tag::SECURITY_DESC),



            group_element(tag::ENCODED_SECURITY_DESC_LEN),



            group_element(tag::ENCODED_SECURITY_DESC),



            group_element(tag::UNDERLYING_SYMBOL),


        ];
        Self(RepeatingGroup::new(tag::NO_QUOTE_ENTRIES, template))
    }

    /// Appends an entry and returns it for population.
    pub fn add(&mut self) -> NoQuoteEntries<&mut Group> {
        NoQuoteEntries(self.0.add())
    }

    /// Returns the `i`th entry.
    pub fn get(&self, i: usize) -> NoQuoteEntries<&Group> {
        NoQuoteEntries(self.0.get(i))
    }

    /// Returns the number of entries.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns true if the group has no entries.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl Default for NoQuoteEntriesRepeatingGroup {
    fn default() -> Self {
        Self::new()
    }
}

