// Code generated by fixer-gen. DO NOT EDIT.
#![allow(clippy::new_without_default)]
#![allow(clippy::needless_pass_by_value)]
#![allow(clippy::too_many_arguments)]
#![allow(unused_imports)]

use fixer::message::Message;
use fixer::fix_string::FIXString;
use fixer::errors::MessageRejectErrorEnum;
use fixer::session::session_id::SessionID;

use rust_decimal::Decimal;


use jiff::Timestamp;

use crate::field;
use crate::tag;

/// `Advertisement` is the `fix40` `Advertisement` type, `MsgType` = 7.
pub struct Advertisement {
    pub message: Message,
}

impl Advertisement {
    /// Creates a new `Advertisement` with required fields.
    pub fn new(adv_id: field::AdvIdField, adv_trans_type: field::AdvTransTypeField, symbol: field::SymbolField, adv_side: field::AdvSideField, shares: field::SharesField) -> Self {
        let mut msg = Message::new();
        msg.header.set_field(tag::MSG_TYPE, FIXString::from("7".to_string()));

        msg.body.set_field(tag::ADV_ID, adv_id.0);

        msg.body.set_field(tag::ADV_TRANS_TYPE, adv_trans_type.0);

        msg.body.set_field(tag::SYMBOL, symbol.0);

        msg.body.set_field(tag::ADV_SIDE, adv_side.0);

        msg.body.set_field(tag::SHARES, shares.0);

        Self { message: msg }
    }

    /// Creates a `Advertisement` from an existing `Message`.
    pub fn from_message(msg: Message) -> Self {
        Self { message: msg }
    }

    /// Returns the underlying `Message`.
    pub fn to_message(self) -> Message {
        self.message
    }




    /// Sets `AdvId`, Tag 2.
    pub fn set_adv_id(&mut self, v: String) {
        self.message.body.set_field(tag::ADV_ID, FIXString::from(v));
    }

    /// Gets `AdvId`, Tag 2.
    pub fn get_adv_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::AdvIdField::new(String::new());
        self.message.body.get_field(tag::ADV_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `AdvId` is present, Tag 2.
    pub fn has_adv_id(&self) -> bool {
        self.message.body.has(tag::ADV_ID)
    }




    /// Sets `AdvRefID`, Tag 3.
    pub fn set_adv_ref_id(&mut self, v: String) {
        self.message.body.set_field(tag::ADV_REF_ID, FIXString::from(v));
    }

    /// Gets `AdvRefID`, Tag 3.
    pub fn get_adv_ref_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::AdvRefIDField::new(String::new());
        self.message.body.get_field(tag::ADV_REF_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `AdvRefID` is present, Tag 3.
    pub fn has_adv_ref_id(&self) -> bool {
        self.message.body.has(tag::ADV_REF_ID)
    }




    /// Sets `AdvSide`, Tag 4.
    pub fn set_adv_side(&mut self, v: String) {
        self.message.body.set_field(tag::ADV_SIDE, FIXString::from(v));
    }

    /// Gets `AdvSide`, Tag 4.
    pub fn get_adv_side(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::AdvSideField::new(String::new());
        self.message.body.get_field(tag::ADV_SIDE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `AdvSide` is present, Tag 4.
    pub fn has_adv_side(&self) -> bool {
        self.message.body.has(tag::ADV_SIDE)
    }




    /// Sets `AdvTransType`, Tag 5.
    pub fn set_adv_trans_type(&mut self, v: String) {
        self.message.body.set_field(tag::ADV_TRANS_TYPE, FIXString::from(v));
    }

    /// Gets `AdvTransType`, Tag 5.
    pub fn get_adv_trans_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::AdvTransTypeField::new(String::new());
        self.message.body.get_field(tag::ADV_TRANS_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `AdvTransType` is present, Tag 5.
    pub fn has_adv_trans_type(&self) -> bool {
        self.message.body.has(tag::ADV_TRANS_TYPE)
    }




    /// Sets `Currency`, Tag 15.
    pub fn set_currency(&mut self, v: String) {
        self.message.body.set_field(tag::CURRENCY, FIXString::from(v));
    }

    /// Gets `Currency`, Tag 15.
    pub fn get_currency(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CurrencyField::new(String::new());
        self.message.body.get_field(tag::CURRENCY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Currency` is present, Tag 15.
    pub fn has_currency(&self) -> bool {
        self.message.body.has(tag::CURRENCY)
    }




    /// Sets `IDSource`, Tag 22.
    pub fn set_id_source(&mut self, v: String) {
        self.message.body.set_field(tag::ID_SOURCE, FIXString::from(v));
    }

    /// Gets `IDSource`, Tag 22.
    pub fn get_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IDSourceField::new(String::new());
        self.message.body.get_field(tag::ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `IDSource` is present, Tag 22.
    pub fn has_id_source(&self) -> bool {
        self.message.body.has(tag::ID_SOURCE)
    }




    /// Sets `Issuer`, Tag 106.
    pub fn set_issuer(&mut self, v: String) {
        self.message.body.set_field(tag::ISSUER, FIXString::from(v));
    }

    /// Gets `Issuer`, Tag 106.
    pub fn get_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IssuerField::new(String::new());
        self.message.body.get_field(tag::ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Issuer` is present, Tag 106.
    pub fn has_issuer(&self) -> bool {
        self.message.body.has(tag::ISSUER)
    }




    /// Sets `Price`, Tag 44.
    pub fn set_price(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::PRICE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `Price`, Tag 44.
    pub fn get_price(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::PriceField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::PRICE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Price` is present, Tag 44.
    pub fn has_price(&self) -> bool {
        self.message.body.has(tag::PRICE)
    }




    /// Sets `SecurityDesc`, Tag 107.
    pub fn set_security_desc(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_DESC, FIXString::from(v));
    }

    /// Gets `SecurityDesc`, Tag 107.
    pub fn get_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityDescField::new(String::new());
        self.message.body.get_field(tag::SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityDesc` is present, Tag 107.
    pub fn has_security_desc(&self) -> bool {
        self.message.body.has(tag::SECURITY_DESC)
    }




    /// Sets `SecurityID`, Tag 48.
    pub fn set_security_id(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_ID, FIXString::from(v));
    }

    /// Gets `SecurityID`, Tag 48.
    pub fn get_security_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityIDField::new(String::new());
        self.message.body.get_field(tag::SECURITY_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityID` is present, Tag 48.
    pub fn has_security_id(&self) -> bool {
        self.message.body.has(tag::SECURITY_ID)
    }




    /// Sets `Shares`, Tag 53.
    pub fn set_shares(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::SHARES, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `Shares`, Tag 53.
    pub fn get_shares(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::SharesField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::SHARES, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Shares` is present, Tag 53.
    pub fn has_shares(&self) -> bool {
        self.message.body.has(tag::SHARES)
    }




    /// Sets `Symbol`, Tag 55.
    pub fn set_symbol(&mut self, v: String) {
        self.message.body.set_field(tag::SYMBOL, FIXString::from(v));
    }

    /// Gets `Symbol`, Tag 55.
    pub fn get_symbol(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolField::new(String::new());
        self.message.body.get_field(tag::SYMBOL, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Symbol` is present, Tag 55.
    pub fn has_symbol(&self) -> bool {
        self.message.body.has(tag::SYMBOL)
    }




    /// Sets `SymbolSfx`, Tag 65.
    pub fn set_symbol_sfx(&mut self, v: String) {
        self.message.body.set_field(tag::SYMBOL_SFX, FIXString::from(v));
    }

    /// Gets `SymbolSfx`, Tag 65.
    pub fn get_symbol_sfx(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolSfxField::new(String::new());
        self.message.body.get_field(tag::SYMBOL_SFX, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SymbolSfx` is present, Tag 65.
    pub fn has_symbol_sfx(&self) -> bool {
        self.message.body.has(tag::SYMBOL_SFX)
    }




    /// Sets `Text`, Tag 58.
    pub fn set_text(&mut self, v: String) {
        self.message.body.set_field(tag::TEXT, FIXString::from(v));
    }

    /// Gets `Text`, Tag 58.
    pub fn get_text(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TextField::new(String::new());
        self.message.body.get_field(tag::TEXT, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Text` is present, Tag 58.
    pub fn has_text(&self) -> bool {
        self.message.body.has(tag::TEXT)
    }




    /// Sets `TransactTime`, Tag 60.
    pub fn set_transact_time(&mut self, v: Timestamp) {
        self.message.body.set_field(tag::TRANSACT_TIME, fixer::fix_utc_timestamp::FIXUTCTimestamp {
            time: v,
            precision: fixer::fix_utc_timestamp::TimestampPrecision::Millis,
        });
    }

    /// Gets `TransactTime`, Tag 60.
    pub fn get_transact_time(&self) -> Result<Timestamp, MessageRejectErrorEnum> {
        let mut fld = field::TransactTimeField::new(Timestamp::UNIX_EPOCH);
        self.message.body.get_field(tag::TRANSACT_TIME, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `TransactTime` is present, Tag 60.
    pub fn has_transact_time(&self) -> bool {
        self.message.body.has(tag::TRANSACT_TIME)
    }


}

/// `RouteOut` is the callback type for routing `Advertisement` messages.
pub type RouteOut = fn(msg: Advertisement, session_id: SessionID) -> Result<(), MessageRejectErrorEnum>;

/// Route type returned by the `route` function.
pub type Route = (&'static str, &'static str, Box<dyn Fn(&Message, SessionID) -> Result<(), MessageRejectErrorEnum> + Send>);

/// Returns the begin string, message type, and route function for `Advertisement`.
pub fn route(router: RouteOut) -> Route {
    let r = move |msg: &Message, session_id: SessionID| -> Result<(), MessageRejectErrorEnum> {
        router(Advertisement::from_message(msg.clone()), session_id)
    };
    ("FIX.4.0", "7", Box::new(r))
}
