// Code generated by fixer-gen. DO NOT EDIT.
#![allow(clippy::new_without_default)]
#![allow(clippy::needless_pass_by_value)]
#![allow(clippy::too_many_arguments)]
#![allow(unused_imports)]

use fixer::message::Message;
use fixer::fix_string::FIXString;
use fixer::errors::MessageRejectErrorEnum;
use fixer::session::session_id::SessionID;

use rust_decimal::Decimal;


use jiff::Timestamp;

use crate::field;
use crate::tag;

/// `NewOrderCross` is the `fix43` `NewOrderCross` type, `MsgType` = s.
pub struct NewOrderCross {
    pub message: Message,
}

impl NewOrderCross {
    /// Creates a new `NewOrderCross` with required fields.
    pub fn new(cross_id: field::CrossIDField, cross_type: field::CrossTypeField, cross_prioritization: field::CrossPrioritizationField, no_sides: field::NoSidesField, handl_inst: field::HandlInstField, transact_time: field::TransactTimeField, ord_type: field::OrdTypeField) -> Self {
        let mut msg = Message::new();
        msg.header.set_field(tag::MSG_TYPE, FIXString::from("s".to_string()));

        msg.body.set_field(tag::CROSS_ID, cross_id.0);

        msg.body.set_field(tag::CROSS_TYPE, cross_type.0);

        msg.body.set_field(tag::CROSS_PRIORITIZATION, cross_prioritization.0);

        msg.body.set_field(tag::NO_SIDES, no_sides.0);

        msg.body.set_field(tag::HANDL_INST, handl_inst.0);

        msg.body.set_field(tag::TRANSACT_TIME, transact_time.0);

        msg.body.set_field(tag::ORD_TYPE, ord_type.0);

        Self { message: msg }
    }

    /// Creates a `NewOrderCross` from an existing `Message`.
    pub fn from_message(msg: Message) -> Self {
        Self { message: msg }
    }

    /// Returns the underlying `Message`.
    pub fn to_message(self) -> Message {
        self.message
    }




    /// Sets `AccruedInterestAmt`, Tag 159.
    pub fn set_accrued_interest_amt(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::ACCRUED_INTEREST_AMT, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `AccruedInterestAmt`, Tag 159.
    pub fn get_accrued_interest_amt(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::AccruedInterestAmtField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::ACCRUED_INTEREST_AMT, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `AccruedInterestAmt` is present, Tag 159.
    pub fn has_accrued_interest_amt(&self) -> bool {
        self.message.body.has(tag::ACCRUED_INTEREST_AMT)
    }




    /// Sets `AccruedInterestRate`, Tag 158.
    pub fn set_accrued_interest_rate(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::ACCRUED_INTEREST_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `AccruedInterestRate`, Tag 158.
    pub fn get_accrued_interest_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::AccruedInterestRateField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::ACCRUED_INTEREST_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `AccruedInterestRate` is present, Tag 158.
    pub fn has_accrued_interest_rate(&self) -> bool {
        self.message.body.has(tag::ACCRUED_INTEREST_RATE)
    }




    /// Sets `BenchmarkCurveCurrency`, Tag 220.
    pub fn set_benchmark_curve_currency(&mut self, v: String) {
        self.message.body.set_field(tag::BENCHMARK_CURVE_CURRENCY, FIXString::from(v));
    }

    /// Gets `BenchmarkCurveCurrency`, Tag 220.
    pub fn get_benchmark_curve_currency(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::BenchmarkCurveCurrencyField::new(String::new());
        self.message.body.get_field(tag::BENCHMARK_CURVE_CURRENCY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `BenchmarkCurveCurrency` is present, Tag 220.
    pub fn has_benchmark_curve_currency(&self) -> bool {
        self.message.body.has(tag::BENCHMARK_CURVE_CURRENCY)
    }




    /// Sets `BenchmarkCurveName`, Tag 221.
    pub fn set_benchmark_curve_name(&mut self, v: String) {
        self.message.body.set_field(tag::BENCHMARK_CURVE_NAME, FIXString::from(v));
    }

    /// Gets `BenchmarkCurveName`, Tag 221.
    pub fn get_benchmark_curve_name(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::BenchmarkCurveNameField::new(String::new());
        self.message.body.get_field(tag::BENCHMARK_CURVE_NAME, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `BenchmarkCurveName` is present, Tag 221.
    pub fn has_benchmark_curve_name(&self) -> bool {
        self.message.body.has(tag::BENCHMARK_CURVE_NAME)
    }




    /// Sets `BenchmarkCurvePoint`, Tag 222.
    pub fn set_benchmark_curve_point(&mut self, v: String) {
        self.message.body.set_field(tag::BENCHMARK_CURVE_POINT, FIXString::from(v));
    }

    /// Gets `BenchmarkCurvePoint`, Tag 222.
    pub fn get_benchmark_curve_point(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::BenchmarkCurvePointField::new(String::new());
        self.message.body.get_field(tag::BENCHMARK_CURVE_POINT, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `BenchmarkCurvePoint` is present, Tag 222.
    pub fn has_benchmark_curve_point(&self) -> bool {
        self.message.body.has(tag::BENCHMARK_CURVE_POINT)
    }




    /// Sets `CFICode`, Tag 461.
    pub fn set_cfi_code(&mut self, v: String) {
        self.message.body.set_field(tag::CFI_CODE, FIXString::from(v));
    }

    /// Gets `CFICode`, Tag 461.
    pub fn get_cfi_code(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CFICodeField::new(String::new());
        self.message.body.get_field(tag::CFI_CODE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CFICode` is present, Tag 461.
    pub fn has_cfi_code(&self) -> bool {
        self.message.body.has(tag::CFI_CODE)
    }




    /// Sets `CancellationRights`, Tag 480.
    pub fn set_cancellation_rights(&mut self, v: String) {
        self.message.body.set_field(tag::CANCELLATION_RIGHTS, FIXString::from(v));
    }

    /// Gets `CancellationRights`, Tag 480.
    pub fn get_cancellation_rights(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CancellationRightsField::new(String::new());
        self.message.body.get_field(tag::CANCELLATION_RIGHTS, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CancellationRights` is present, Tag 480.
    pub fn has_cancellation_rights(&self) -> bool {
        self.message.body.has(tag::CANCELLATION_RIGHTS)
    }




    /// Sets `ComplianceID`, Tag 376.
    pub fn set_compliance_id(&mut self, v: String) {
        self.message.body.set_field(tag::COMPLIANCE_ID, FIXString::from(v));
    }

    /// Gets `ComplianceID`, Tag 376.
    pub fn get_compliance_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::ComplianceIDField::new(String::new());
        self.message.body.get_field(tag::COMPLIANCE_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `ComplianceID` is present, Tag 376.
    pub fn has_compliance_id(&self) -> bool {
        self.message.body.has(tag::COMPLIANCE_ID)
    }




    /// Sets `ContractMultiplier`, Tag 231.
    pub fn set_contract_multiplier(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::CONTRACT_MULTIPLIER, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `ContractMultiplier`, Tag 231.
    pub fn get_contract_multiplier(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::ContractMultiplierField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::CONTRACT_MULTIPLIER, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `ContractMultiplier` is present, Tag 231.
    pub fn has_contract_multiplier(&self) -> bool {
        self.message.body.has(tag::CONTRACT_MULTIPLIER)
    }




    /// Sets `CountryOfIssue`, Tag 470.
    pub fn set_country_of_issue(&mut self, v: String) {
        self.message.body.set_field(tag::COUNTRY_OF_ISSUE, FIXString::from(v));
    }

    /// Gets `CountryOfIssue`, Tag 470.
    pub fn get_country_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CountryOfIssueField::new(String::new());
        self.message.body.get_field(tag::COUNTRY_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CountryOfIssue` is present, Tag 470.
    pub fn has_country_of_issue(&self) -> bool {
        self.message.body.has(tag::COUNTRY_OF_ISSUE)
    }




    /// Sets `CouponPaymentDate`, Tag 224.
    pub fn set_coupon_payment_date(&mut self, v: String) {
        self.message.body.set_field(tag::COUPON_PAYMENT_DATE, FIXString::from(v));
    }

    /// Gets `CouponPaymentDate`, Tag 224.
    pub fn get_coupon_payment_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CouponPaymentDateField::new(String::new());
        self.message.body.get_field(tag::COUPON_PAYMENT_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CouponPaymentDate` is present, Tag 224.
    pub fn has_coupon_payment_date(&self) -> bool {
        self.message.body.has(tag::COUPON_PAYMENT_DATE)
    }




    /// Sets `CouponRate`, Tag 223.
    pub fn set_coupon_rate(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::COUPON_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `CouponRate`, Tag 223.
    pub fn get_coupon_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::CouponRateField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::COUPON_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `CouponRate` is present, Tag 223.
    pub fn has_coupon_rate(&self) -> bool {
        self.message.body.has(tag::COUPON_RATE)
    }




    /// Sets `CreditRating`, Tag 255.
    pub fn set_credit_rating(&mut self, v: String) {
        self.message.body.set_field(tag::CREDIT_RATING, FIXString::from(v));
    }

    /// Gets `CreditRating`, Tag 255.
    pub fn get_credit_rating(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CreditRatingField::new(String::new());
        self.message.body.get_field(tag::CREDIT_RATING, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CreditRating` is present, Tag 255.
    pub fn has_credit_rating(&self) -> bool {
        self.message.body.has(tag::CREDIT_RATING)
    }




    /// Sets `CrossID`, Tag 548.
    pub fn set_cross_id(&mut self, v: String) {
        self.message.body.set_field(tag::CROSS_ID, FIXString::from(v));
    }

    /// Gets `CrossID`, Tag 548.
    pub fn get_cross_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CrossIDField::new(String::new());
        self.message.body.get_field(tag::CROSS_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CrossID` is present, Tag 548.
    pub fn has_cross_id(&self) -> bool {
        self.message.body.has(tag::CROSS_ID)
    }




    /// Sets `CrossPrioritization`, Tag 550.
    pub fn set_cross_prioritization(&mut self, v: isize) {
        self.message.body.set_field(tag::CROSS_PRIORITIZATION, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `CrossPrioritization`, Tag 550.
    pub fn get_cross_prioritization(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::CrossPrioritizationField::new(0);
        self.message.body.get_field(tag::CROSS_PRIORITIZATION, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `CrossPrioritization` is present, Tag 550.
    pub fn has_cross_prioritization(&self) -> bool {
        self.message.body.has(tag::CROSS_PRIORITIZATION)
    }




    /// Sets `CrossType`, Tag 549.
    pub fn set_cross_type(&mut self, v: isize) {
        self.message.body.set_field(tag::CROSS_TYPE, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `CrossType`, Tag 549.
    pub fn get_cross_type(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::CrossTypeField::new(0);
        self.message.body.get_field(tag::CROSS_TYPE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `CrossType` is present, Tag 549.
    pub fn has_cross_type(&self) -> bool {
        self.message.body.has(tag::CROSS_TYPE)
    }




    /// Sets `Currency`, Tag 15.
    pub fn set_currency(&mut self, v: String) {
        self.message.body.set_field(tag::CURRENCY, FIXString::from(v));
    }

    /// Gets `Currency`, Tag 15.
    pub fn get_currency(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CurrencyField::new(String::new());
        self.message.body.get_field(tag::CURRENCY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Currency` is present, Tag 15.
    pub fn has_currency(&self) -> bool {
        self.message.body.has(tag::CURRENCY)
    }




    /// Sets `Designation`, Tag 494.
    pub fn set_designation(&mut self, v: String) {
        self.message.body.set_field(tag::DESIGNATION, FIXString::from(v));
    }

    /// Gets `Designation`, Tag 494.
    pub fn get_designation(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::DesignationField::new(String::new());
        self.message.body.get_field(tag::DESIGNATION, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Designation` is present, Tag 494.
    pub fn has_designation(&self) -> bool {
        self.message.body.has(tag::DESIGNATION)
    }




    /// Sets `DiscretionInst`, Tag 388.
    pub fn set_discretion_inst(&mut self, v: String) {
        self.message.body.set_field(tag::DISCRETION_INST, FIXString::from(v));
    }

    /// Gets `DiscretionInst`, Tag 388.
    pub fn get_discretion_inst(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::DiscretionInstField::new(String::new());
        self.message.body.get_field(tag::DISCRETION_INST, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `DiscretionInst` is present, Tag 388.
    pub fn has_discretion_inst(&self) -> bool {
        self.message.body.has(tag::DISCRETION_INST)
    }




    /// Sets `DiscretionOffset`, Tag 389.
    pub fn set_discretion_offset(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::DISCRETION_OFFSET, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `DiscretionOffset`, Tag 389.
    pub fn get_discretion_offset(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::DiscretionOffsetField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::DISCRETION_OFFSET, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `DiscretionOffset` is present, Tag 389.
    pub fn has_discretion_offset(&self) -> bool {
        self.message.body.has(tag::DISCRETION_OFFSET)
    }




    /// Sets `EffectiveTime`, Tag 168.
    pub fn set_effective_time(&mut self, v: Timestamp) {
        self.message.body.set_field(tag::EFFECTIVE_TIME, fixer::fix_utc_timestamp::FIXUTCTimestamp {
            time: v,
            precision: fixer::fix_utc_timestamp::TimestampPrecision::Millis,
        });
    }

    /// Gets `EffectiveTime`, Tag 168.
    pub fn get_effective_time(&self) -> Result<Timestamp, MessageRejectErrorEnum> {
        let mut fld = field::EffectiveTimeField::new(Timestamp::UNIX_EPOCH);
        self.message.body.get_field(tag::EFFECTIVE_TIME, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EffectiveTime` is present, Tag 168.
    pub fn has_effective_time(&self) -> bool {
        self.message.body.has(tag::EFFECTIVE_TIME)
    }




    /// Sets `EncodedIssuer`, Tag 349.
    pub fn set_encoded_issuer(&mut self, v: String) {
        self.message.body.set_field(tag::ENCODED_ISSUER, FIXString::from(v));
    }

    /// Gets `EncodedIssuer`, Tag 349.
    pub fn get_encoded_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedIssuerField::new(String::new());
        self.message.body.get_field(tag::ENCODED_ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedIssuer` is present, Tag 349.
    pub fn has_encoded_issuer(&self) -> bool {
        self.message.body.has(tag::ENCODED_ISSUER)
    }




    /// Sets `EncodedIssuerLen`, Tag 348.
    pub fn set_encoded_issuer_len(&mut self, v: isize) {
        self.message.body.set_field(tag::ENCODED_ISSUER_LEN, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `EncodedIssuerLen`, Tag 348.
    pub fn get_encoded_issuer_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedIssuerLenField::new(0);
        self.message.body.get_field(tag::ENCODED_ISSUER_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedIssuerLen` is present, Tag 348.
    pub fn has_encoded_issuer_len(&self) -> bool {
        self.message.body.has(tag::ENCODED_ISSUER_LEN)
    }




    /// Sets `EncodedSecurityDesc`, Tag 351.
    pub fn set_encoded_security_desc(&mut self, v: String) {
        self.message.body.set_field(tag::ENCODED_SECURITY_DESC, FIXString::from(v));
    }

    /// Gets `EncodedSecurityDesc`, Tag 351.
    pub fn get_encoded_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedSecurityDescField::new(String::new());
        self.message.body.get_field(tag::ENCODED_SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedSecurityDesc` is present, Tag 351.
    pub fn has_encoded_security_desc(&self) -> bool {
        self.message.body.has(tag::ENCODED_SECURITY_DESC)
    }




    /// Sets `EncodedSecurityDescLen`, Tag 350.
    pub fn set_encoded_security_desc_len(&mut self, v: isize) {
        self.message.body.set_field(tag::ENCODED_SECURITY_DESC_LEN, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `EncodedSecurityDescLen`, Tag 350.
    pub fn get_encoded_security_desc_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedSecurityDescLenField::new(0);
        self.message.body.get_field(tag::ENCODED_SECURITY_DESC_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedSecurityDescLen` is present, Tag 350.
    pub fn has_encoded_security_desc_len(&self) -> bool {
        self.message.body.has(tag::ENCODED_SECURITY_DESC_LEN)
    }




    /// Sets `ExDestination`, Tag 100.
    pub fn set_ex_destination(&mut self, v: String) {
        self.message.body.set_field(tag::EX_DESTINATION, FIXString::from(v));
    }

    /// Gets `ExDestination`, Tag 100.
    pub fn get_ex_destination(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::ExDestinationField::new(String::new());
        self.message.body.get_field(tag::EX_DESTINATION, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `ExDestination` is present, Tag 100.
    pub fn has_ex_destination(&self) -> bool {
        self.message.body.has(tag::EX_DESTINATION)
    }




    /// Sets `ExecInst`, Tag 18.
    pub fn set_exec_inst(&mut self, v: String) {
        self.message.body.set_field(tag::EXEC_INST, FIXString::from(v));
    }

    /// Gets `ExecInst`, Tag 18.
    pub fn get_exec_inst(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::ExecInstField::new(String::new());
        self.message.body.get_field(tag::EXEC_INST, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `ExecInst` is present, Tag 18.
    pub fn has_exec_inst(&self) -> bool {
        self.message.body.has(tag::EXEC_INST)
    }




    /// Sets `ExpireDate`, Tag 432.
    pub fn set_expire_date(&mut self, v: String) {
        self.message.body.set_field(tag::EXPIRE_DATE, FIXString::from(v));
    }

    /// Gets `ExpireDate`, Tag 432.
    pub fn get_expire_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::ExpireDateField::new(String::new());
        self.message.body.get_field(tag::EXPIRE_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `ExpireDate` is present, Tag 432.
    pub fn has_expire_date(&self) -> bool {
        self.message.body.has(tag::EXPIRE_DATE)
    }




    /// Sets `ExpireTime`, Tag 126.
    pub fn set_expire_time(&mut self, v: Timestamp) {
        self.message.body.set_field(tag::EXPIRE_TIME, fixer::fix_utc_timestamp::FIXUTCTimestamp {
            time: v,
            precision: fixer::fix_utc_timestamp::TimestampPrecision::Millis,
        });
    }

    /// Gets `ExpireTime`, Tag 126.
    pub fn get_expire_time(&self) -> Result<Timestamp, MessageRejectErrorEnum> {
        let mut fld = field::ExpireTimeField::new(Timestamp::UNIX_EPOCH);
        self.message.body.get_field(tag::EXPIRE_TIME, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `ExpireTime` is present, Tag 126.
    pub fn has_expire_time(&self) -> bool {
        self.message.body.has(tag::EXPIRE_TIME)
    }




    /// Sets `Factor`, Tag 228.
    pub fn set_factor(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::FACTOR, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `Factor`, Tag 228.
    pub fn get_factor(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::FactorField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::FACTOR, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Factor` is present, Tag 228.
    pub fn has_factor(&self) -> bool {
        self.message.body.has(tag::FACTOR)
    }




    /// Sets `FutSettDate`, Tag 64.
    pub fn set_fut_sett_date(&mut self, v: String) {
        self.message.body.set_field(tag::FUT_SETT_DATE, FIXString::from(v));
    }

    /// Gets `FutSettDate`, Tag 64.
    pub fn get_fut_sett_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::FutSettDateField::new(String::new());
        self.message.body.get_field(tag::FUT_SETT_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `FutSettDate` is present, Tag 64.
    pub fn has_fut_sett_date(&self) -> bool {
        self.message.body.has(tag::FUT_SETT_DATE)
    }




    /// Sets `GTBookingInst`, Tag 427.
    pub fn set_gt_booking_inst(&mut self, v: isize) {
        self.message.body.set_field(tag::GT_BOOKING_INST, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `GTBookingInst`, Tag 427.
    pub fn get_gt_booking_inst(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::GTBookingInstField::new(0);
        self.message.body.get_field(tag::GT_BOOKING_INST, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `GTBookingInst` is present, Tag 427.
    pub fn has_gt_booking_inst(&self) -> bool {
        self.message.body.has(tag::GT_BOOKING_INST)
    }




    /// Sets `HandlInst`, Tag 21.
    pub fn set_handl_inst(&mut self, v: String) {
        self.message.body.set_field(tag::HANDL_INST, FIXString::from(v));
    }

    /// Gets `HandlInst`, Tag 21.
    pub fn get_handl_inst(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::HandlInstField::new(String::new());
        self.message.body.get_field(tag::HANDL_INST, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `HandlInst` is present, Tag 21.
    pub fn has_handl_inst(&self) -> bool {
        self.message.body.has(tag::HANDL_INST)
    }




    /// Sets `IOIid`, Tag 23.
    pub fn set_io_iid(&mut self, v: String) {
        self.message.body.set_field(tag::IO_IID, FIXString::from(v));
    }

    /// Gets `IOIid`, Tag 23.
    pub fn get_io_iid(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IOIidField::new(String::new());
        self.message.body.get_field(tag::IO_IID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `IOIid` is present, Tag 23.
    pub fn has_io_iid(&self) -> bool {
        self.message.body.has(tag::IO_IID)
    }




    /// Sets `InstrRegistry`, Tag 543.
    pub fn set_instr_registry(&mut self, v: String) {
        self.message.body.set_field(tag::INSTR_REGISTRY, FIXString::from(v));
    }

    /// Gets `InstrRegistry`, Tag 543.
    pub fn get_instr_registry(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::InstrRegistryField::new(String::new());
        self.message.body.get_field(tag::INSTR_REGISTRY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `InstrRegistry` is present, Tag 543.
    pub fn has_instr_registry(&self) -> bool {
        self.message.body.has(tag::INSTR_REGISTRY)
    }




    /// Sets `IssueDate`, Tag 225.
    pub fn set_issue_date(&mut self, v: String) {
        self.message.body.set_field(tag::ISSUE_DATE, FIXString::from(v));
    }

    /// Gets `IssueDate`, Tag 225.
    pub fn get_issue_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IssueDateField::new(String::new());
        self.message.body.get_field(tag::ISSUE_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `IssueDate` is present, Tag 225.
    pub fn has_issue_date(&self) -> bool {
        self.message.body.has(tag::ISSUE_DATE)
    }




    /// Sets `Issuer`, Tag 106.
    pub fn set_issuer(&mut self, v: String) {
        self.message.body.set_field(tag::ISSUER, FIXString::from(v));
    }

    /// Gets `Issuer`, Tag 106.
    pub fn get_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IssuerField::new(String::new());
        self.message.body.get_field(tag::ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Issuer` is present, Tag 106.
    pub fn has_issuer(&self) -> bool {
        self.message.body.has(tag::ISSUER)
    }




    /// Sets `LocaleOfIssue`, Tag 472.
    pub fn set_locale_of_issue(&mut self, v: String) {
        self.message.body.set_field(tag::LOCALE_OF_ISSUE, FIXString::from(v));
    }

    /// Gets `LocaleOfIssue`, Tag 472.
    pub fn get_locale_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::LocaleOfIssueField::new(String::new());
        self.message.body.get_field(tag::LOCALE_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `LocaleOfIssue` is present, Tag 472.
    pub fn has_locale_of_issue(&self) -> bool {
        self.message.body.has(tag::LOCALE_OF_ISSUE)
    }




    /// Sets `LocateReqd`, Tag 114.
    pub fn set_locate_reqd(&mut self, v: bool) {
        self.message.body.set_field(tag::LOCATE_REQD, fixer::fix_boolean::FIXBoolean::from(v));
    }

    /// Gets `LocateReqd`, Tag 114.
    pub fn get_locate_reqd(&self) -> Result<bool, MessageRejectErrorEnum> {
        let mut fld = field::LocateReqdField::new(false);
        self.message.body.get_field(tag::LOCATE_REQD, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `LocateReqd` is present, Tag 114.
    pub fn has_locate_reqd(&self) -> bool {
        self.message.body.has(tag::LOCATE_REQD)
    }




    /// Sets `MaturityDate`, Tag 541.
    pub fn set_maturity_date(&mut self, v: String) {
        self.message.body.set_field(tag::MATURITY_DATE, FIXString::from(v));
    }

    /// Gets `MaturityDate`, Tag 541.
    pub fn get_maturity_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MaturityDateField::new(String::new());
        self.message.body.get_field(tag::MATURITY_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MaturityDate` is present, Tag 541.
    pub fn has_maturity_date(&self) -> bool {
        self.message.body.has(tag::MATURITY_DATE)
    }




    /// Sets `MaturityMonthYear`, Tag 200.
    pub fn set_maturity_month_year(&mut self, v: String) {
        self.message.body.set_field(tag::MATURITY_MONTH_YEAR, FIXString::from(v));
    }

    /// Gets `MaturityMonthYear`, Tag 200.
    pub fn get_maturity_month_year(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MaturityMonthYearField::new(String::new());
        self.message.body.get_field(tag::MATURITY_MONTH_YEAR, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MaturityMonthYear` is present, Tag 200.
    pub fn has_maturity_month_year(&self) -> bool {
        self.message.body.has(tag::MATURITY_MONTH_YEAR)
    }




    /// Sets `MaxFloor`, Tag 111.
    pub fn set_max_floor(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::MAX_FLOOR, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `MaxFloor`, Tag 111.
    pub fn get_max_floor(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::MaxFloorField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::MAX_FLOOR, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `MaxFloor` is present, Tag 111.
    pub fn has_max_floor(&self) -> bool {
        self.message.body.has(tag::MAX_FLOOR)
    }




    /// Sets `MaxShow`, Tag 210.
    pub fn set_max_show(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::MAX_SHOW, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `MaxShow`, Tag 210.
    pub fn get_max_show(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::MaxShowField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::MAX_SHOW, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `MaxShow` is present, Tag 210.
    pub fn has_max_show(&self) -> bool {
        self.message.body.has(tag::MAX_SHOW)
    }




    /// Sets `MinQty`, Tag 110.
    pub fn set_min_qty(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::MIN_QTY, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `MinQty`, Tag 110.
    pub fn get_min_qty(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::MinQtyField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::MIN_QTY, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `MinQty` is present, Tag 110.
    pub fn has_min_qty(&self) -> bool {
        self.message.body.has(tag::MIN_QTY)
    }




    /// Sets `MoneyLaunderingStatus`, Tag 481.
    pub fn set_money_laundering_status(&mut self, v: String) {
        self.message.body.set_field(tag::MONEY_LAUNDERING_STATUS, FIXString::from(v));
    }

    /// Gets `MoneyLaunderingStatus`, Tag 481.
    pub fn get_money_laundering_status(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MoneyLaunderingStatusField::new(String::new());
        self.message.body.get_field(tag::MONEY_LAUNDERING_STATUS, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MoneyLaunderingStatus` is present, Tag 481.
    pub fn has_money_laundering_status(&self) -> bool {
        self.message.body.has(tag::MONEY_LAUNDERING_STATUS)
    }




    /// Sets `NetMoney`, Tag 118.
    pub fn set_net_money(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::NET_MONEY, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `NetMoney`, Tag 118.
    pub fn get_net_money(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::NetMoneyField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::NET_MONEY, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `NetMoney` is present, Tag 118.
    pub fn has_net_money(&self) -> bool {
        self.message.body.has(tag::NET_MONEY)
    }




    /// Sets `NoSecurityAltID`, Tag 454.
    pub fn set_no_security_alt_id(&mut self, v: isize) {
        self.message.body.set_field(tag::NO_SECURITY_ALT_ID, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `NoSecurityAltID`, Tag 454.
    pub fn get_no_security_alt_id(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::NoSecurityAltIDField::new(0);
        self.message.body.get_field(tag::NO_SECURITY_ALT_ID, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `NoSecurityAltID` is present, Tag 454.
    pub fn has_no_security_alt_id(&self) -> bool {
        self.message.body.has(tag::NO_SECURITY_ALT_ID)
    }




    /// Sets `NoSides`, Tag 552.
    pub fn set_no_sides(&mut self, v: isize) {
        self.message.body.set_field(tag::NO_SIDES, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `NoSides`, Tag 552.
    pub fn get_no_sides(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::NoSidesField::new(0);
        self.message.body.get_field(tag::NO_SIDES, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `NoSides` is present, Tag 552.
    pub fn has_no_sides(&self) -> bool {
        self.message.body.has(tag::NO_SIDES)
    }




    /// Sets `NoStipulations`, Tag 232.
    pub fn set_no_stipulations(&mut self, v: isize) {
        self.message.body.set_field(tag::NO_STIPULATIONS, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `NoStipulations`, Tag 232.
    pub fn get_no_stipulations(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::NoStipulationsField::new(0);
        self.message.body.get_field(tag::NO_STIPULATIONS, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `NoStipulations` is present, Tag 232.
    pub fn has_no_stipulations(&self) -> bool {
        self.message.body.has(tag::NO_STIPULATIONS)
    }




    /// Sets `NoTradingSessions`, Tag 386.
    pub fn set_no_trading_sessions(&mut self, v: isize) {
        self.message.body.set_field(tag::NO_TRADING_SESSIONS, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `NoTradingSessions`, Tag 386.
    pub fn get_no_trading_sessions(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::NoTradingSessionsField::new(0);
        self.message.body.get_field(tag::NO_TRADING_SESSIONS, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `NoTradingSessions` is present, Tag 386.
    pub fn has_no_trading_sessions(&self) -> bool {
        self.message.body.has(tag::NO_TRADING_SESSIONS)
    }




    /// Sets `OptAttribute`, Tag 206.
    pub fn set_opt_attribute(&mut self, v: String) {
        self.message.body.set_field(tag::OPT_ATTRIBUTE, FIXString::from(v));
    }

    /// Gets `OptAttribute`, Tag 206.
    pub fn get_opt_attribute(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::OptAttributeField::new(String::new());
        self.message.body.get_field(tag::OPT_ATTRIBUTE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `OptAttribute` is present, Tag 206.
    pub fn has_opt_attribute(&self) -> bool {
        self.message.body.has(tag::OPT_ATTRIBUTE)
    }




    /// Sets `OrdType`, Tag 40.
    pub fn set_ord_type(&mut self, v: String) {
        self.message.body.set_field(tag::ORD_TYPE, FIXString::from(v));
    }

    /// Gets `OrdType`, Tag 40.
    pub fn get_ord_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::OrdTypeField::new(String::new());
        self.message.body.get_field(tag::ORD_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `OrdType` is present, Tag 40.
    pub fn has_ord_type(&self) -> bool {
        self.message.body.has(tag::ORD_TYPE)
    }




    /// Sets `PegDifference`, Tag 211.
    pub fn set_peg_difference(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::PEG_DIFFERENCE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `PegDifference`, Tag 211.
    pub fn get_peg_difference(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::PegDifferenceField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::PEG_DIFFERENCE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `PegDifference` is present, Tag 211.
    pub fn has_peg_difference(&self) -> bool {
        self.message.body.has(tag::PEG_DIFFERENCE)
    }




    /// Sets `PrevClosePx`, Tag 140.
    pub fn set_prev_close_px(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::PREV_CLOSE_PX, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `PrevClosePx`, Tag 140.
    pub fn get_prev_close_px(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::PrevClosePxField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::PREV_CLOSE_PX, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `PrevClosePx` is present, Tag 140.
    pub fn has_prev_close_px(&self) -> bool {
        self.message.body.has(tag::PREV_CLOSE_PX)
    }




    /// Sets `Price`, Tag 44.
    pub fn set_price(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::PRICE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `Price`, Tag 44.
    pub fn get_price(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::PriceField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::PRICE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Price` is present, Tag 44.
    pub fn has_price(&self) -> bool {
        self.message.body.has(tag::PRICE)
    }




    /// Sets `PriceType`, Tag 423.
    pub fn set_price_type(&mut self, v: isize) {
        self.message.body.set_field(tag::PRICE_TYPE, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `PriceType`, Tag 423.
    pub fn get_price_type(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::PriceTypeField::new(0);
        self.message.body.get_field(tag::PRICE_TYPE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `PriceType` is present, Tag 423.
    pub fn has_price_type(&self) -> bool {
        self.message.body.has(tag::PRICE_TYPE)
    }




    /// Sets `ProcessCode`, Tag 81.
    pub fn set_process_code(&mut self, v: String) {
        self.message.body.set_field(tag::PROCESS_CODE, FIXString::from(v));
    }

    /// Gets `ProcessCode`, Tag 81.
    pub fn get_process_code(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::ProcessCodeField::new(String::new());
        self.message.body.get_field(tag::PROCESS_CODE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `ProcessCode` is present, Tag 81.
    pub fn has_process_code(&self) -> bool {
        self.message.body.has(tag::PROCESS_CODE)
    }




    /// Sets `Product`, Tag 460.
    pub fn set_product(&mut self, v: isize) {
        self.message.body.set_field(tag::PRODUCT, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `Product`, Tag 460.
    pub fn get_product(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::ProductField::new(0);
        self.message.body.get_field(tag::PRODUCT, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Product` is present, Tag 460.
    pub fn has_product(&self) -> bool {
        self.message.body.has(tag::PRODUCT)
    }




    /// Sets `QuoteID`, Tag 117.
    pub fn set_quote_id(&mut self, v: String) {
        self.message.body.set_field(tag::QUOTE_ID, FIXString::from(v));
    }

    /// Gets `QuoteID`, Tag 117.
    pub fn get_quote_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::QuoteIDField::new(String::new());
        self.message.body.get_field(tag::QUOTE_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `QuoteID` is present, Tag 117.
    pub fn has_quote_id(&self) -> bool {
        self.message.body.has(tag::QUOTE_ID)
    }




    /// Sets `RedemptionDate`, Tag 240.
    pub fn set_redemption_date(&mut self, v: String) {
        self.message.body.set_field(tag::REDEMPTION_DATE, FIXString::from(v));
    }

    /// Gets `RedemptionDate`, Tag 240.
    pub fn get_redemption_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::RedemptionDateField::new(String::new());
        self.message.body.get_field(tag::REDEMPTION_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `RedemptionDate` is present, Tag 240.
    pub fn has_redemption_date(&self) -> bool {
        self.message.body.has(tag::REDEMPTION_DATE)
    }




    /// Sets `RegistID`, Tag 513.
    pub fn set_regist_id(&mut self, v: String) {
        self.message.body.set_field(tag::REGIST_ID, FIXString::from(v));
    }

    /// Gets `RegistID`, Tag 513.
    pub fn get_regist_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::RegistIDField::new(String::new());
        self.message.body.get_field(tag::REGIST_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `RegistID` is present, Tag 513.
    pub fn has_regist_id(&self) -> bool {
        self.message.body.has(tag::REGIST_ID)
    }




    /// Sets `RepoCollateralSecurityType`, Tag 239.
    pub fn set_repo_collateral_security_type(&mut self, v: isize) {
        self.message.body.set_field(tag::REPO_COLLATERAL_SECURITY_TYPE, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `RepoCollateralSecurityType`, Tag 239.
    pub fn get_repo_collateral_security_type(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::RepoCollateralSecurityTypeField::new(0);
        self.message.body.get_field(tag::REPO_COLLATERAL_SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RepoCollateralSecurityType` is present, Tag 239.
    pub fn has_repo_collateral_security_type(&self) -> bool {
        self.message.body.has(tag::REPO_COLLATERAL_SECURITY_TYPE)
    }




    /// Sets `RepurchaseRate`, Tag 227.
    pub fn set_repurchase_rate(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::REPURCHASE_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `RepurchaseRate`, Tag 227.
    pub fn get_repurchase_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::RepurchaseRateField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::REPURCHASE_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RepurchaseRate` is present, Tag 227.
    pub fn has_repurchase_rate(&self) -> bool {
        self.message.body.has(tag::REPURCHASE_RATE)
    }




    /// Sets `RepurchaseTerm`, Tag 226.
    pub fn set_repurchase_term(&mut self, v: isize) {
        self.message.body.set_field(tag::REPURCHASE_TERM, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `RepurchaseTerm`, Tag 226.
    pub fn get_repurchase_term(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::RepurchaseTermField::new(0);
        self.message.body.get_field(tag::REPURCHASE_TERM, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RepurchaseTerm` is present, Tag 226.
    pub fn has_repurchase_term(&self) -> bool {
        self.message.body.has(tag::REPURCHASE_TERM)
    }




    /// Sets `SecurityDesc`, Tag 107.
    pub fn set_security_desc(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_DESC, FIXString::from(v));
    }

    /// Gets `SecurityDesc`, Tag 107.
    pub fn get_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityDescField::new(String::new());
        self.message.body.get_field(tag::SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityDesc` is present, Tag 107.
    pub fn has_security_desc(&self) -> bool {
        self.message.body.has(tag::SECURITY_DESC)
    }




    /// Sets `SecurityExchange`, Tag 207.
    pub fn set_security_exchange(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_EXCHANGE, FIXString::from(v));
    }

    /// Gets `SecurityExchange`, Tag 207.
    pub fn get_security_exchange(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityExchangeField::new(String::new());
        self.message.body.get_field(tag::SECURITY_EXCHANGE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityExchange` is present, Tag 207.
    pub fn has_security_exchange(&self) -> bool {
        self.message.body.has(tag::SECURITY_EXCHANGE)
    }




    /// Sets `SecurityID`, Tag 48.
    pub fn set_security_id(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_ID, FIXString::from(v));
    }

    /// Gets `SecurityID`, Tag 48.
    pub fn get_security_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityIDField::new(String::new());
        self.message.body.get_field(tag::SECURITY_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityID` is present, Tag 48.
    pub fn has_security_id(&self) -> bool {
        self.message.body.has(tag::SECURITY_ID)
    }




    /// Sets `SecurityIDSource`, Tag 22.
    pub fn set_security_id_source(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_ID_SOURCE, FIXString::from(v));
    }

    /// Gets `SecurityIDSource`, Tag 22.
    pub fn get_security_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityIDSourceField::new(String::new());
        self.message.body.get_field(tag::SECURITY_ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityIDSource` is present, Tag 22.
    pub fn has_security_id_source(&self) -> bool {
        self.message.body.has(tag::SECURITY_ID_SOURCE)
    }




    /// Sets `SecurityType`, Tag 167.
    pub fn set_security_type(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_TYPE, FIXString::from(v));
    }

    /// Gets `SecurityType`, Tag 167.
    pub fn get_security_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityTypeField::new(String::new());
        self.message.body.get_field(tag::SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityType` is present, Tag 167.
    pub fn has_security_type(&self) -> bool {
        self.message.body.has(tag::SECURITY_TYPE)
    }




    /// Sets `SettlmntTyp`, Tag 63.
    pub fn set_settlmnt_typ(&mut self, v: String) {
        self.message.body.set_field(tag::SETTLMNT_TYP, FIXString::from(v));
    }

    /// Gets `SettlmntTyp`, Tag 63.
    pub fn get_settlmnt_typ(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SettlmntTypField::new(String::new());
        self.message.body.get_field(tag::SETTLMNT_TYP, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SettlmntTyp` is present, Tag 63.
    pub fn has_settlmnt_typ(&self) -> bool {
        self.message.body.has(tag::SETTLMNT_TYP)
    }




    /// Sets `Spread`, Tag 218.
    pub fn set_spread(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::SPREAD, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `Spread`, Tag 218.
    pub fn get_spread(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::SpreadField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::SPREAD, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Spread` is present, Tag 218.
    pub fn has_spread(&self) -> bool {
        self.message.body.has(tag::SPREAD)
    }




    /// Sets `StateOrProvinceOfIssue`, Tag 471.
    pub fn set_state_or_province_of_issue(&mut self, v: String) {
        self.message.body.set_field(tag::STATE_OR_PROVINCE_OF_ISSUE, FIXString::from(v));
    }

    /// Gets `StateOrProvinceOfIssue`, Tag 471.
    pub fn get_state_or_province_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::StateOrProvinceOfIssueField::new(String::new());
        self.message.body.get_field(tag::STATE_OR_PROVINCE_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `StateOrProvinceOfIssue` is present, Tag 471.
    pub fn has_state_or_province_of_issue(&self) -> bool {
        self.message.body.has(tag::STATE_OR_PROVINCE_OF_ISSUE)
    }




    /// Sets `StopPx`, Tag 99.
    pub fn set_stop_px(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::STOP_PX, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `StopPx`, Tag 99.
    pub fn get_stop_px(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::StopPxField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::STOP_PX, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `StopPx` is present, Tag 99.
    pub fn has_stop_px(&self) -> bool {
        self.message.body.has(tag::STOP_PX)
    }




    /// Sets `StrikePrice`, Tag 202.
    pub fn set_strike_price(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::STRIKE_PRICE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `StrikePrice`, Tag 202.
    pub fn get_strike_price(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::StrikePriceField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::STRIKE_PRICE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `StrikePrice` is present, Tag 202.
    pub fn has_strike_price(&self) -> bool {
        self.message.body.has(tag::STRIKE_PRICE)
    }




    /// Sets `Symbol`, Tag 55.
    pub fn set_symbol(&mut self, v: String) {
        self.message.body.set_field(tag::SYMBOL, FIXString::from(v));
    }

    /// Gets `Symbol`, Tag 55.
    pub fn get_symbol(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolField::new(String::new());
        self.message.body.get_field(tag::SYMBOL, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Symbol` is present, Tag 55.
    pub fn has_symbol(&self) -> bool {
        self.message.body.has(tag::SYMBOL)
    }




    /// Sets `SymbolSfx`, Tag 65.
    pub fn set_symbol_sfx(&mut self, v: String) {
        self.message.body.set_field(tag::SYMBOL_SFX, FIXString::from(v));
    }

    /// Gets `SymbolSfx`, Tag 65.
    pub fn get_symbol_sfx(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolSfxField::new(String::new());
        self.message.body.get_field(tag::SYMBOL_SFX, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SymbolSfx` is present, Tag 65.
    pub fn has_symbol_sfx(&self) -> bool {
        self.message.body.has(tag::SYMBOL_SFX)
    }




    /// Sets `TimeInForce`, Tag 59.
    pub fn set_time_in_force(&mut self, v: String) {
        self.message.body.set_field(tag::TIME_IN_FORCE, FIXString::from(v));
    }

    /// Gets `TimeInForce`, Tag 59.
    pub fn get_time_in_force(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TimeInForceField::new(String::new());
        self.message.body.get_field(tag::TIME_IN_FORCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `TimeInForce` is present, Tag 59.
    pub fn has_time_in_force(&self) -> bool {
        self.message.body.has(tag::TIME_IN_FORCE)
    }




    /// Sets `TransactTime`, Tag 60.
    pub fn set_transact_time(&mut self, v: Timestamp) {
        self.message.body.set_field(tag::TRANSACT_TIME, fixer::fix_utc_timestamp::FIXUTCTimestamp {
            time: v,
            precision: fixer::fix_utc_timestamp::TimestampPrecision::Millis,
        });
    }

    /// Gets `TransactTime`, Tag 60.
    pub fn get_transact_time(&self) -> Result<Timestamp, MessageRejectErrorEnum> {
        let mut fld = field::TransactTimeField::new(Timestamp::UNIX_EPOCH);
        self.message.body.get_field(tag::TRANSACT_TIME, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `TransactTime` is present, Tag 60.
    pub fn has_transact_time(&self) -> bool {
        self.message.body.has(tag::TRANSACT_TIME)
    }




    /// Sets `Yield`, Tag 236.
    pub fn set_yield(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::YIELD, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `Yield`, Tag 236.
    pub fn get_yield(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::YieldField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::YIELD, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Yield` is present, Tag 236.
    pub fn has_yield(&self) -> bool {
        self.message.body.has(tag::YIELD)
    }




    /// Sets `YieldType`, Tag 235.
    pub fn set_yield_type(&mut self, v: String) {
        self.message.body.set_field(tag::YIELD_TYPE, FIXString::from(v));
    }

    /// Gets `YieldType`, Tag 235.
    pub fn get_yield_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::YieldTypeField::new(String::new());
        self.message.body.get_field(tag::YIELD_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `YieldType` is present, Tag 235.
    pub fn has_yield_type(&self) -> bool {
        self.message.body.has(tag::YIELD_TYPE)
    }


}

/// `RouteOut` is the callback type for routing `NewOrderCross` messages.
pub type RouteOut = fn(msg: NewOrderCross, session_id: SessionID) -> Result<(), MessageRejectErrorEnum>;

/// Route type returned by the `route` function.
pub type Route = (&'static str, &'static str, Box<dyn Fn(&Message, SessionID) -> Result<(), MessageRejectErrorEnum> + Send>);

/// Returns the begin string, message type, and route function for `NewOrderCross`.
pub fn route(router: RouteOut) -> Route {
    let r = move |msg: &Message, session_id: SessionID| -> Result<(), MessageRejectErrorEnum> {
        router(NewOrderCross::from_message(msg.clone()), session_id)
    };
    ("FIX.4.3", "s", Box::new(r))
}
