// Code generated by fixer-gen. DO NOT EDIT.
#![allow(clippy::new_without_default)]
#![allow(clippy::needless_pass_by_value)]
#![allow(clippy::too_many_arguments)]
#![allow(unused_imports)]

use fixer::message::Message;
use fixer::fix_string::FIXString;
use fixer::errors::MessageRejectErrorEnum;
use fixer::session::session_id::SessionID;
use fixer::repeating_group::{Group, GroupTemplate, RepeatingGroup, group_element};
use std::borrow::{Borrow, BorrowMut};

use rust_decimal::Decimal;


use jiff::Timestamp;

use crate::field;
use crate::tag;

/// `OrderMassCancelReport` is the `fix43` `OrderMassCancelReport` type, `MsgType` = r.
pub struct OrderMassCancelReport {
    pub message: Message,
}

impl OrderMassCancelReport {
    /// Creates a new `OrderMassCancelReport` with required fields.
    pub fn new(order_id: field::OrderIDField, mass_cancel_request_type: field::MassCancelRequestTypeField, mass_cancel_response: field::MassCancelResponseField) -> Self {
        let mut msg = Message::new();
        msg.header.set_field(tag::MSG_TYPE, FIXString::from("r".to_string()));

        msg.body.set_field(tag::ORDER_ID, order_id.0);

        msg.body.set_field(tag::MASS_CANCEL_REQUEST_TYPE, mass_cancel_request_type.0);

        msg.body.set_field(tag::MASS_CANCEL_RESPONSE, mass_cancel_response.0);

        Self { message: msg }
    }

    /// Creates a `OrderMassCancelReport` from an existing `Message`.
    pub fn from_message(msg: Message) -> Self {
        Self { message: msg }
    }

    /// Returns the underlying `Message`.
    pub fn to_message(self) -> Message {
        self.message
    }




    /// Sets `CFICode`, Tag 461.
    pub fn set_cfi_code(&mut self, v: String) {
        self.message.body.set_field(tag::CFI_CODE, FIXString::from(v));
    }

    /// Gets `CFICode`, Tag 461.
    pub fn get_cfi_code(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CFICodeField::new(String::new());
        self.message.body.get_field(tag::CFI_CODE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CFICode` is present, Tag 461.
    pub fn has_cfi_code(&self) -> bool {
        self.message.body.has(tag::CFI_CODE)
    }




    /// Sets `ClOrdID`, Tag 11.
    pub fn set_cl_ord_id(&mut self, v: String) {
        self.message.body.set_field(tag::CL_ORD_ID, FIXString::from(v));
    }

    /// Gets `ClOrdID`, Tag 11.
    pub fn get_cl_ord_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::ClOrdIDField::new(String::new());
        self.message.body.get_field(tag::CL_ORD_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `ClOrdID` is present, Tag 11.
    pub fn has_cl_ord_id(&self) -> bool {
        self.message.body.has(tag::CL_ORD_ID)
    }




    /// Sets `ContractMultiplier`, Tag 231.
    pub fn set_contract_multiplier(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::CONTRACT_MULTIPLIER, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `ContractMultiplier`, Tag 231.
    pub fn get_contract_multiplier(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::ContractMultiplierField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::CONTRACT_MULTIPLIER, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `ContractMultiplier` is present, Tag 231.
    pub fn has_contract_multiplier(&self) -> bool {
        self.message.body.has(tag::CONTRACT_MULTIPLIER)
    }




    /// Sets `CountryOfIssue`, Tag 470.
    pub fn set_country_of_issue(&mut self, v: String) {
        self.message.body.set_field(tag::COUNTRY_OF_ISSUE, FIXString::from(v));
    }

    /// Gets `CountryOfIssue`, Tag 470.
    pub fn get_country_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CountryOfIssueField::new(String::new());
        self.message.body.get_field(tag::COUNTRY_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CountryOfIssue` is present, Tag 470.
    pub fn has_country_of_issue(&self) -> bool {
        self.message.body.has(tag::COUNTRY_OF_ISSUE)
    }




    /// Sets `CouponPaymentDate`, Tag 224.
    pub fn set_coupon_payment_date(&mut self, v: String) {
        self.message.body.set_field(tag::COUPON_PAYMENT_DATE, FIXString::from(v));
    }

    /// Gets `CouponPaymentDate`, Tag 224.
    pub fn get_coupon_payment_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CouponPaymentDateField::new(String::new());
        self.message.body.get_field(tag::COUPON_PAYMENT_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CouponPaymentDate` is present, Tag 224.
    pub fn has_coupon_payment_date(&self) -> bool {
        self.message.body.has(tag::COUPON_PAYMENT_DATE)
    }




    /// Sets `CouponRate`, Tag 223.
    pub fn set_coupon_rate(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::COUPON_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `CouponRate`, Tag 223.
    pub fn get_coupon_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::CouponRateField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::COUPON_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `CouponRate` is present, Tag 223.
    pub fn has_coupon_rate(&self) -> bool {
        self.message.body.has(tag::COUPON_RATE)
    }




    /// Sets `CreditRating`, Tag 255.
    pub fn set_credit_rating(&mut self, v: String) {
        self.message.body.set_field(tag::CREDIT_RATING, FIXString::from(v));
    }

    /// Gets `CreditRating`, Tag 255.
    pub fn get_credit_rating(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CreditRatingField::new(String::new());
        self.message.body.get_field(tag::CREDIT_RATING, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CreditRating` is present, Tag 255.
    pub fn has_credit_rating(&self) -> bool {
        self.message.body.has(tag::CREDIT_RATING)
    }




    /// Sets `EncodedIssuer`, Tag 349.
    pub fn set_encoded_issuer(&mut self, v: String) {
        self.message.body.set_field(tag::ENCODED_ISSUER, FIXString::from(v));
    }

    /// Gets `EncodedIssuer`, Tag 349.
    pub fn get_encoded_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedIssuerField::new(String::new());
        self.message.body.get_field(tag::ENCODED_ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedIssuer` is present, Tag 349.
    pub fn has_encoded_issuer(&self) -> bool {
        self.message.body.has(tag::ENCODED_ISSUER)
    }




    /// Sets `EncodedIssuerLen`, Tag 348.
    pub fn set_encoded_issuer_len(&mut self, v: isize) {
        self.message.body.set_field(tag::ENCODED_ISSUER_LEN, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `EncodedIssuerLen`, Tag 348.
    pub fn get_encoded_issuer_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedIssuerLenField::new(0);
        self.message.body.get_field(tag::ENCODED_ISSUER_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedIssuerLen` is present, Tag 348.
    pub fn has_encoded_issuer_len(&self) -> bool {
        self.message.body.has(tag::ENCODED_ISSUER_LEN)
    }




    /// Sets `EncodedSecurityDesc`, Tag 351.
    pub fn set_encoded_security_desc(&mut self, v: String) {
        self.message.body.set_field(tag::ENCODED_SECURITY_DESC, FIXString::from(v));
    }

    /// Gets `EncodedSecurityDesc`, Tag 351.
    pub fn get_encoded_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedSecurityDescField::new(String::new());
        self.message.body.get_field(tag::ENCODED_SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedSecurityDesc` is present, Tag 351.
    pub fn has_encoded_security_desc(&self) -> bool {
        self.message.body.has(tag::ENCODED_SECURITY_DESC)
    }




    /// Sets `EncodedSecurityDescLen`, Tag 350.
    pub fn set_encoded_security_desc_len(&mut self, v: isize) {
        self.message.body.set_field(tag::ENCODED_SECURITY_DESC_LEN, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `EncodedSecurityDescLen`, Tag 350.
    pub fn get_encoded_security_desc_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedSecurityDescLenField::new(0);
        self.message.body.get_field(tag::ENCODED_SECURITY_DESC_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedSecurityDescLen` is present, Tag 350.
    pub fn has_encoded_security_desc_len(&self) -> bool {
        self.message.body.has(tag::ENCODED_SECURITY_DESC_LEN)
    }




    /// Sets `EncodedText`, Tag 355.
    pub fn set_encoded_text(&mut self, v: String) {
        self.message.body.set_field(tag::ENCODED_TEXT, FIXString::from(v));
    }

    /// Gets `EncodedText`, Tag 355.
    pub fn get_encoded_text(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedTextField::new(String::new());
        self.message.body.get_field(tag::ENCODED_TEXT, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedText` is present, Tag 355.
    pub fn has_encoded_text(&self) -> bool {
        self.message.body.has(tag::ENCODED_TEXT)
    }




    /// Sets `EncodedTextLen`, Tag 354.
    pub fn set_encoded_text_len(&mut self, v: isize) {
        self.message.body.set_field(tag::ENCODED_TEXT_LEN, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `EncodedTextLen`, Tag 354.
    pub fn get_encoded_text_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedTextLenField::new(0);
        self.message.body.get_field(tag::ENCODED_TEXT_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedTextLen` is present, Tag 354.
    pub fn has_encoded_text_len(&self) -> bool {
        self.message.body.has(tag::ENCODED_TEXT_LEN)
    }




    /// Sets `EncodedUnderlyingIssuer`, Tag 363.
    pub fn set_encoded_underlying_issuer(&mut self, v: String) {
        self.message.body.set_field(tag::ENCODED_UNDERLYING_ISSUER, FIXString::from(v));
    }

    /// Gets `EncodedUnderlyingIssuer`, Tag 363.
    pub fn get_encoded_underlying_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedUnderlyingIssuerField::new(String::new());
        self.message.body.get_field(tag::ENCODED_UNDERLYING_ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedUnderlyingIssuer` is present, Tag 363.
    pub fn has_encoded_underlying_issuer(&self) -> bool {
        self.message.body.has(tag::ENCODED_UNDERLYING_ISSUER)
    }




    /// Sets `EncodedUnderlyingIssuerLen`, Tag 362.
    pub fn set_encoded_underlying_issuer_len(&mut self, v: isize) {
        self.message.body.set_field(tag::ENCODED_UNDERLYING_ISSUER_LEN, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `EncodedUnderlyingIssuerLen`, Tag 362.
    pub fn get_encoded_underlying_issuer_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedUnderlyingIssuerLenField::new(0);
        self.message.body.get_field(tag::ENCODED_UNDERLYING_ISSUER_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedUnderlyingIssuerLen` is present, Tag 362.
    pub fn has_encoded_underlying_issuer_len(&self) -> bool {
        self.message.body.has(tag::ENCODED_UNDERLYING_ISSUER_LEN)
    }




    /// Sets `EncodedUnderlyingSecurityDesc`, Tag 365.
    pub fn set_encoded_underlying_security_desc(&mut self, v: String) {
        self.message.body.set_field(tag::ENCODED_UNDERLYING_SECURITY_DESC, FIXString::from(v));
    }

    /// Gets `EncodedUnderlyingSecurityDesc`, Tag 365.
    pub fn get_encoded_underlying_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedUnderlyingSecurityDescField::new(String::new());
        self.message.body.get_field(tag::ENCODED_UNDERLYING_SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedUnderlyingSecurityDesc` is present, Tag 365.
    pub fn has_encoded_underlying_security_desc(&self) -> bool {
        self.message.body.has(tag::ENCODED_UNDERLYING_SECURITY_DESC)
    }




    /// Sets `EncodedUnderlyingSecurityDescLen`, Tag 364.
    pub fn set_encoded_underlying_security_desc_len(&mut self, v: isize) {
        self.message.body.set_field(tag::ENCODED_UNDERLYING_SECURITY_DESC_LEN, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `EncodedUnderlyingSecurityDescLen`, Tag 364.
    pub fn get_encoded_underlying_security_desc_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedUnderlyingSecurityDescLenField::new(0);
        self.message.body.get_field(tag::ENCODED_UNDERLYING_SECURITY_DESC_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedUnderlyingSecurityDescLen` is present, Tag 364.
    pub fn has_encoded_underlying_security_desc_len(&self) -> bool {
        self.message.body.has(tag::ENCODED_UNDERLYING_SECURITY_DESC_LEN)
    }




    /// Sets `Factor`, Tag 228.
    pub fn set_factor(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::FACTOR, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `Factor`, Tag 228.
    pub fn get_factor(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::FactorField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::FACTOR, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Factor` is present, Tag 228.
    pub fn has_factor(&self) -> bool {
        self.message.body.has(tag::FACTOR)
    }




    /// Sets `InstrRegistry`, Tag 543.
    pub fn set_instr_registry(&mut self, v: String) {
        self.message.body.set_field(tag::INSTR_REGISTRY, FIXString::from(v));
    }

    /// Gets `InstrRegistry`, Tag 543.
    pub fn get_instr_registry(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::InstrRegistryField::new(String::new());
        self.message.body.get_field(tag::INSTR_REGISTRY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `InstrRegistry` is present, Tag 543.
    pub fn has_instr_registry(&self) -> bool {
        self.message.body.has(tag::INSTR_REGISTRY)
    }




    /// Sets `IssueDate`, Tag 225.
    pub fn set_issue_date(&mut self, v: String) {
        self.message.body.set_field(tag::ISSUE_DATE, FIXString::from(v));
    }

    /// Gets `IssueDate`, Tag 225.
    pub fn get_issue_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IssueDateField::new(String::new());
        self.message.body.get_field(tag::ISSUE_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `IssueDate` is present, Tag 225.
    pub fn has_issue_date(&self) -> bool {
        self.message.body.has(tag::ISSUE_DATE)
    }




    /// Sets `Issuer`, Tag 106.
    pub fn set_issuer(&mut self, v: String) {
        self.message.body.set_field(tag::ISSUER, FIXString::from(v));
    }

    /// Gets `Issuer`, Tag 106.
    pub fn get_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IssuerField::new(String::new());
        self.message.body.get_field(tag::ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Issuer` is present, Tag 106.
    pub fn has_issuer(&self) -> bool {
        self.message.body.has(tag::ISSUER)
    }




    /// Sets `LocaleOfIssue`, Tag 472.
    pub fn set_locale_of_issue(&mut self, v: String) {
        self.message.body.set_field(tag::LOCALE_OF_ISSUE, FIXString::from(v));
    }

    /// Gets `LocaleOfIssue`, Tag 472.
    pub fn get_locale_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::LocaleOfIssueField::new(String::new());
        self.message.body.get_field(tag::LOCALE_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `LocaleOfIssue` is present, Tag 472.
    pub fn has_locale_of_issue(&self) -> bool {
        self.message.body.has(tag::LOCALE_OF_ISSUE)
    }




    /// Sets `MassCancelRejectReason`, Tag 532.
    pub fn set_mass_cancel_reject_reason(&mut self, v: isize) {
        self.message.body.set_field(tag::MASS_CANCEL_REJECT_REASON, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `MassCancelRejectReason`, Tag 532.
    pub fn get_mass_cancel_reject_reason(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::MassCancelRejectReasonField::new(0);
        self.message.body.get_field(tag::MASS_CANCEL_REJECT_REASON, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `MassCancelRejectReason` is present, Tag 532.
    pub fn has_mass_cancel_reject_reason(&self) -> bool {
        self.message.body.has(tag::MASS_CANCEL_REJECT_REASON)
    }




    /// Sets `MassCancelRequestType`, Tag 530.
    pub fn set_mass_cancel_request_type(&mut self, v: String) {
        self.message.body.set_field(tag::MASS_CANCEL_REQUEST_TYPE, FIXString::from(v));
    }

    /// Gets `MassCancelRequestType`, Tag 530.
    pub fn get_mass_cancel_request_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MassCancelRequestTypeField::new(String::new());
        self.message.body.get_field(tag::MASS_CANCEL_REQUEST_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MassCancelRequestType` is present, Tag 530.
    pub fn has_mass_cancel_request_type(&self) -> bool {
        self.message.body.has(tag::MASS_CANCEL_REQUEST_TYPE)
    }




    /// Sets `MassCancelResponse`, Tag 531.
    pub fn set_mass_cancel_response(&mut self, v: String) {
        self.message.body.set_field(tag::MASS_CANCEL_RESPONSE, FIXString::from(v));
    }

    /// Gets `MassCancelResponse`, Tag 531.
    pub fn get_mass_cancel_response(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MassCancelResponseField::new(String::new());
        self.message.body.get_field(tag::MASS_CANCEL_RESPONSE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MassCancelResponse` is present, Tag 531.
    pub fn has_mass_cancel_response(&self) -> bool {
        self.message.body.has(tag::MASS_CANCEL_RESPONSE)
    }




    /// Sets `MaturityDate`, Tag 541.
    pub fn set_maturity_date(&mut self, v: String) {
        self.message.body.set_field(tag::MATURITY_DATE, FIXString::from(v));
    }

    /// Gets `MaturityDate`, Tag 541.
    pub fn get_maturity_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MaturityDateField::new(String::new());
        self.message.body.get_field(tag::MATURITY_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MaturityDate` is present, Tag 541.
    pub fn has_maturity_date(&self) -> bool {
        self.message.body.has(tag::MATURITY_DATE)
    }




    /// Sets `MaturityMonthYear`, Tag 200.
    pub fn set_maturity_month_year(&mut self, v: String) {
        self.message.body.set_field(tag::MATURITY_MONTH_YEAR, FIXString::from(v));
    }

    /// Gets `MaturityMonthYear`, Tag 200.
    pub fn get_maturity_month_year(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MaturityMonthYearField::new(String::new());
        self.message.body.get_field(tag::MATURITY_MONTH_YEAR, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MaturityMonthYear` is present, Tag 200.
    pub fn has_maturity_month_year(&self) -> bool {
        self.message.body.has(tag::MATURITY_MONTH_YEAR)
    }




    /// Sets `NoAffectedOrders`, Tag 534.
    pub fn set_no_affected_orders(&mut self, f: NoAffectedOrdersRepeatingGroup) {
        self.message.body.set_group(f.0);
    }

    /// Gets `NoAffectedOrders`, Tag 534.
    pub fn get_no_affected_orders(&self) -> Result<NoAffectedOrdersRepeatingGroup, MessageRejectErrorEnum> {
        let g = NoAffectedOrdersRepeatingGroup::new();
        Ok(NoAffectedOrdersRepeatingGroup(self.message.body.get_group(g.0)?))
    }


    /// Returns true if `NoAffectedOrders` is present, Tag 534.
    pub fn has_no_affected_orders(&self) -> bool {
        self.message.body.has(tag::NO_AFFECTED_ORDERS)
    }




    /// Sets `NoSecurityAltID`, Tag 454.
    pub fn set_no_security_alt_id(&mut self, f: NoSecurityAltIDRepeatingGroup) {
        self.message.body.set_group(f.0);
    }

    /// Gets `NoSecurityAltID`, Tag 454.
    pub fn get_no_security_alt_id(&self) -> Result<NoSecurityAltIDRepeatingGroup, MessageRejectErrorEnum> {
        let g = NoSecurityAltIDRepeatingGroup::new();
        Ok(NoSecurityAltIDRepeatingGroup(self.message.body.get_group(g.0)?))
    }


    /// Returns true if `NoSecurityAltID` is present, Tag 454.
    pub fn has_no_security_alt_id(&self) -> bool {
        self.message.body.has(tag::NO_SECURITY_ALT_ID)
    }




    /// Sets `NoUnderlyingSecurityAltID`, Tag 457.
    pub fn set_no_underlying_security_alt_id(&mut self, f: NoUnderlyingSecurityAltIDRepeatingGroup) {
        self.message.body.set_group(f.0);
    }

    /// Gets `NoUnderlyingSecurityAltID`, Tag 457.
    pub fn get_no_underlying_security_alt_id(&self) -> Result<NoUnderlyingSecurityAltIDRepeatingGroup, MessageRejectErrorEnum> {
        let g = NoUnderlyingSecurityAltIDRepeatingGroup::new();
        Ok(NoUnderlyingSecurityAltIDRepeatingGroup(self.message.body.get_group(g.0)?))
    }


    /// Returns true if `NoUnderlyingSecurityAltID` is present, Tag 457.
    pub fn has_no_underlying_security_alt_id(&self) -> bool {
        self.message.body.has(tag::NO_UNDERLYING_SECURITY_ALT_ID)
    }




    /// Sets `OptAttribute`, Tag 206.
    pub fn set_opt_attribute(&mut self, v: String) {
        self.message.body.set_field(tag::OPT_ATTRIBUTE, FIXString::from(v));
    }

    /// Gets `OptAttribute`, Tag 206.
    pub fn get_opt_attribute(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::OptAttributeField::new(String::new());
        self.message.body.get_field(tag::OPT_ATTRIBUTE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `OptAttribute` is present, Tag 206.
    pub fn has_opt_attribute(&self) -> bool {
        self.message.body.has(tag::OPT_ATTRIBUTE)
    }




    /// Sets `OrderID`, Tag 37.
    pub fn set_order_id(&mut self, v: String) {
        self.message.body.set_field(tag::ORDER_ID, FIXString::from(v));
    }

    /// Gets `OrderID`, Tag 37.
    pub fn get_order_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::OrderIDField::new(String::new());
        self.message.body.get_field(tag::ORDER_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `OrderID` is present, Tag 37.
    pub fn has_order_id(&self) -> bool {
        self.message.body.has(tag::ORDER_ID)
    }




    /// Sets `Product`, Tag 460.
    pub fn set_product(&mut self, v: isize) {
        self.message.body.set_field(tag::PRODUCT, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `Product`, Tag 460.
    pub fn get_product(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::ProductField::new(0);
        self.message.body.get_field(tag::PRODUCT, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Product` is present, Tag 460.
    pub fn has_product(&self) -> bool {
        self.message.body.has(tag::PRODUCT)
    }




    /// Sets `RedemptionDate`, Tag 240.
    pub fn set_redemption_date(&mut self, v: String) {
        self.message.body.set_field(tag::REDEMPTION_DATE, FIXString::from(v));
    }

    /// Gets `RedemptionDate`, Tag 240.
    pub fn get_redemption_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::RedemptionDateField::new(String::new());
        self.message.body.get_field(tag::REDEMPTION_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `RedemptionDate` is present, Tag 240.
    pub fn has_redemption_date(&self) -> bool {
        self.message.body.has(tag::REDEMPTION_DATE)
    }




    /// Sets `RepoCollateralSecurityType`, Tag 239.
    pub fn set_repo_collateral_security_type(&mut self, v: isize) {
        self.message.body.set_field(tag::REPO_COLLATERAL_SECURITY_TYPE, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `RepoCollateralSecurityType`, Tag 239.
    pub fn get_repo_collateral_security_type(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::RepoCollateralSecurityTypeField::new(0);
        self.message.body.get_field(tag::REPO_COLLATERAL_SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RepoCollateralSecurityType` is present, Tag 239.
    pub fn has_repo_collateral_security_type(&self) -> bool {
        self.message.body.has(tag::REPO_COLLATERAL_SECURITY_TYPE)
    }




    /// Sets `RepurchaseRate`, Tag 227.
    pub fn set_repurchase_rate(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::REPURCHASE_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `RepurchaseRate`, Tag 227.
    pub fn get_repurchase_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::RepurchaseRateField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::REPURCHASE_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RepurchaseRate` is present, Tag 227.
    pub fn has_repurchase_rate(&self) -> bool {
        self.message.body.has(tag::REPURCHASE_RATE)
    }




    /// Sets `RepurchaseTerm`, Tag 226.
    pub fn set_repurchase_term(&mut self, v: isize) {
        self.message.body.set_field(tag::REPURCHASE_TERM, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `RepurchaseTerm`, Tag 226.
    pub fn get_repurchase_term(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::RepurchaseTermField::new(0);
        self.message.body.get_field(tag::REPURCHASE_TERM, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RepurchaseTerm` is present, Tag 226.
    pub fn has_repurchase_term(&self) -> bool {
        self.message.body.has(tag::REPURCHASE_TERM)
    }




    /// Sets `SecondaryClOrdID`, Tag 526.
    pub fn set_secondary_cl_ord_id(&mut self, v: String) {
        self.message.body.set_field(tag::SECONDARY_CL_ORD_ID, FIXString::from(v));
    }

    /// Gets `SecondaryClOrdID`, Tag 526.
    pub fn get_secondary_cl_ord_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecondaryClOrdIDField::new(String::new());
        self.message.body.get_field(tag::SECONDARY_CL_ORD_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecondaryClOrdID` is present, Tag 526.
    pub fn has_secondary_cl_ord_id(&self) -> bool {
        self.message.body.has(tag::SECONDARY_CL_ORD_ID)
    }




    /// Sets `SecondaryOrderID`, Tag 198.
    pub fn set_secondary_order_id(&mut self, v: String) {
        self.message.body.set_field(tag::SECONDARY_ORDER_ID, FIXString::from(v));
    }

    /// Gets `SecondaryOrderID`, Tag 198.
    pub fn get_secondary_order_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecondaryOrderIDField::new(String::new());
        self.message.body.get_field(tag::SECONDARY_ORDER_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecondaryOrderID` is present, Tag 198.
    pub fn has_secondary_order_id(&self) -> bool {
        self.message.body.has(tag::SECONDARY_ORDER_ID)
    }




    /// Sets `SecurityDesc`, Tag 107.
    pub fn set_security_desc(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_DESC, FIXString::from(v));
    }

    /// Gets `SecurityDesc`, Tag 107.
    pub fn get_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityDescField::new(String::new());
        self.message.body.get_field(tag::SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityDesc` is present, Tag 107.
    pub fn has_security_desc(&self) -> bool {
        self.message.body.has(tag::SECURITY_DESC)
    }




    /// Sets `SecurityExchange`, Tag 207.
    pub fn set_security_exchange(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_EXCHANGE, FIXString::from(v));
    }

    /// Gets `SecurityExchange`, Tag 207.
    pub fn get_security_exchange(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityExchangeField::new(String::new());
        self.message.body.get_field(tag::SECURITY_EXCHANGE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityExchange` is present, Tag 207.
    pub fn has_security_exchange(&self) -> bool {
        self.message.body.has(tag::SECURITY_EXCHANGE)
    }




    /// Sets `SecurityID`, Tag 48.
    pub fn set_security_id(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_ID, FIXString::from(v));
    }

    /// Gets `SecurityID`, Tag 48.
    pub fn get_security_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityIDField::new(String::new());
        self.message.body.get_field(tag::SECURITY_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityID` is present, Tag 48.
    pub fn has_security_id(&self) -> bool {
        self.message.body.has(tag::SECURITY_ID)
    }




    /// Sets `SecurityIDSource`, Tag 22.
    pub fn set_security_id_source(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_ID_SOURCE, FIXString::from(v));
    }

    /// Gets `SecurityIDSource`, Tag 22.
    pub fn get_security_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityIDSourceField::new(String::new());
        self.message.body.get_field(tag::SECURITY_ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityIDSource` is present, Tag 22.
    pub fn has_security_id_source(&self) -> bool {
        self.message.body.has(tag::SECURITY_ID_SOURCE)
    }




    /// Sets `SecurityType`, Tag 167.
    pub fn set_security_type(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_TYPE, FIXString::from(v));
    }

    /// Gets `SecurityType`, Tag 167.
    pub fn get_security_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityTypeField::new(String::new());
        self.message.body.get_field(tag::SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityType` is present, Tag 167.
    pub fn has_security_type(&self) -> bool {
        self.message.body.has(tag::SECURITY_TYPE)
    }




    /// Sets `Side`, Tag 54.
    pub fn set_side(&mut self, v: String) {
        self.message.body.set_field(tag::SIDE, FIXString::from(v));
    }

    /// Gets `Side`, Tag 54.
    pub fn get_side(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SideField::new(String::new());
        self.message.body.get_field(tag::SIDE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Side` is present, Tag 54.
    pub fn has_side(&self) -> bool {
        self.message.body.has(tag::SIDE)
    }




    /// Sets `StateOrProvinceOfIssue`, Tag 471.
    pub fn set_state_or_province_of_issue(&mut self, v: String) {
        self.message.body.set_field(tag::STATE_OR_PROVINCE_OF_ISSUE, FIXString::from(v));
    }

    /// Gets `StateOrProvinceOfIssue`, Tag 471.
    pub fn get_state_or_province_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::StateOrProvinceOfIssueField::new(String::new());
        self.message.body.get_field(tag::STATE_OR_PROVINCE_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `StateOrProvinceOfIssue` is present, Tag 471.
    pub fn has_state_or_province_of_issue(&self) -> bool {
        self.message.body.has(tag::STATE_OR_PROVINCE_OF_ISSUE)
    }




    /// Sets `StrikePrice`, Tag 202.
    pub fn set_strike_price(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::STRIKE_PRICE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `StrikePrice`, Tag 202.
    pub fn get_strike_price(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::StrikePriceField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::STRIKE_PRICE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `StrikePrice` is present, Tag 202.
    pub fn has_strike_price(&self) -> bool {
        self.message.body.has(tag::STRIKE_PRICE)
    }




    /// Sets `Symbol`, Tag 55.
    pub fn set_symbol(&mut self, v: String) {
        self.message.body.set_field(tag::SYMBOL, FIXString::from(v));
    }

    /// Gets `Symbol`, Tag 55.
    pub fn get_symbol(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolField::new(String::new());
        self.message.body.get_field(tag::SYMBOL, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Symbol` is present, Tag 55.
    pub fn has_symbol(&self) -> bool {
        self.message.body.has(tag::SYMBOL)
    }




    /// Sets `SymbolSfx`, Tag 65.
    pub fn set_symbol_sfx(&mut self, v: String) {
        self.message.body.set_field(tag::SYMBOL_SFX, FIXString::from(v));
    }

    /// Gets `SymbolSfx`, Tag 65.
    pub fn get_symbol_sfx(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolSfxField::new(String::new());
        self.message.body.get_field(tag::SYMBOL_SFX, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SymbolSfx` is present, Tag 65.
    pub fn has_symbol_sfx(&self) -> bool {
        self.message.body.has(tag::SYMBOL_SFX)
    }




    /// Sets `Text`, Tag 58.
    pub fn set_text(&mut self, v: String) {
        self.message.body.set_field(tag::TEXT, FIXString::from(v));
    }

    /// Gets `Text`, Tag 58.
    pub fn get_text(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TextField::new(String::new());
        self.message.body.get_field(tag::TEXT, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Text` is present, Tag 58.
    pub fn has_text(&self) -> bool {
        self.message.body.has(tag::TEXT)
    }




    /// Sets `TotalAffectedOrders`, Tag 533.
    pub fn set_total_affected_orders(&mut self, v: isize) {
        self.message.body.set_field(tag::TOTAL_AFFECTED_ORDERS, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `TotalAffectedOrders`, Tag 533.
    pub fn get_total_affected_orders(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::TotalAffectedOrdersField::new(0);
        self.message.body.get_field(tag::TOTAL_AFFECTED_ORDERS, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `TotalAffectedOrders` is present, Tag 533.
    pub fn has_total_affected_orders(&self) -> bool {
        self.message.body.has(tag::TOTAL_AFFECTED_ORDERS)
    }




    /// Sets `TradingSessionID`, Tag 336.
    pub fn set_trading_session_id(&mut self, v: String) {
        self.message.body.set_field(tag::TRADING_SESSION_ID, FIXString::from(v));
    }

    /// Gets `TradingSessionID`, Tag 336.
    pub fn get_trading_session_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TradingSessionIDField::new(String::new());
        self.message.body.get_field(tag::TRADING_SESSION_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `TradingSessionID` is present, Tag 336.
    pub fn has_trading_session_id(&self) -> bool {
        self.message.body.has(tag::TRADING_SESSION_ID)
    }




    /// Sets `TradingSessionSubID`, Tag 625.
    pub fn set_trading_session_sub_id(&mut self, v: String) {
        self.message.body.set_field(tag::TRADING_SESSION_SUB_ID, FIXString::from(v));
    }

    /// Gets `TradingSessionSubID`, Tag 625.
    pub fn get_trading_session_sub_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TradingSessionSubIDField::new(String::new());
        self.message.body.get_field(tag::TRADING_SESSION_SUB_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `TradingSessionSubID` is present, Tag 625.
    pub fn has_trading_session_sub_id(&self) -> bool {
        self.message.body.has(tag::TRADING_SESSION_SUB_ID)
    }




    /// Sets `TransactTime`, Tag 60.
    pub fn set_transact_time(&mut self, v: Timestamp) {
        self.message.body.set_field(tag::TRANSACT_TIME, fixer::fix_utc_timestamp::FIXUTCTimestamp {
            time: v,
            precision: fixer::fix_utc_timestamp::TimestampPrecision::Millis,
        });
    }

    /// Gets `TransactTime`, Tag 60.
    pub fn get_transact_time(&self) -> Result<Timestamp, MessageRejectErrorEnum> {
        let mut fld = field::TransactTimeField::new(Timestamp::UNIX_EPOCH);
        self.message.body.get_field(tag::TRANSACT_TIME, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `TransactTime` is present, Tag 60.
    pub fn has_transact_time(&self) -> bool {
        self.message.body.has(tag::TRANSACT_TIME)
    }




    /// Sets `UnderlyingCFICode`, Tag 463.
    pub fn set_underlying_cfi_code(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_CFI_CODE, FIXString::from(v));
    }

    /// Gets `UnderlyingCFICode`, Tag 463.
    pub fn get_underlying_cfi_code(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingCFICodeField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_CFI_CODE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingCFICode` is present, Tag 463.
    pub fn has_underlying_cfi_code(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_CFI_CODE)
    }




    /// Sets `UnderlyingContractMultiplier`, Tag 436.
    pub fn set_underlying_contract_multiplier(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::UNDERLYING_CONTRACT_MULTIPLIER, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `UnderlyingContractMultiplier`, Tag 436.
    pub fn get_underlying_contract_multiplier(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingContractMultiplierField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::UNDERLYING_CONTRACT_MULTIPLIER, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingContractMultiplier` is present, Tag 436.
    pub fn has_underlying_contract_multiplier(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_CONTRACT_MULTIPLIER)
    }




    /// Sets `UnderlyingCountryOfIssue`, Tag 592.
    pub fn set_underlying_country_of_issue(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_COUNTRY_OF_ISSUE, FIXString::from(v));
    }

    /// Gets `UnderlyingCountryOfIssue`, Tag 592.
    pub fn get_underlying_country_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingCountryOfIssueField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_COUNTRY_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingCountryOfIssue` is present, Tag 592.
    pub fn has_underlying_country_of_issue(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_COUNTRY_OF_ISSUE)
    }




    /// Sets `UnderlyingCouponPaymentDate`, Tag 241.
    pub fn set_underlying_coupon_payment_date(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_COUPON_PAYMENT_DATE, FIXString::from(v));
    }

    /// Gets `UnderlyingCouponPaymentDate`, Tag 241.
    pub fn get_underlying_coupon_payment_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingCouponPaymentDateField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_COUPON_PAYMENT_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingCouponPaymentDate` is present, Tag 241.
    pub fn has_underlying_coupon_payment_date(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_COUPON_PAYMENT_DATE)
    }




    /// Sets `UnderlyingCouponRate`, Tag 435.
    pub fn set_underlying_coupon_rate(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::UNDERLYING_COUPON_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `UnderlyingCouponRate`, Tag 435.
    pub fn get_underlying_coupon_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingCouponRateField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::UNDERLYING_COUPON_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingCouponRate` is present, Tag 435.
    pub fn has_underlying_coupon_rate(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_COUPON_RATE)
    }




    /// Sets `UnderlyingCreditRating`, Tag 256.
    pub fn set_underlying_credit_rating(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_CREDIT_RATING, FIXString::from(v));
    }

    /// Gets `UnderlyingCreditRating`, Tag 256.
    pub fn get_underlying_credit_rating(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingCreditRatingField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_CREDIT_RATING, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingCreditRating` is present, Tag 256.
    pub fn has_underlying_credit_rating(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_CREDIT_RATING)
    }




    /// Sets `UnderlyingFactor`, Tag 246.
    pub fn set_underlying_factor(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::UNDERLYING_FACTOR, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `UnderlyingFactor`, Tag 246.
    pub fn get_underlying_factor(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingFactorField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::UNDERLYING_FACTOR, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingFactor` is present, Tag 246.
    pub fn has_underlying_factor(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_FACTOR)
    }




    /// Sets `UnderlyingInstrRegistry`, Tag 595.
    pub fn set_underlying_instr_registry(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_INSTR_REGISTRY, FIXString::from(v));
    }

    /// Gets `UnderlyingInstrRegistry`, Tag 595.
    pub fn get_underlying_instr_registry(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingInstrRegistryField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_INSTR_REGISTRY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingInstrRegistry` is present, Tag 595.
    pub fn has_underlying_instr_registry(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_INSTR_REGISTRY)
    }




    /// Sets `UnderlyingIssueDate`, Tag 242.
    pub fn set_underlying_issue_date(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_ISSUE_DATE, FIXString::from(v));
    }

    /// Gets `UnderlyingIssueDate`, Tag 242.
    pub fn get_underlying_issue_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingIssueDateField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_ISSUE_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingIssueDate` is present, Tag 242.
    pub fn has_underlying_issue_date(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_ISSUE_DATE)
    }




    /// Sets `UnderlyingIssuer`, Tag 306.
    pub fn set_underlying_issuer(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_ISSUER, FIXString::from(v));
    }

    /// Gets `UnderlyingIssuer`, Tag 306.
    pub fn get_underlying_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingIssuerField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingIssuer` is present, Tag 306.
    pub fn has_underlying_issuer(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_ISSUER)
    }




    /// Sets `UnderlyingLocaleOfIssue`, Tag 594.
    pub fn set_underlying_locale_of_issue(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_LOCALE_OF_ISSUE, FIXString::from(v));
    }

    /// Gets `UnderlyingLocaleOfIssue`, Tag 594.
    pub fn get_underlying_locale_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingLocaleOfIssueField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_LOCALE_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingLocaleOfIssue` is present, Tag 594.
    pub fn has_underlying_locale_of_issue(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_LOCALE_OF_ISSUE)
    }




    /// Sets `UnderlyingMaturityDate`, Tag 542.
    pub fn set_underlying_maturity_date(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_MATURITY_DATE, FIXString::from(v));
    }

    /// Gets `UnderlyingMaturityDate`, Tag 542.
    pub fn get_underlying_maturity_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingMaturityDateField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_MATURITY_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingMaturityDate` is present, Tag 542.
    pub fn has_underlying_maturity_date(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_MATURITY_DATE)
    }




    /// Sets `UnderlyingMaturityMonthYear`, Tag 313.
    pub fn set_underlying_maturity_month_year(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_MATURITY_MONTH_YEAR, FIXString::from(v));
    }

    /// Gets `UnderlyingMaturityMonthYear`, Tag 313.
    pub fn get_underlying_maturity_month_year(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingMaturityMonthYearField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_MATURITY_MONTH_YEAR, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingMaturityMonthYear` is present, Tag 313.
    pub fn has_underlying_maturity_month_year(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_MATURITY_MONTH_YEAR)
    }




    /// Sets `UnderlyingOptAttribute`, Tag 317.
    pub fn set_underlying_opt_attribute(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_OPT_ATTRIBUTE, FIXString::from(v));
    }

    /// Gets `UnderlyingOptAttribute`, Tag 317.
    pub fn get_underlying_opt_attribute(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingOptAttributeField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_OPT_ATTRIBUTE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingOptAttribute` is present, Tag 317.
    pub fn has_underlying_opt_attribute(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_OPT_ATTRIBUTE)
    }




    /// Sets `UnderlyingProduct`, Tag 462.
    pub fn set_underlying_product(&mut self, v: isize) {
        self.message.body.set_field(tag::UNDERLYING_PRODUCT, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `UnderlyingProduct`, Tag 462.
    pub fn get_underlying_product(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingProductField::new(0);
        self.message.body.get_field(tag::UNDERLYING_PRODUCT, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingProduct` is present, Tag 462.
    pub fn has_underlying_product(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_PRODUCT)
    }




    /// Sets `UnderlyingRedemptionDate`, Tag 247.
    pub fn set_underlying_redemption_date(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_REDEMPTION_DATE, FIXString::from(v));
    }

    /// Gets `UnderlyingRedemptionDate`, Tag 247.
    pub fn get_underlying_redemption_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingRedemptionDateField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_REDEMPTION_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingRedemptionDate` is present, Tag 247.
    pub fn has_underlying_redemption_date(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_REDEMPTION_DATE)
    }




    /// Sets `UnderlyingRepoCollateralSecurityType`, Tag 243.
    pub fn set_underlying_repo_collateral_security_type(&mut self, v: isize) {
        self.message.body.set_field(tag::UNDERLYING_REPO_COLLATERAL_SECURITY_TYPE, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `UnderlyingRepoCollateralSecurityType`, Tag 243.
    pub fn get_underlying_repo_collateral_security_type(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingRepoCollateralSecurityTypeField::new(0);
        self.message.body.get_field(tag::UNDERLYING_REPO_COLLATERAL_SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingRepoCollateralSecurityType` is present, Tag 243.
    pub fn has_underlying_repo_collateral_security_type(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_REPO_COLLATERAL_SECURITY_TYPE)
    }




    /// Sets `UnderlyingRepurchaseRate`, Tag 245.
    pub fn set_underlying_repurchase_rate(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::UNDERLYING_REPURCHASE_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `UnderlyingRepurchaseRate`, Tag 245.
    pub fn get_underlying_repurchase_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingRepurchaseRateField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::UNDERLYING_REPURCHASE_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingRepurchaseRate` is present, Tag 245.
    pub fn has_underlying_repurchase_rate(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_REPURCHASE_RATE)
    }




    /// Sets `UnderlyingRepurchaseTerm`, Tag 244.
    pub fn set_underlying_repurchase_term(&mut self, v: isize) {
        self.message.body.set_field(tag::UNDERLYING_REPURCHASE_TERM, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `UnderlyingRepurchaseTerm`, Tag 244.
    pub fn get_underlying_repurchase_term(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingRepurchaseTermField::new(0);
        self.message.body.get_field(tag::UNDERLYING_REPURCHASE_TERM, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingRepurchaseTerm` is present, Tag 244.
    pub fn has_underlying_repurchase_term(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_REPURCHASE_TERM)
    }




    /// Sets `UnderlyingSecurityDesc`, Tag 307.
    pub fn set_underlying_security_desc(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_SECURITY_DESC, FIXString::from(v));
    }

    /// Gets `UnderlyingSecurityDesc`, Tag 307.
    pub fn get_underlying_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSecurityDescField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSecurityDesc` is present, Tag 307.
    pub fn has_underlying_security_desc(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_SECURITY_DESC)
    }




    /// Sets `UnderlyingSecurityExchange`, Tag 308.
    pub fn set_underlying_security_exchange(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_SECURITY_EXCHANGE, FIXString::from(v));
    }

    /// Gets `UnderlyingSecurityExchange`, Tag 308.
    pub fn get_underlying_security_exchange(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSecurityExchangeField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_SECURITY_EXCHANGE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSecurityExchange` is present, Tag 308.
    pub fn has_underlying_security_exchange(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_SECURITY_EXCHANGE)
    }




    /// Sets `UnderlyingSecurityID`, Tag 309.
    pub fn set_underlying_security_id(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_SECURITY_ID, FIXString::from(v));
    }

    /// Gets `UnderlyingSecurityID`, Tag 309.
    pub fn get_underlying_security_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSecurityIDField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_SECURITY_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSecurityID` is present, Tag 309.
    pub fn has_underlying_security_id(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_SECURITY_ID)
    }




    /// Sets `UnderlyingSecurityIDSource`, Tag 305.
    pub fn set_underlying_security_id_source(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_SECURITY_ID_SOURCE, FIXString::from(v));
    }

    /// Gets `UnderlyingSecurityIDSource`, Tag 305.
    pub fn get_underlying_security_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSecurityIDSourceField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_SECURITY_ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSecurityIDSource` is present, Tag 305.
    pub fn has_underlying_security_id_source(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_SECURITY_ID_SOURCE)
    }




    /// Sets `UnderlyingSecurityType`, Tag 310.
    pub fn set_underlying_security_type(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_SECURITY_TYPE, FIXString::from(v));
    }

    /// Gets `UnderlyingSecurityType`, Tag 310.
    pub fn get_underlying_security_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSecurityTypeField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSecurityType` is present, Tag 310.
    pub fn has_underlying_security_type(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_SECURITY_TYPE)
    }




    /// Sets `UnderlyingStateOrProvinceOfIssue`, Tag 593.
    pub fn set_underlying_state_or_province_of_issue(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_STATE_OR_PROVINCE_OF_ISSUE, FIXString::from(v));
    }

    /// Gets `UnderlyingStateOrProvinceOfIssue`, Tag 593.
    pub fn get_underlying_state_or_province_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingStateOrProvinceOfIssueField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_STATE_OR_PROVINCE_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingStateOrProvinceOfIssue` is present, Tag 593.
    pub fn has_underlying_state_or_province_of_issue(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_STATE_OR_PROVINCE_OF_ISSUE)
    }




    /// Sets `UnderlyingStrikePrice`, Tag 316.
    pub fn set_underlying_strike_price(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::UNDERLYING_STRIKE_PRICE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `UnderlyingStrikePrice`, Tag 316.
    pub fn get_underlying_strike_price(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingStrikePriceField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::UNDERLYING_STRIKE_PRICE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `UnderlyingStrikePrice` is present, Tag 316.
    pub fn has_underlying_strike_price(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_STRIKE_PRICE)
    }




    /// Sets `UnderlyingSymbol`, Tag 311.
    pub fn set_underlying_symbol(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_SYMBOL, FIXString::from(v));
    }

    /// Gets `UnderlyingSymbol`, Tag 311.
    pub fn get_underlying_symbol(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSymbolField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_SYMBOL, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSymbol` is present, Tag 311.
    pub fn has_underlying_symbol(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_SYMBOL)
    }




    /// Sets `UnderlyingSymbolSfx`, Tag 312.
    pub fn set_underlying_symbol_sfx(&mut self, v: String) {
        self.message.body.set_field(tag::UNDERLYING_SYMBOL_SFX, FIXString::from(v));
    }

    /// Gets `UnderlyingSymbolSfx`, Tag 312.
    pub fn get_underlying_symbol_sfx(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSymbolSfxField::new(String::new());
        self.message.body.get_field(tag::UNDERLYING_SYMBOL_SFX, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSymbolSfx` is present, Tag 312.
    pub fn has_underlying_symbol_sfx(&self) -> bool {
        self.message.body.has(tag::UNDERLYING_SYMBOL_SFX)
    }


}

/// `RouteOut` is the callback type for routing `OrderMassCancelReport` messages.
pub type RouteOut = fn(msg: OrderMassCancelReport, session_id: SessionID) -> Result<(), MessageRejectErrorEnum>;

/// Route type returned by the `route` function.
pub type Route = (&'static str, &'static str, Box<dyn Fn(&Message, SessionID) -> Result<(), MessageRejectErrorEnum> + Send>);

/// Returns the begin string, message type, and route function for `OrderMassCancelReport`.
pub fn route(router: RouteOut) -> Route {
    let r = move |msg: &Message, session_id: SessionID| -> Result<(), MessageRejectErrorEnum> {
        router(OrderMassCancelReport::from_message(msg.clone()), session_id)
    };
    ("FIX.4.3", "r", Box::new(r))
}


/// `NoAffectedOrders` is an entry in the `NoAffectedOrders` repeating group, Tag 534.
pub struct NoAffectedOrders<G>(pub G);

impl<G: Borrow<Group>> NoAffectedOrders<G> {
    fn group(&self) -> &Group {
        self.0.borrow()
    }



    /// Gets `OrigClOrdID`, Tag 41.
    pub fn get_orig_cl_ord_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::OrigClOrdIDField::new(String::new());
        self.group().field_map.get_field(tag::ORIG_CL_ORD_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `OrigClOrdID` is present, Tag 41.
    pub fn has_orig_cl_ord_id(&self) -> bool {
        self.group().field_map.has(tag::ORIG_CL_ORD_ID)
    }




    /// Gets `AffectedOrderID`, Tag 535.
    pub fn get_affected_order_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::AffectedOrderIDField::new(String::new());
        self.group().field_map.get_field(tag::AFFECTED_ORDER_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `AffectedOrderID` is present, Tag 535.
    pub fn has_affected_order_id(&self) -> bool {
        self.group().field_map.has(tag::AFFECTED_ORDER_ID)
    }




    /// Gets `AffectedSecondaryOrderID`, Tag 536.
    pub fn get_affected_secondary_order_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::AffectedSecondaryOrderIDField::new(String::new());
        self.group().field_map.get_field(tag::AFFECTED_SECONDARY_ORDER_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `AffectedSecondaryOrderID` is present, Tag 536.
    pub fn has_affected_secondary_order_id(&self) -> bool {
        self.group().field_map.has(tag::AFFECTED_SECONDARY_ORDER_ID)
    }


}

impl<G: BorrowMut<Group>> NoAffectedOrders<G> {
    fn group_mut(&mut self) -> &mut Group {
        self.0.borrow_mut()
    }



    /// Sets `OrigClOrdID`, Tag 41.
    pub fn set_orig_cl_ord_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ORIG_CL_ORD_ID, FIXString::from(v));
    }





    /// Sets `AffectedOrderID`, Tag 535.
    pub fn set_affected_order_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::AFFECTED_ORDER_ID, FIXString::from(v));
    }





    /// Sets `AffectedSecondaryOrderID`, Tag 536.
    pub fn set_affected_secondary_order_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::AFFECTED_SECONDARY_ORDER_ID, FIXString::from(v));
    }



}

/// `NoAffectedOrdersRepeatingGroup` is the `NoAffectedOrders` repeating group, Tag 534.
pub struct NoAffectedOrdersRepeatingGroup(pub RepeatingGroup);

impl NoAffectedOrdersRepeatingGroup {
    /// Creates an empty `NoAffectedOrders` group with the template from the FIX spec.
    pub fn new() -> Self {
        let template: GroupTemplate = vec![


            group_element(tag::ORIG_CL_ORD_ID),



            group_element(tag::AFFECTED_ORDER_ID),



            group_element(tag::AFFECTED_SECONDARY_ORDER_ID),


        ];
        Self(RepeatingGroup::new(tag::NO_AFFECTED_ORDERS, template))
    }

    /// Appends an entry and returns it for population.
    pub fn add(&mut self) -> NoAffectedOrders<&mut Group> {
        NoAffectedOrders(self.0.add())
    }

    /// Returns the `i`th entry.
    pub fn get(&self, i: usize) -> NoAffectedOrders<&Group> {
        NoAffectedOrders(self.0.get(i))
    }

    /// Returns the number of entries.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns true if the group has no entries.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl Default for NoAffectedOrdersRepeatingGroup {
    fn default() -> Self {
        Self::new()
    }
}



/// `NoSecurityAltID` is an entry in the `NoSecurityAltID` repeating group, Tag 454.
pub struct NoSecurityAltID<G>(pub G);

impl<G: Borrow<Group>> NoSecurityAltID<G> {
    fn group(&self) -> &Group {
        self.0.borrow()
    }



    /// Gets `SecurityAltID`, Tag 455.
    pub fn get_security_alt_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityAltIDField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_ALT_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityAltID` is present, Tag 455.
    pub fn has_security_alt_id(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_ALT_ID)
    }




    /// Gets `SecurityAltIDSource`, Tag 456.
    pub fn get_security_alt_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityAltIDSourceField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_ALT_ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityAltIDSource` is present, Tag 456.
    pub fn has_security_alt_id_source(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_ALT_ID_SOURCE)
    }


}

impl<G: BorrowMut<Group>> NoSecurityAltID<G> {
    fn group_mut(&mut self) -> &mut Group {
        self.0.borrow_mut()
    }



    /// Sets `SecurityAltID`, Tag 455.
    pub fn set_security_alt_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_ALT_ID, FIXString::from(v));
    }





    /// Sets `SecurityAltIDSource`, Tag 456.
    pub fn set_security_alt_id_source(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_ALT_ID_SOURCE, FIXString::from(v));
    }



}

/// `NoSecurityAltIDRepeatingGroup` is the `NoSecurityAltID` repeating group, Tag 454.
pub struct NoSecurityAltIDRepeatingGroup(pub RepeatingGroup);

impl NoSecurityAltIDRepeatingGroup {
    /// Creates an empty `NoSecurityAltID` group with the template from the FIX spec.
    pub fn new() -> Self {
        let template: GroupTemplate = vec![


            group_element(tag::SECURITY_ALT_ID),



            group_element(tag::SECURITY_ALT_ID_SOURCE),


        ];
        Self(RepeatingGroup::new(tag::NO_SECURITY_ALT_ID, template))
    }

    /// Appends an entry and returns it for population.
    pub fn add(&mut self) -> NoSecurityAltID<&mut Group> {
        NoSecurityAltID(self.0.add())
    }

    /// Returns the `i`th entry.
    pub fn get(&self, i: usize) -> NoSecurityAltID<&Group> {
        NoSecurityAltID(self.0.get(i))
    }

    /// Returns the number of entries.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns true if the group has no entries.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl Default for NoSecurityAltIDRepeatingGroup {
    fn default() -> Self {
        Self::new()
    }
}



/// `NoUnderlyingSecurityAltID` is an entry in the `NoUnderlyingSecurityAltID` repeating group, Tag 457.
pub struct NoUnderlyingSecurityAltID<G>(pub G);

impl<G: Borrow<Group>> NoUnderlyingSecurityAltID<G> {
    fn group(&self) -> &Group {
        self.0.borrow()
    }



    /// Gets `UnderlyingSecurityAltID`, Tag 458.
    pub fn get_underlying_security_alt_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSecurityAltIDField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_SECURITY_ALT_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSecurityAltID` is present, Tag 458.
    pub fn has_underlying_security_alt_id(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_SECURITY_ALT_ID)
    }




    /// Gets `UnderlyingSecurityAltIDSource`, Tag 459.
    pub fn get_underlying_security_alt_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::UnderlyingSecurityAltIDSourceField::new(String::new());
        self.group().field_map.get_field(tag::UNDERLYING_SECURITY_ALT_ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `UnderlyingSecurityAltIDSource` is present, Tag 459.
    pub fn has_underlying_security_alt_id_source(&self) -> bool {
        self.group().field_map.has(tag::UNDERLYING_SECURITY_ALT_ID_SOURCE)
    }


}

impl<G: BorrowMut<Group>> NoUnderlyingSecurityAltID<G> {
    fn group_mut(&mut self) -> &mut Group {
        self.0.borrow_mut()
    }



    /// Sets `UnderlyingSecurityAltID`, Tag 458.
    pub fn set_underlying_security_alt_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_SECURITY_ALT_ID, FIXString::from(v));
    }





    /// Sets `UnderlyingSecurityAltIDSource`, Tag 459.
    pub fn set_underlying_security_alt_id_source(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::UNDERLYING_SECURITY_ALT_ID_SOURCE, FIXString::from(v));
    }



}

/// `NoUnderlyingSecurityAltIDRepeatingGroup` is the `NoUnderlyingSecurityAltID` repeating group, Tag 457.
pub struct NoUnderlyingSecurityAltIDRepeatingGroup(pub RepeatingGroup);

impl NoUnderlyingSecurityAltIDRepeatingGroup {
    /// Creates an empty `NoUnderlyingSecurityAltID` group with the template from the FIX spec.
    pub fn new() -> Self {
        let template: GroupTemplate = vec![


            group_element(tag::UNDERLYING_SECURITY_ALT_ID),



            group_element(tag::UNDERLYING_SECURITY_ALT_ID_SOURCE),


        ];
        Self(RepeatingGroup::new(tag::NO_UNDERLYING_SECURITY_ALT_ID, template))
    }

    /// Appends an entry and returns it for population.
    pub fn add(&mut self) -> NoUnderlyingSecurityAltID<&mut Group> {
        NoUnderlyingSecurityAltID(self.0.add())
    }

    /// Returns the `i`th entry.
    pub fn get(&self, i: usize) -> NoUnderlyingSecurityAltID<&Group> {
        NoUnderlyingSecurityAltID(self.0.get(i))
    }

    /// Returns the number of entries.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns true if the group has no entries.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl Default for NoUnderlyingSecurityAltIDRepeatingGroup {
    fn default() -> Self {
        Self::new()
    }
}

