// Code generated by fixer-gen. DO NOT EDIT.
#![allow(clippy::new_without_default)]
#![allow(clippy::needless_pass_by_value)]
#![allow(clippy::too_many_arguments)]
#![allow(unused_imports)]

use fixer::message::Message;
use fixer::fix_string::FIXString;
use fixer::errors::MessageRejectErrorEnum;
use fixer::session::session_id::SessionID;
use fixer::repeating_group::{Group, GroupTemplate, RepeatingGroup, group_element};
use std::borrow::{Borrow, BorrowMut};

use rust_decimal::Decimal;


use crate::field;
use crate::tag;

/// `QuoteCancel` is the `fix43` `QuoteCancel` type, `MsgType` = Z.
pub struct QuoteCancel {
    pub message: Message,
}

impl QuoteCancel {
    /// Creates a new `QuoteCancel` with required fields.
    pub fn new(quote_id: field::QuoteIDField, quote_cancel_type: field::QuoteCancelTypeField) -> Self {
        let mut msg = Message::new();
        msg.header.set_field(tag::MSG_TYPE, FIXString::from("Z".to_string()));

        msg.body.set_field(tag::QUOTE_ID, quote_id.0);

        msg.body.set_field(tag::QUOTE_CANCEL_TYPE, quote_cancel_type.0);

        Self { message: msg }
    }

    /// Creates a `QuoteCancel` from an existing `Message`.
    pub fn from_message(msg: Message) -> Self {
        Self { message: msg }
    }

    /// Returns the underlying `Message`.
    pub fn to_message(self) -> Message {
        self.message
    }




    /// Sets `Account`, Tag 1.
    pub fn set_account(&mut self, v: String) {
        self.message.body.set_field(tag::ACCOUNT, FIXString::from(v));
    }

    /// Gets `Account`, Tag 1.
    pub fn get_account(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::AccountField::new(String::new());
        self.message.body.get_field(tag::ACCOUNT, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Account` is present, Tag 1.
    pub fn has_account(&self) -> bool {
        self.message.body.has(tag::ACCOUNT)
    }




    /// Sets `AccountType`, Tag 581.
    pub fn set_account_type(&mut self, v: isize) {
        self.message.body.set_field(tag::ACCOUNT_TYPE, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `AccountType`, Tag 581.
    pub fn get_account_type(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::AccountTypeField::new(0);
        self.message.body.get_field(tag::ACCOUNT_TYPE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `AccountType` is present, Tag 581.
    pub fn has_account_type(&self) -> bool {
        self.message.body.has(tag::ACCOUNT_TYPE)
    }




    /// Sets `NoPartyIDs`, Tag 453.
    pub fn set_no_party_i_ds(&mut self, f: NoPartyIDsRepeatingGroup) {
        self.message.body.set_group(f.0);
    }

    /// Gets `NoPartyIDs`, Tag 453.
    pub fn get_no_party_i_ds(&self) -> Result<NoPartyIDsRepeatingGroup, MessageRejectErrorEnum> {
        let g = NoPartyIDsRepeatingGroup::new();
        Ok(NoPartyIDsRepeatingGroup(self.message.body.get_group(g.0)?))
    }


    /// Returns true if `NoPartyIDs` is present, Tag 453.
    pub fn has_no_party_i_ds(&self) -> bool {
        self.message.body.has(tag::NO_PARTY_I_DS)
    }




    /// Sets `NoQuoteEntries`, Tag 295.
    pub fn set_no_quote_entries(&mut self, f: NoQuoteEntriesRepeatingGroup) {
        self.message.body.set_group(f.0);
    }

    /// Gets `NoQuoteEntries`, Tag 295.
    pub fn get_no_quote_entries(&self) -> Result<NoQuoteEntriesRepeatingGroup, MessageRejectErrorEnum> {
        let g = NoQuoteEntriesRepeatingGroup::new();
        Ok(NoQuoteEntriesRepeatingGroup(self.message.body.get_group(g.0)?))
    }


    /// Returns true if `NoQuoteEntries` is present, Tag 295.
    pub fn has_no_quote_entries(&self) -> bool {
        self.message.body.has(tag::NO_QUOTE_ENTRIES)
    }




    /// Sets `QuoteCancelType`, Tag 298.
    pub fn set_quote_cancel_type(&mut self, v: isize) {
        self.message.body.set_field(tag::QUOTE_CANCEL_TYPE, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `QuoteCancelType`, Tag 298.
    pub fn get_quote_cancel_type(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::QuoteCancelTypeField::new(0);
        self.message.body.get_field(tag::QUOTE_CANCEL_TYPE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `QuoteCancelType` is present, Tag 298.
    pub fn has_quote_cancel_type(&self) -> bool {
        self.message.body.has(tag::QUOTE_CANCEL_TYPE)
    }




    /// Sets `QuoteID`, Tag 117.
    pub fn set_quote_id(&mut self, v: String) {
        self.message.body.set_field(tag::QUOTE_ID, FIXString::from(v));
    }

    /// Gets `QuoteID`, Tag 117.
    pub fn get_quote_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::QuoteIDField::new(String::new());
        self.message.body.get_field(tag::QUOTE_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `QuoteID` is present, Tag 117.
    pub fn has_quote_id(&self) -> bool {
        self.message.body.has(tag::QUOTE_ID)
    }




    /// Sets `QuoteReqID`, Tag 131.
    pub fn set_quote_req_id(&mut self, v: String) {
        self.message.body.set_field(tag::QUOTE_REQ_ID, FIXString::from(v));
    }

    /// Gets `QuoteReqID`, Tag 131.
    pub fn get_quote_req_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::QuoteReqIDField::new(String::new());
        self.message.body.get_field(tag::QUOTE_REQ_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `QuoteReqID` is present, Tag 131.
    pub fn has_quote_req_id(&self) -> bool {
        self.message.body.has(tag::QUOTE_REQ_ID)
    }




    /// Sets `QuoteResponseLevel`, Tag 301.
    pub fn set_quote_response_level(&mut self, v: isize) {
        self.message.body.set_field(tag::QUOTE_RESPONSE_LEVEL, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `QuoteResponseLevel`, Tag 301.
    pub fn get_quote_response_level(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::QuoteResponseLevelField::new(0);
        self.message.body.get_field(tag::QUOTE_RESPONSE_LEVEL, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `QuoteResponseLevel` is present, Tag 301.
    pub fn has_quote_response_level(&self) -> bool {
        self.message.body.has(tag::QUOTE_RESPONSE_LEVEL)
    }




    /// Sets `TradingSessionID`, Tag 336.
    pub fn set_trading_session_id(&mut self, v: String) {
        self.message.body.set_field(tag::TRADING_SESSION_ID, FIXString::from(v));
    }

    /// Gets `TradingSessionID`, Tag 336.
    pub fn get_trading_session_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TradingSessionIDField::new(String::new());
        self.message.body.get_field(tag::TRADING_SESSION_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `TradingSessionID` is present, Tag 336.
    pub fn has_trading_session_id(&self) -> bool {
        self.message.body.has(tag::TRADING_SESSION_ID)
    }




    /// Sets `TradingSessionSubID`, Tag 625.
    pub fn set_trading_session_sub_id(&mut self, v: String) {
        self.message.body.set_field(tag::TRADING_SESSION_SUB_ID, FIXString::from(v));
    }

    /// Gets `TradingSessionSubID`, Tag 625.
    pub fn get_trading_session_sub_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TradingSessionSubIDField::new(String::new());
        self.message.body.get_field(tag::TRADING_SESSION_SUB_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `TradingSessionSubID` is present, Tag 625.
    pub fn has_trading_session_sub_id(&self) -> bool {
        self.message.body.has(tag::TRADING_SESSION_SUB_ID)
    }


}

/// `RouteOut` is the callback type for routing `QuoteCancel` messages.
pub type RouteOut = fn(msg: QuoteCancel, session_id: SessionID) -> Result<(), MessageRejectErrorEnum>;

/// Route type returned by the `route` function.
pub type Route = (&'static str, &'static str, Box<dyn Fn(&Message, SessionID) -> Result<(), MessageRejectErrorEnum> + Send>);

/// Returns the begin string, message type, and route function for `QuoteCancel`.
pub fn route(router: RouteOut) -> Route {
    let r = move |msg: &Message, session_id: SessionID| -> Result<(), MessageRejectErrorEnum> {
        router(QuoteCancel::from_message(msg.clone()), session_id)
    };
    ("FIX.4.3", "Z", Box::new(r))
}


/// `NoPartyIDs` is an entry in the `NoPartyIDs` repeating group, Tag 453.
pub struct NoPartyIDs<G>(pub G);

impl<G: Borrow<Group>> NoPartyIDs<G> {
    fn group(&self) -> &Group {
        self.0.borrow()
    }



    /// Gets `PartyID`, Tag 448.
    pub fn get_party_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::PartyIDField::new(String::new());
        self.group().field_map.get_field(tag::PARTY_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `PartyID` is present, Tag 448.
    pub fn has_party_id(&self) -> bool {
        self.group().field_map.has(tag::PARTY_ID)
    }




    /// Gets `PartyIDSource`, Tag 447.
    pub fn get_party_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::PartyIDSourceField::new(String::new());
        self.group().field_map.get_field(tag::PARTY_ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `PartyIDSource` is present, Tag 447.
    pub fn has_party_id_source(&self) -> bool {
        self.group().field_map.has(tag::PARTY_ID_SOURCE)
    }




    /// Gets `PartyRole`, Tag 452.
    pub fn get_party_role(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::PartyRoleField::new(0);
        self.group().field_map.get_field(tag::PARTY_ROLE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `PartyRole` is present, Tag 452.
    pub fn has_party_role(&self) -> bool {
        self.group().field_map.has(tag::PARTY_ROLE)
    }




    /// Gets `PartySubID`, Tag 523.
    pub fn get_party_sub_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::PartySubIDField::new(String::new());
        self.group().field_map.get_field(tag::PARTY_SUB_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `PartySubID` is present, Tag 523.
    pub fn has_party_sub_id(&self) -> bool {
        self.group().field_map.has(tag::PARTY_SUB_ID)
    }


}

impl<G: BorrowMut<Group>> NoPartyIDs<G> {
    fn group_mut(&mut self) -> &mut Group {
        self.0.borrow_mut()
    }



    /// Sets `PartyID`, Tag 448.
    pub fn set_party_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::PARTY_ID, FIXString::from(v));
    }





    /// Sets `PartyIDSource`, Tag 447.
    pub fn set_party_id_source(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::PARTY_ID_SOURCE, FIXString::from(v));
    }





    /// Sets `PartyRole`, Tag 452.
    pub fn set_party_role(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::PARTY_ROLE, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `PartySubID`, Tag 523.
    pub fn set_party_sub_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::PARTY_SUB_ID, FIXString::from(v));
    }



}

/// `NoPartyIDsRepeatingGroup` is the `NoPartyIDs` repeating group, Tag 453.
pub struct NoPartyIDsRepeatingGroup(pub RepeatingGroup);

impl NoPartyIDsRepeatingGroup {
    /// Creates an empty `NoPartyIDs` group with the template from the FIX spec.
    pub fn new() -> Self {
        let template: GroupTemplate = vec![


            group_element(tag::PARTY_ID),



            group_element(tag::PARTY_ID_SOURCE),



            group_element(tag::PARTY_ROLE),



            group_element(tag::PARTY_SUB_ID),


        ];
        Self(RepeatingGroup::new(tag::NO_PARTY_I_DS, template))
    }

    /// Appends an entry and returns it for population.
    pub fn add(&mut self) -> NoPartyIDs<&mut Group> {
        NoPartyIDs(self.0.add())
    }

    /// Returns the `i`th entry.
    pub fn get(&self, i: usize) -> NoPartyIDs<&Group> {
        NoPartyIDs(self.0.get(i))
    }

    /// Returns the number of entries.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns true if the group has no entries.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl Default for NoPartyIDsRepeatingGroup {
    fn default() -> Self {
        Self::new()
    }
}



/// `NoSecurityAltID` is an entry in the `NoSecurityAltID` repeating group, Tag 454.
pub struct NoQuoteEntriesNoSecurityAltID<G>(pub G);

impl<G: Borrow<Group>> NoQuoteEntriesNoSecurityAltID<G> {
    fn group(&self) -> &Group {
        self.0.borrow()
    }



    /// Gets `SecurityAltID`, Tag 455.
    pub fn get_security_alt_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityAltIDField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_ALT_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityAltID` is present, Tag 455.
    pub fn has_security_alt_id(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_ALT_ID)
    }




    /// Gets `SecurityAltIDSource`, Tag 456.
    pub fn get_security_alt_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityAltIDSourceField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_ALT_ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityAltIDSource` is present, Tag 456.
    pub fn has_security_alt_id_source(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_ALT_ID_SOURCE)
    }


}

impl<G: BorrowMut<Group>> NoQuoteEntriesNoSecurityAltID<G> {
    fn group_mut(&mut self) -> &mut Group {
        self.0.borrow_mut()
    }



    /// Sets `SecurityAltID`, Tag 455.
    pub fn set_security_alt_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_ALT_ID, FIXString::from(v));
    }





    /// Sets `SecurityAltIDSource`, Tag 456.
    pub fn set_security_alt_id_source(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_ALT_ID_SOURCE, FIXString::from(v));
    }



}

/// `NoQuoteEntriesNoSecurityAltIDRepeatingGroup` is the `NoSecurityAltID` repeating group, Tag 454.
pub struct NoQuoteEntriesNoSecurityAltIDRepeatingGroup(pub RepeatingGroup);

impl NoQuoteEntriesNoSecurityAltIDRepeatingGroup {
    /// Creates an empty `NoSecurityAltID` group with the template from the FIX spec.
    pub fn new() -> Self {
        let template: GroupTemplate = vec![


            group_element(tag::SECURITY_ALT_ID),



            group_element(tag::SECURITY_ALT_ID_SOURCE),


        ];
        Self(RepeatingGroup::new(tag::NO_SECURITY_ALT_ID, template))
    }

    /// Appends an entry and returns it for population.
    pub fn add(&mut self) -> NoQuoteEntriesNoSecurityAltID<&mut Group> {
        NoQuoteEntriesNoSecurityAltID(self.0.add())
    }

    /// Returns the `i`th entry.
    pub fn get(&self, i: usize) -> NoQuoteEntriesNoSecurityAltID<&Group> {
        NoQuoteEntriesNoSecurityAltID(self.0.get(i))
    }

    /// Returns the number of entries.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns true if the group has no entries.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl Default for NoQuoteEntriesNoSecurityAltIDRepeatingGroup {
    fn default() -> Self {
        Self::new()
    }
}



/// `NoQuoteEntries` is an entry in the `NoQuoteEntries` repeating group, Tag 295.
pub struct NoQuoteEntries<G>(pub G);

impl<G: Borrow<Group>> NoQuoteEntries<G> {
    fn group(&self) -> &Group {
        self.0.borrow()
    }



    /// Gets `Symbol`, Tag 55.
    pub fn get_symbol(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolField::new(String::new());
        self.group().field_map.get_field(tag::SYMBOL, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Symbol` is present, Tag 55.
    pub fn has_symbol(&self) -> bool {
        self.group().field_map.has(tag::SYMBOL)
    }




    /// Gets `SymbolSfx`, Tag 65.
    pub fn get_symbol_sfx(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolSfxField::new(String::new());
        self.group().field_map.get_field(tag::SYMBOL_SFX, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SymbolSfx` is present, Tag 65.
    pub fn has_symbol_sfx(&self) -> bool {
        self.group().field_map.has(tag::SYMBOL_SFX)
    }




    /// Gets `SecurityID`, Tag 48.
    pub fn get_security_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityIDField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityID` is present, Tag 48.
    pub fn has_security_id(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_ID)
    }




    /// Gets `SecurityIDSource`, Tag 22.
    pub fn get_security_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityIDSourceField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityIDSource` is present, Tag 22.
    pub fn has_security_id_source(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_ID_SOURCE)
    }




    /// Gets `NoSecurityAltID`, Tag 454.
    pub fn get_no_security_alt_id(&self) -> Result<NoQuoteEntriesNoSecurityAltIDRepeatingGroup, MessageRejectErrorEnum> {
        let g = NoQuoteEntriesNoSecurityAltIDRepeatingGroup::new();
        Ok(NoQuoteEntriesNoSecurityAltIDRepeatingGroup(self.group().field_map.get_group(g.0)?))
    }


    /// Returns true if `NoSecurityAltID` is present, Tag 454.
    pub fn has_no_security_alt_id(&self) -> bool {
        self.group().field_map.has(tag::NO_SECURITY_ALT_ID)
    }




    /// Gets `Product`, Tag 460.
    pub fn get_product(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::ProductField::new(0);
        self.group().field_map.get_field(tag::PRODUCT, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Product` is present, Tag 460.
    pub fn has_product(&self) -> bool {
        self.group().field_map.has(tag::PRODUCT)
    }




    /// Gets `CFICode`, Tag 461.
    pub fn get_cfi_code(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CFICodeField::new(String::new());
        self.group().field_map.get_field(tag::CFI_CODE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CFICode` is present, Tag 461.
    pub fn has_cfi_code(&self) -> bool {
        self.group().field_map.has(tag::CFI_CODE)
    }




    /// Gets `SecurityType`, Tag 167.
    pub fn get_security_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityTypeField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityType` is present, Tag 167.
    pub fn has_security_type(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_TYPE)
    }




    /// Gets `MaturityMonthYear`, Tag 200.
    pub fn get_maturity_month_year(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MaturityMonthYearField::new(String::new());
        self.group().field_map.get_field(tag::MATURITY_MONTH_YEAR, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MaturityMonthYear` is present, Tag 200.
    pub fn has_maturity_month_year(&self) -> bool {
        self.group().field_map.has(tag::MATURITY_MONTH_YEAR)
    }




    /// Gets `MaturityDate`, Tag 541.
    pub fn get_maturity_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MaturityDateField::new(String::new());
        self.group().field_map.get_field(tag::MATURITY_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MaturityDate` is present, Tag 541.
    pub fn has_maturity_date(&self) -> bool {
        self.group().field_map.has(tag::MATURITY_DATE)
    }




    /// Gets `CouponPaymentDate`, Tag 224.
    pub fn get_coupon_payment_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CouponPaymentDateField::new(String::new());
        self.group().field_map.get_field(tag::COUPON_PAYMENT_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CouponPaymentDate` is present, Tag 224.
    pub fn has_coupon_payment_date(&self) -> bool {
        self.group().field_map.has(tag::COUPON_PAYMENT_DATE)
    }




    /// Gets `IssueDate`, Tag 225.
    pub fn get_issue_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IssueDateField::new(String::new());
        self.group().field_map.get_field(tag::ISSUE_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `IssueDate` is present, Tag 225.
    pub fn has_issue_date(&self) -> bool {
        self.group().field_map.has(tag::ISSUE_DATE)
    }




    /// Gets `RepoCollateralSecurityType`, Tag 239.
    pub fn get_repo_collateral_security_type(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::RepoCollateralSecurityTypeField::new(0);
        self.group().field_map.get_field(tag::REPO_COLLATERAL_SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RepoCollateralSecurityType` is present, Tag 239.
    pub fn has_repo_collateral_security_type(&self) -> bool {
        self.group().field_map.has(tag::REPO_COLLATERAL_SECURITY_TYPE)
    }




    /// Gets `RepurchaseTerm`, Tag 226.
    pub fn get_repurchase_term(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::RepurchaseTermField::new(0);
        self.group().field_map.get_field(tag::REPURCHASE_TERM, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RepurchaseTerm` is present, Tag 226.
    pub fn has_repurchase_term(&self) -> bool {
        self.group().field_map.has(tag::REPURCHASE_TERM)
    }




    /// Gets `RepurchaseRate`, Tag 227.
    pub fn get_repurchase_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::RepurchaseRateField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::REPURCHASE_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RepurchaseRate` is present, Tag 227.
    pub fn has_repurchase_rate(&self) -> bool {
        self.group().field_map.has(tag::REPURCHASE_RATE)
    }




    /// Gets `Factor`, Tag 228.
    pub fn get_factor(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::FactorField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::FACTOR, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Factor` is present, Tag 228.
    pub fn has_factor(&self) -> bool {
        self.group().field_map.has(tag::FACTOR)
    }




    /// Gets `CreditRating`, Tag 255.
    pub fn get_credit_rating(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CreditRatingField::new(String::new());
        self.group().field_map.get_field(tag::CREDIT_RATING, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CreditRating` is present, Tag 255.
    pub fn has_credit_rating(&self) -> bool {
        self.group().field_map.has(tag::CREDIT_RATING)
    }




    /// Gets `InstrRegistry`, Tag 543.
    pub fn get_instr_registry(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::InstrRegistryField::new(String::new());
        self.group().field_map.get_field(tag::INSTR_REGISTRY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `InstrRegistry` is present, Tag 543.
    pub fn has_instr_registry(&self) -> bool {
        self.group().field_map.has(tag::INSTR_REGISTRY)
    }




    /// Gets `CountryOfIssue`, Tag 470.
    pub fn get_country_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CountryOfIssueField::new(String::new());
        self.group().field_map.get_field(tag::COUNTRY_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CountryOfIssue` is present, Tag 470.
    pub fn has_country_of_issue(&self) -> bool {
        self.group().field_map.has(tag::COUNTRY_OF_ISSUE)
    }




    /// Gets `StateOrProvinceOfIssue`, Tag 471.
    pub fn get_state_or_province_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::StateOrProvinceOfIssueField::new(String::new());
        self.group().field_map.get_field(tag::STATE_OR_PROVINCE_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `StateOrProvinceOfIssue` is present, Tag 471.
    pub fn has_state_or_province_of_issue(&self) -> bool {
        self.group().field_map.has(tag::STATE_OR_PROVINCE_OF_ISSUE)
    }




    /// Gets `LocaleOfIssue`, Tag 472.
    pub fn get_locale_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::LocaleOfIssueField::new(String::new());
        self.group().field_map.get_field(tag::LOCALE_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `LocaleOfIssue` is present, Tag 472.
    pub fn has_locale_of_issue(&self) -> bool {
        self.group().field_map.has(tag::LOCALE_OF_ISSUE)
    }




    /// Gets `RedemptionDate`, Tag 240.
    pub fn get_redemption_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::RedemptionDateField::new(String::new());
        self.group().field_map.get_field(tag::REDEMPTION_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `RedemptionDate` is present, Tag 240.
    pub fn has_redemption_date(&self) -> bool {
        self.group().field_map.has(tag::REDEMPTION_DATE)
    }




    /// Gets `StrikePrice`, Tag 202.
    pub fn get_strike_price(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::StrikePriceField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::STRIKE_PRICE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `StrikePrice` is present, Tag 202.
    pub fn has_strike_price(&self) -> bool {
        self.group().field_map.has(tag::STRIKE_PRICE)
    }




    /// Gets `OptAttribute`, Tag 206.
    pub fn get_opt_attribute(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::OptAttributeField::new(String::new());
        self.group().field_map.get_field(tag::OPT_ATTRIBUTE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `OptAttribute` is present, Tag 206.
    pub fn has_opt_attribute(&self) -> bool {
        self.group().field_map.has(tag::OPT_ATTRIBUTE)
    }




    /// Gets `ContractMultiplier`, Tag 231.
    pub fn get_contract_multiplier(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::ContractMultiplierField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::CONTRACT_MULTIPLIER, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `ContractMultiplier` is present, Tag 231.
    pub fn has_contract_multiplier(&self) -> bool {
        self.group().field_map.has(tag::CONTRACT_MULTIPLIER)
    }




    /// Gets `CouponRate`, Tag 223.
    pub fn get_coupon_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::CouponRateField::new(Decimal::ZERO, 0);
        self.group().field_map.get_field(tag::COUPON_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `CouponRate` is present, Tag 223.
    pub fn has_coupon_rate(&self) -> bool {
        self.group().field_map.has(tag::COUPON_RATE)
    }




    /// Gets `SecurityExchange`, Tag 207.
    pub fn get_security_exchange(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityExchangeField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_EXCHANGE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityExchange` is present, Tag 207.
    pub fn has_security_exchange(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_EXCHANGE)
    }




    /// Gets `Issuer`, Tag 106.
    pub fn get_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IssuerField::new(String::new());
        self.group().field_map.get_field(tag::ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Issuer` is present, Tag 106.
    pub fn has_issuer(&self) -> bool {
        self.group().field_map.has(tag::ISSUER)
    }




    /// Gets `EncodedIssuerLen`, Tag 348.
    pub fn get_encoded_issuer_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedIssuerLenField::new(0);
        self.group().field_map.get_field(tag::ENCODED_ISSUER_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedIssuerLen` is present, Tag 348.
    pub fn has_encoded_issuer_len(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_ISSUER_LEN)
    }




    /// Gets `EncodedIssuer`, Tag 349.
    pub fn get_encoded_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedIssuerField::new(String::new());
        self.group().field_map.get_field(tag::ENCODED_ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedIssuer` is present, Tag 349.
    pub fn has_encoded_issuer(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_ISSUER)
    }




    /// Gets `SecurityDesc`, Tag 107.
    pub fn get_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityDescField::new(String::new());
        self.group().field_map.get_field(tag::SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityDesc` is present, Tag 107.
    pub fn has_security_desc(&self) -> bool {
        self.group().field_map.has(tag::SECURITY_DESC)
    }




    /// Gets `EncodedSecurityDescLen`, Tag 350.
    pub fn get_encoded_security_desc_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedSecurityDescLenField::new(0);
        self.group().field_map.get_field(tag::ENCODED_SECURITY_DESC_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedSecurityDescLen` is present, Tag 350.
    pub fn has_encoded_security_desc_len(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_SECURITY_DESC_LEN)
    }




    /// Gets `EncodedSecurityDesc`, Tag 351.
    pub fn get_encoded_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedSecurityDescField::new(String::new());
        self.group().field_map.get_field(tag::ENCODED_SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedSecurityDesc` is present, Tag 351.
    pub fn has_encoded_security_desc(&self) -> bool {
        self.group().field_map.has(tag::ENCODED_SECURITY_DESC)
    }


}

impl<G: BorrowMut<Group>> NoQuoteEntries<G> {
    fn group_mut(&mut self) -> &mut Group {
        self.0.borrow_mut()
    }



    /// Sets `Symbol`, Tag 55.
    pub fn set_symbol(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SYMBOL, FIXString::from(v));
    }





    /// Sets `SymbolSfx`, Tag 65.
    pub fn set_symbol_sfx(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SYMBOL_SFX, FIXString::from(v));
    }





    /// Sets `SecurityID`, Tag 48.
    pub fn set_security_id(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_ID, FIXString::from(v));
    }





    /// Sets `SecurityIDSource`, Tag 22.
    pub fn set_security_id_source(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_ID_SOURCE, FIXString::from(v));
    }





    /// Sets `NoSecurityAltID`, Tag 454.
    pub fn set_no_security_alt_id(&mut self, f: NoQuoteEntriesNoSecurityAltIDRepeatingGroup) {
        self.group_mut().field_map.set_group(f.0);
    }





    /// Sets `Product`, Tag 460.
    pub fn set_product(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::PRODUCT, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `CFICode`, Tag 461.
    pub fn set_cfi_code(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::CFI_CODE, FIXString::from(v));
    }





    /// Sets `SecurityType`, Tag 167.
    pub fn set_security_type(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_TYPE, FIXString::from(v));
    }





    /// Sets `MaturityMonthYear`, Tag 200.
    pub fn set_maturity_month_year(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::MATURITY_MONTH_YEAR, FIXString::from(v));
    }





    /// Sets `MaturityDate`, Tag 541.
    pub fn set_maturity_date(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::MATURITY_DATE, FIXString::from(v));
    }





    /// Sets `CouponPaymentDate`, Tag 224.
    pub fn set_coupon_payment_date(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::COUPON_PAYMENT_DATE, FIXString::from(v));
    }





    /// Sets `IssueDate`, Tag 225.
    pub fn set_issue_date(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ISSUE_DATE, FIXString::from(v));
    }





    /// Sets `RepoCollateralSecurityType`, Tag 239.
    pub fn set_repo_collateral_security_type(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::REPO_COLLATERAL_SECURITY_TYPE, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `RepurchaseTerm`, Tag 226.
    pub fn set_repurchase_term(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::REPURCHASE_TERM, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `RepurchaseRate`, Tag 227.
    pub fn set_repurchase_rate(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::REPURCHASE_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `Factor`, Tag 228.
    pub fn set_factor(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::FACTOR, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `CreditRating`, Tag 255.
    pub fn set_credit_rating(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::CREDIT_RATING, FIXString::from(v));
    }





    /// Sets `InstrRegistry`, Tag 543.
    pub fn set_instr_registry(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::INSTR_REGISTRY, FIXString::from(v));
    }





    /// Sets `CountryOfIssue`, Tag 470.
    pub fn set_country_of_issue(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::COUNTRY_OF_ISSUE, FIXString::from(v));
    }





    /// Sets `StateOrProvinceOfIssue`, Tag 471.
    pub fn set_state_or_province_of_issue(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::STATE_OR_PROVINCE_OF_ISSUE, FIXString::from(v));
    }





    /// Sets `LocaleOfIssue`, Tag 472.
    pub fn set_locale_of_issue(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::LOCALE_OF_ISSUE, FIXString::from(v));
    }





    /// Sets `RedemptionDate`, Tag 240.
    pub fn set_redemption_date(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::REDEMPTION_DATE, FIXString::from(v));
    }





    /// Sets `StrikePrice`, Tag 202.
    pub fn set_strike_price(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::STRIKE_PRICE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `OptAttribute`, Tag 206.
    pub fn set_opt_attribute(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::OPT_ATTRIBUTE, FIXString::from(v));
    }





    /// Sets `ContractMultiplier`, Tag 231.
    pub fn set_contract_multiplier(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::CONTRACT_MULTIPLIER, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `CouponRate`, Tag 223.
    pub fn set_coupon_rate(&mut self, val: Decimal, scale: i32) {
        self.group_mut().field_map.set_field(tag::COUPON_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }





    /// Sets `SecurityExchange`, Tag 207.
    pub fn set_security_exchange(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_EXCHANGE, FIXString::from(v));
    }





    /// Sets `Issuer`, Tag 106.
    pub fn set_issuer(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ISSUER, FIXString::from(v));
    }





    /// Sets `EncodedIssuerLen`, Tag 348.
    pub fn set_encoded_issuer_len(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::ENCODED_ISSUER_LEN, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `EncodedIssuer`, Tag 349.
    pub fn set_encoded_issuer(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ENCODED_ISSUER, FIXString::from(v));
    }





    /// Sets `SecurityDesc`, Tag 107.
    pub fn set_security_desc(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::SECURITY_DESC, FIXString::from(v));
    }





    /// Sets `EncodedSecurityDescLen`, Tag 350.
    pub fn set_encoded_security_desc_len(&mut self, v: isize) {
        self.group_mut().field_map.set_field(tag::ENCODED_SECURITY_DESC_LEN, fixer::fix_int::FIXInt::from(v));
    }





    /// Sets `EncodedSecurityDesc`, Tag 351.
    pub fn set_encoded_security_desc(&mut self, v: String) {
        self.group_mut().field_map.set_field(tag::ENCODED_SECURITY_DESC, FIXString::from(v));
    }



}

/// `NoQuoteEntriesRepeatingGroup` is the `NoQuoteEntries` repeating group, Tag 295.
pub struct NoQuoteEntriesRepeatingGroup(pub RepeatingGroup);

impl NoQuoteEntriesRepeatingGroup {
    /// Creates an empty `NoQuoteEntries` group with the template from the FIX spec.
    pub fn new() -> Self {
        let template: GroupTemplate = vec![


            group_element(tag::SYMBOL),



            group_element(tag::SYMBOL_SFX),



            group_element(tag::SECURITY_ID),



            group_element(tag::SECURITY_ID_SOURCE),



            Box::new(NoQuoteEntriesNoSecurityAltIDRepeatingGroup::new().0),



            group_element(tag::PRODUCT),



            group_element(tag::CFI_CODE),



            group_element(tag::SECURITY_TYPE),



            group_element(tag::MATURITY_MONTH_YEAR),



            group_element(tag::MATURITY_DATE),



            group_element(tag::COUPON_PAYMENT_DATE),



            group_element(tag::ISSUE_DATE),



            group_element(tag::REPO_COLLATERAL_SECURITY_TYPE),



            group_element(tag::REPURCHASE_TERM),



            group_element(tag::REPURCHASE_RATE),



            group_element(tag::FACTOR),



            group_element(tag::CREDIT_RATING),



            group_element(tag::INSTR_REGISTRY),



            group_element(tag::COUNTRY_OF_ISSUE),



            group_element(tag::STATE_OR_PROVINCE_OF_ISSUE),



            group_element(tag::LOCALE_OF_ISSUE),



            group_element(tag::REDEMPTION_DATE),



            group_element(tag::STRIKE_PRICE),



            group_element(tag::OPT_ATTRIBUTE),



            group_element(tag::CONTRACT_MULTIPLIER),



            group_element(tag::COUPON_RATE),



            group_element(tag::SECURITY_EXCHANGE),



            group_element(tag::ISSUER),



            group_element(tag::ENCODED_ISSUER_LEN),



            group_element(tag::ENCODED_ISSUER),



            group_element(tag::SECURITY_DESC),



            group_element(tag::ENCODED_SECURITY_DESC_LEN),



            group_element(tag::ENCODED_SECURITY_DESC),


        ];
        Self(RepeatingGroup::new(tag::NO_QUOTE_ENTRIES, template))
    }

    /// Appends an entry and returns it for population.
    pub fn add(&mut self) -> NoQuoteEntries<&mut Group> {
        NoQuoteEntries(self.0.add())
    }

    /// Returns the `i`th entry.
    pub fn get(&self, i: usize) -> NoQuoteEntries<&Group> {
        NoQuoteEntries(self.0.get(i))
    }

    /// Returns the number of entries.
    pub fn len(&self) -> usize {
        self.0.len()
    }

    /// Returns true if the group has no entries.
    pub fn is_empty(&self) -> bool {
        self.0.is_empty()
    }
}

impl Default for NoQuoteEntriesRepeatingGroup {
    fn default() -> Self {
        Self::new()
    }
}

