// Code generated by fixer-gen. DO NOT EDIT.
#![allow(clippy::new_without_default)]
#![allow(clippy::needless_pass_by_value)]
#![allow(clippy::too_many_arguments)]
#![allow(unused_imports)]

use fixer::message::Message;
use fixer::fix_string::FIXString;
use fixer::errors::MessageRejectErrorEnum;
use fixer::session::session_id::SessionID;


use crate::field;
use crate::tag;

/// `SequenceReset` is the `fix43` `SequenceReset` type, `MsgType` = 4.
pub struct SequenceReset {
    pub message: Message,
}

impl SequenceReset {
    /// Creates a new `SequenceReset` with required fields.
    pub fn new(new_seq_no: field::NewSeqNoField) -> Self {
        let mut msg = Message::new();
        msg.header.set_field(tag::MSG_TYPE, FIXString::from("4".to_string()));

        msg.body.set_field(tag::NEW_SEQ_NO, new_seq_no.0);

        Self { message: msg }
    }

    /// Creates a `SequenceReset` from an existing `Message`.
    pub fn from_message(msg: Message) -> Self {
        Self { message: msg }
    }

    /// Returns the underlying `Message`.
    pub fn to_message(self) -> Message {
        self.message
    }




    /// Sets `GapFillFlag`, Tag 123.
    pub fn set_gap_fill_flag(&mut self, v: bool) {
        self.message.body.set_field(tag::GAP_FILL_FLAG, fixer::fix_boolean::FIXBoolean::from(v));
    }

    /// Gets `GapFillFlag`, Tag 123.
    pub fn get_gap_fill_flag(&self) -> Result<bool, MessageRejectErrorEnum> {
        let mut fld = field::GapFillFlagField::new(false);
        self.message.body.get_field(tag::GAP_FILL_FLAG, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `GapFillFlag` is present, Tag 123.
    pub fn has_gap_fill_flag(&self) -> bool {
        self.message.body.has(tag::GAP_FILL_FLAG)
    }




    /// Sets `NewSeqNo`, Tag 36.
    pub fn set_new_seq_no(&mut self, v: isize) {
        self.message.body.set_field(tag::NEW_SEQ_NO, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `NewSeqNo`, Tag 36.
    pub fn get_new_seq_no(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::NewSeqNoField::new(0);
        self.message.body.get_field(tag::NEW_SEQ_NO, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `NewSeqNo` is present, Tag 36.
    pub fn has_new_seq_no(&self) -> bool {
        self.message.body.has(tag::NEW_SEQ_NO)
    }


}

/// `RouteOut` is the callback type for routing `SequenceReset` messages.
pub type RouteOut = fn(msg: SequenceReset, session_id: SessionID) -> Result<(), MessageRejectErrorEnum>;

/// Route type returned by the `route` function.
pub type Route = (&'static str, &'static str, Box<dyn Fn(&Message, SessionID) -> Result<(), MessageRejectErrorEnum> + Send>);

/// Returns the begin string, message type, and route function for `SequenceReset`.
pub fn route(router: RouteOut) -> Route {
    let r = move |msg: &Message, session_id: SessionID| -> Result<(), MessageRejectErrorEnum> {
        router(SequenceReset::from_message(msg.clone()), session_id)
    };
    ("FIX.4.3", "4", Box::new(r))
}
