// Code generated by fixer-gen. DO NOT EDIT.
#![allow(clippy::new_without_default)]
#![allow(clippy::needless_pass_by_value)]
#![allow(clippy::too_many_arguments)]
#![allow(unused_imports)]

use fixer::message::Message;
use fixer::fix_string::FIXString;
use fixer::errors::MessageRejectErrorEnum;
use fixer::session::session_id::SessionID;

use rust_decimal::Decimal;


use jiff::Timestamp;

use crate::field;
use crate::tag;

/// `TradeCaptureReport` is the `fix43` `TradeCaptureReport` type, `MsgType` = AE.
pub struct TradeCaptureReport {
    pub message: Message,
}

impl TradeCaptureReport {
    /// Creates a new `TradeCaptureReport` with required fields.
    pub fn new(trade_report_id: field::TradeReportIDField, exec_type: field::ExecTypeField, previously_reported: field::PreviouslyReportedField, last_qty: field::LastQtyField, last_px: field::LastPxField, trade_date: field::TradeDateField, transact_time: field::TransactTimeField, no_sides: field::NoSidesField) -> Self {
        let mut msg = Message::new();
        msg.header.set_field(tag::MSG_TYPE, FIXString::from("AE".to_string()));

        msg.body.set_field(tag::TRADE_REPORT_ID, trade_report_id.0);

        msg.body.set_field(tag::EXEC_TYPE, exec_type.0);

        msg.body.set_field(tag::PREVIOUSLY_REPORTED, previously_reported.0);

        msg.body.set_field(tag::LAST_QTY, last_qty.0);

        msg.body.set_field(tag::LAST_PX, last_px.0);

        msg.body.set_field(tag::TRADE_DATE, trade_date.0);

        msg.body.set_field(tag::TRANSACT_TIME, transact_time.0);

        msg.body.set_field(tag::NO_SIDES, no_sides.0);

        Self { message: msg }
    }

    /// Creates a `TradeCaptureReport` from an existing `Message`.
    pub fn from_message(msg: Message) -> Self {
        Self { message: msg }
    }

    /// Returns the underlying `Message`.
    pub fn to_message(self) -> Message {
        self.message
    }




    /// Sets `CFICode`, Tag 461.
    pub fn set_cfi_code(&mut self, v: String) {
        self.message.body.set_field(tag::CFI_CODE, FIXString::from(v));
    }

    /// Gets `CFICode`, Tag 461.
    pub fn get_cfi_code(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CFICodeField::new(String::new());
        self.message.body.get_field(tag::CFI_CODE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CFICode` is present, Tag 461.
    pub fn has_cfi_code(&self) -> bool {
        self.message.body.has(tag::CFI_CODE)
    }




    /// Sets `CashOrderQty`, Tag 152.
    pub fn set_cash_order_qty(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::CASH_ORDER_QTY, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `CashOrderQty`, Tag 152.
    pub fn get_cash_order_qty(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::CashOrderQtyField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::CASH_ORDER_QTY, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `CashOrderQty` is present, Tag 152.
    pub fn has_cash_order_qty(&self) -> bool {
        self.message.body.has(tag::CASH_ORDER_QTY)
    }




    /// Sets `ContractMultiplier`, Tag 231.
    pub fn set_contract_multiplier(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::CONTRACT_MULTIPLIER, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `ContractMultiplier`, Tag 231.
    pub fn get_contract_multiplier(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::ContractMultiplierField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::CONTRACT_MULTIPLIER, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `ContractMultiplier` is present, Tag 231.
    pub fn has_contract_multiplier(&self) -> bool {
        self.message.body.has(tag::CONTRACT_MULTIPLIER)
    }




    /// Sets `CountryOfIssue`, Tag 470.
    pub fn set_country_of_issue(&mut self, v: String) {
        self.message.body.set_field(tag::COUNTRY_OF_ISSUE, FIXString::from(v));
    }

    /// Gets `CountryOfIssue`, Tag 470.
    pub fn get_country_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CountryOfIssueField::new(String::new());
        self.message.body.get_field(tag::COUNTRY_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CountryOfIssue` is present, Tag 470.
    pub fn has_country_of_issue(&self) -> bool {
        self.message.body.has(tag::COUNTRY_OF_ISSUE)
    }




    /// Sets `CouponPaymentDate`, Tag 224.
    pub fn set_coupon_payment_date(&mut self, v: String) {
        self.message.body.set_field(tag::COUPON_PAYMENT_DATE, FIXString::from(v));
    }

    /// Gets `CouponPaymentDate`, Tag 224.
    pub fn get_coupon_payment_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CouponPaymentDateField::new(String::new());
        self.message.body.get_field(tag::COUPON_PAYMENT_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CouponPaymentDate` is present, Tag 224.
    pub fn has_coupon_payment_date(&self) -> bool {
        self.message.body.has(tag::COUPON_PAYMENT_DATE)
    }




    /// Sets `CouponRate`, Tag 223.
    pub fn set_coupon_rate(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::COUPON_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `CouponRate`, Tag 223.
    pub fn get_coupon_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::CouponRateField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::COUPON_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `CouponRate` is present, Tag 223.
    pub fn has_coupon_rate(&self) -> bool {
        self.message.body.has(tag::COUPON_RATE)
    }




    /// Sets `CreditRating`, Tag 255.
    pub fn set_credit_rating(&mut self, v: String) {
        self.message.body.set_field(tag::CREDIT_RATING, FIXString::from(v));
    }

    /// Gets `CreditRating`, Tag 255.
    pub fn get_credit_rating(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::CreditRatingField::new(String::new());
        self.message.body.get_field(tag::CREDIT_RATING, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `CreditRating` is present, Tag 255.
    pub fn has_credit_rating(&self) -> bool {
        self.message.body.has(tag::CREDIT_RATING)
    }




    /// Sets `EncodedIssuer`, Tag 349.
    pub fn set_encoded_issuer(&mut self, v: String) {
        self.message.body.set_field(tag::ENCODED_ISSUER, FIXString::from(v));
    }

    /// Gets `EncodedIssuer`, Tag 349.
    pub fn get_encoded_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedIssuerField::new(String::new());
        self.message.body.get_field(tag::ENCODED_ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedIssuer` is present, Tag 349.
    pub fn has_encoded_issuer(&self) -> bool {
        self.message.body.has(tag::ENCODED_ISSUER)
    }




    /// Sets `EncodedIssuerLen`, Tag 348.
    pub fn set_encoded_issuer_len(&mut self, v: isize) {
        self.message.body.set_field(tag::ENCODED_ISSUER_LEN, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `EncodedIssuerLen`, Tag 348.
    pub fn get_encoded_issuer_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedIssuerLenField::new(0);
        self.message.body.get_field(tag::ENCODED_ISSUER_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedIssuerLen` is present, Tag 348.
    pub fn has_encoded_issuer_len(&self) -> bool {
        self.message.body.has(tag::ENCODED_ISSUER_LEN)
    }




    /// Sets `EncodedSecurityDesc`, Tag 351.
    pub fn set_encoded_security_desc(&mut self, v: String) {
        self.message.body.set_field(tag::ENCODED_SECURITY_DESC, FIXString::from(v));
    }

    /// Gets `EncodedSecurityDesc`, Tag 351.
    pub fn get_encoded_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::EncodedSecurityDescField::new(String::new());
        self.message.body.get_field(tag::ENCODED_SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `EncodedSecurityDesc` is present, Tag 351.
    pub fn has_encoded_security_desc(&self) -> bool {
        self.message.body.has(tag::ENCODED_SECURITY_DESC)
    }




    /// Sets `EncodedSecurityDescLen`, Tag 350.
    pub fn set_encoded_security_desc_len(&mut self, v: isize) {
        self.message.body.set_field(tag::ENCODED_SECURITY_DESC_LEN, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `EncodedSecurityDescLen`, Tag 350.
    pub fn get_encoded_security_desc_len(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::EncodedSecurityDescLenField::new(0);
        self.message.body.get_field(tag::ENCODED_SECURITY_DESC_LEN, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `EncodedSecurityDescLen` is present, Tag 350.
    pub fn has_encoded_security_desc_len(&self) -> bool {
        self.message.body.has(tag::ENCODED_SECURITY_DESC_LEN)
    }




    /// Sets `ExecID`, Tag 17.
    pub fn set_exec_id(&mut self, v: String) {
        self.message.body.set_field(tag::EXEC_ID, FIXString::from(v));
    }

    /// Gets `ExecID`, Tag 17.
    pub fn get_exec_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::ExecIDField::new(String::new());
        self.message.body.get_field(tag::EXEC_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `ExecID` is present, Tag 17.
    pub fn has_exec_id(&self) -> bool {
        self.message.body.has(tag::EXEC_ID)
    }




    /// Sets `ExecRestatementReason`, Tag 378.
    pub fn set_exec_restatement_reason(&mut self, v: isize) {
        self.message.body.set_field(tag::EXEC_RESTATEMENT_REASON, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `ExecRestatementReason`, Tag 378.
    pub fn get_exec_restatement_reason(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::ExecRestatementReasonField::new(0);
        self.message.body.get_field(tag::EXEC_RESTATEMENT_REASON, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `ExecRestatementReason` is present, Tag 378.
    pub fn has_exec_restatement_reason(&self) -> bool {
        self.message.body.has(tag::EXEC_RESTATEMENT_REASON)
    }




    /// Sets `ExecType`, Tag 150.
    pub fn set_exec_type(&mut self, v: String) {
        self.message.body.set_field(tag::EXEC_TYPE, FIXString::from(v));
    }

    /// Gets `ExecType`, Tag 150.
    pub fn get_exec_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::ExecTypeField::new(String::new());
        self.message.body.get_field(tag::EXEC_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `ExecType` is present, Tag 150.
    pub fn has_exec_type(&self) -> bool {
        self.message.body.has(tag::EXEC_TYPE)
    }




    /// Sets `Factor`, Tag 228.
    pub fn set_factor(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::FACTOR, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `Factor`, Tag 228.
    pub fn get_factor(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::FactorField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::FACTOR, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Factor` is present, Tag 228.
    pub fn has_factor(&self) -> bool {
        self.message.body.has(tag::FACTOR)
    }




    /// Sets `FutSettDate`, Tag 64.
    pub fn set_fut_sett_date(&mut self, v: String) {
        self.message.body.set_field(tag::FUT_SETT_DATE, FIXString::from(v));
    }

    /// Gets `FutSettDate`, Tag 64.
    pub fn get_fut_sett_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::FutSettDateField::new(String::new());
        self.message.body.get_field(tag::FUT_SETT_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `FutSettDate` is present, Tag 64.
    pub fn has_fut_sett_date(&self) -> bool {
        self.message.body.has(tag::FUT_SETT_DATE)
    }




    /// Sets `InstrRegistry`, Tag 543.
    pub fn set_instr_registry(&mut self, v: String) {
        self.message.body.set_field(tag::INSTR_REGISTRY, FIXString::from(v));
    }

    /// Gets `InstrRegistry`, Tag 543.
    pub fn get_instr_registry(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::InstrRegistryField::new(String::new());
        self.message.body.get_field(tag::INSTR_REGISTRY, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `InstrRegistry` is present, Tag 543.
    pub fn has_instr_registry(&self) -> bool {
        self.message.body.has(tag::INSTR_REGISTRY)
    }




    /// Sets `IssueDate`, Tag 225.
    pub fn set_issue_date(&mut self, v: String) {
        self.message.body.set_field(tag::ISSUE_DATE, FIXString::from(v));
    }

    /// Gets `IssueDate`, Tag 225.
    pub fn get_issue_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IssueDateField::new(String::new());
        self.message.body.get_field(tag::ISSUE_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `IssueDate` is present, Tag 225.
    pub fn has_issue_date(&self) -> bool {
        self.message.body.has(tag::ISSUE_DATE)
    }




    /// Sets `Issuer`, Tag 106.
    pub fn set_issuer(&mut self, v: String) {
        self.message.body.set_field(tag::ISSUER, FIXString::from(v));
    }

    /// Gets `Issuer`, Tag 106.
    pub fn get_issuer(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::IssuerField::new(String::new());
        self.message.body.get_field(tag::ISSUER, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Issuer` is present, Tag 106.
    pub fn has_issuer(&self) -> bool {
        self.message.body.has(tag::ISSUER)
    }




    /// Sets `LastForwardPoints`, Tag 195.
    pub fn set_last_forward_points(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::LAST_FORWARD_POINTS, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `LastForwardPoints`, Tag 195.
    pub fn get_last_forward_points(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::LastForwardPointsField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::LAST_FORWARD_POINTS, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `LastForwardPoints` is present, Tag 195.
    pub fn has_last_forward_points(&self) -> bool {
        self.message.body.has(tag::LAST_FORWARD_POINTS)
    }




    /// Sets `LastMkt`, Tag 30.
    pub fn set_last_mkt(&mut self, v: String) {
        self.message.body.set_field(tag::LAST_MKT, FIXString::from(v));
    }

    /// Gets `LastMkt`, Tag 30.
    pub fn get_last_mkt(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::LastMktField::new(String::new());
        self.message.body.get_field(tag::LAST_MKT, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `LastMkt` is present, Tag 30.
    pub fn has_last_mkt(&self) -> bool {
        self.message.body.has(tag::LAST_MKT)
    }




    /// Sets `LastPx`, Tag 31.
    pub fn set_last_px(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::LAST_PX, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `LastPx`, Tag 31.
    pub fn get_last_px(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::LastPxField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::LAST_PX, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `LastPx` is present, Tag 31.
    pub fn has_last_px(&self) -> bool {
        self.message.body.has(tag::LAST_PX)
    }




    /// Sets `LastQty`, Tag 32.
    pub fn set_last_qty(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::LAST_QTY, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `LastQty`, Tag 32.
    pub fn get_last_qty(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::LastQtyField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::LAST_QTY, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `LastQty` is present, Tag 32.
    pub fn has_last_qty(&self) -> bool {
        self.message.body.has(tag::LAST_QTY)
    }




    /// Sets `LastSpotRate`, Tag 194.
    pub fn set_last_spot_rate(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::LAST_SPOT_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `LastSpotRate`, Tag 194.
    pub fn get_last_spot_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::LastSpotRateField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::LAST_SPOT_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `LastSpotRate` is present, Tag 194.
    pub fn has_last_spot_rate(&self) -> bool {
        self.message.body.has(tag::LAST_SPOT_RATE)
    }




    /// Sets `LocaleOfIssue`, Tag 472.
    pub fn set_locale_of_issue(&mut self, v: String) {
        self.message.body.set_field(tag::LOCALE_OF_ISSUE, FIXString::from(v));
    }

    /// Gets `LocaleOfIssue`, Tag 472.
    pub fn get_locale_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::LocaleOfIssueField::new(String::new());
        self.message.body.get_field(tag::LOCALE_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `LocaleOfIssue` is present, Tag 472.
    pub fn has_locale_of_issue(&self) -> bool {
        self.message.body.has(tag::LOCALE_OF_ISSUE)
    }




    /// Sets `MatchStatus`, Tag 573.
    pub fn set_match_status(&mut self, v: String) {
        self.message.body.set_field(tag::MATCH_STATUS, FIXString::from(v));
    }

    /// Gets `MatchStatus`, Tag 573.
    pub fn get_match_status(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MatchStatusField::new(String::new());
        self.message.body.get_field(tag::MATCH_STATUS, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MatchStatus` is present, Tag 573.
    pub fn has_match_status(&self) -> bool {
        self.message.body.has(tag::MATCH_STATUS)
    }




    /// Sets `MatchType`, Tag 574.
    pub fn set_match_type(&mut self, v: String) {
        self.message.body.set_field(tag::MATCH_TYPE, FIXString::from(v));
    }

    /// Gets `MatchType`, Tag 574.
    pub fn get_match_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MatchTypeField::new(String::new());
        self.message.body.get_field(tag::MATCH_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MatchType` is present, Tag 574.
    pub fn has_match_type(&self) -> bool {
        self.message.body.has(tag::MATCH_TYPE)
    }




    /// Sets `MaturityDate`, Tag 541.
    pub fn set_maturity_date(&mut self, v: String) {
        self.message.body.set_field(tag::MATURITY_DATE, FIXString::from(v));
    }

    /// Gets `MaturityDate`, Tag 541.
    pub fn get_maturity_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MaturityDateField::new(String::new());
        self.message.body.get_field(tag::MATURITY_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MaturityDate` is present, Tag 541.
    pub fn has_maturity_date(&self) -> bool {
        self.message.body.has(tag::MATURITY_DATE)
    }




    /// Sets `MaturityMonthYear`, Tag 200.
    pub fn set_maturity_month_year(&mut self, v: String) {
        self.message.body.set_field(tag::MATURITY_MONTH_YEAR, FIXString::from(v));
    }

    /// Gets `MaturityMonthYear`, Tag 200.
    pub fn get_maturity_month_year(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::MaturityMonthYearField::new(String::new());
        self.message.body.get_field(tag::MATURITY_MONTH_YEAR, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `MaturityMonthYear` is present, Tag 200.
    pub fn has_maturity_month_year(&self) -> bool {
        self.message.body.has(tag::MATURITY_MONTH_YEAR)
    }




    /// Sets `NoSecurityAltID`, Tag 454.
    pub fn set_no_security_alt_id(&mut self, v: isize) {
        self.message.body.set_field(tag::NO_SECURITY_ALT_ID, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `NoSecurityAltID`, Tag 454.
    pub fn get_no_security_alt_id(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::NoSecurityAltIDField::new(0);
        self.message.body.get_field(tag::NO_SECURITY_ALT_ID, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `NoSecurityAltID` is present, Tag 454.
    pub fn has_no_security_alt_id(&self) -> bool {
        self.message.body.has(tag::NO_SECURITY_ALT_ID)
    }




    /// Sets `NoSides`, Tag 552.
    pub fn set_no_sides(&mut self, v: isize) {
        self.message.body.set_field(tag::NO_SIDES, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `NoSides`, Tag 552.
    pub fn get_no_sides(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::NoSidesField::new(0);
        self.message.body.get_field(tag::NO_SIDES, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `NoSides` is present, Tag 552.
    pub fn has_no_sides(&self) -> bool {
        self.message.body.has(tag::NO_SIDES)
    }




    /// Sets `OptAttribute`, Tag 206.
    pub fn set_opt_attribute(&mut self, v: String) {
        self.message.body.set_field(tag::OPT_ATTRIBUTE, FIXString::from(v));
    }

    /// Gets `OptAttribute`, Tag 206.
    pub fn get_opt_attribute(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::OptAttributeField::new(String::new());
        self.message.body.get_field(tag::OPT_ATTRIBUTE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `OptAttribute` is present, Tag 206.
    pub fn has_opt_attribute(&self) -> bool {
        self.message.body.has(tag::OPT_ATTRIBUTE)
    }




    /// Sets `OrderPercent`, Tag 516.
    pub fn set_order_percent(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::ORDER_PERCENT, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `OrderPercent`, Tag 516.
    pub fn get_order_percent(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::OrderPercentField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::ORDER_PERCENT, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `OrderPercent` is present, Tag 516.
    pub fn has_order_percent(&self) -> bool {
        self.message.body.has(tag::ORDER_PERCENT)
    }




    /// Sets `OrderQty`, Tag 38.
    pub fn set_order_qty(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::ORDER_QTY, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `OrderQty`, Tag 38.
    pub fn get_order_qty(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::OrderQtyField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::ORDER_QTY, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `OrderQty` is present, Tag 38.
    pub fn has_order_qty(&self) -> bool {
        self.message.body.has(tag::ORDER_QTY)
    }




    /// Sets `PreviouslyReported`, Tag 570.
    pub fn set_previously_reported(&mut self, v: bool) {
        self.message.body.set_field(tag::PREVIOUSLY_REPORTED, fixer::fix_boolean::FIXBoolean::from(v));
    }

    /// Gets `PreviouslyReported`, Tag 570.
    pub fn get_previously_reported(&self) -> Result<bool, MessageRejectErrorEnum> {
        let mut fld = field::PreviouslyReportedField::new(false);
        self.message.body.get_field(tag::PREVIOUSLY_REPORTED, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `PreviouslyReported` is present, Tag 570.
    pub fn has_previously_reported(&self) -> bool {
        self.message.body.has(tag::PREVIOUSLY_REPORTED)
    }




    /// Sets `Product`, Tag 460.
    pub fn set_product(&mut self, v: isize) {
        self.message.body.set_field(tag::PRODUCT, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `Product`, Tag 460.
    pub fn get_product(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::ProductField::new(0);
        self.message.body.get_field(tag::PRODUCT, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `Product` is present, Tag 460.
    pub fn has_product(&self) -> bool {
        self.message.body.has(tag::PRODUCT)
    }




    /// Sets `RedemptionDate`, Tag 240.
    pub fn set_redemption_date(&mut self, v: String) {
        self.message.body.set_field(tag::REDEMPTION_DATE, FIXString::from(v));
    }

    /// Gets `RedemptionDate`, Tag 240.
    pub fn get_redemption_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::RedemptionDateField::new(String::new());
        self.message.body.get_field(tag::REDEMPTION_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `RedemptionDate` is present, Tag 240.
    pub fn has_redemption_date(&self) -> bool {
        self.message.body.has(tag::REDEMPTION_DATE)
    }




    /// Sets `RepoCollateralSecurityType`, Tag 239.
    pub fn set_repo_collateral_security_type(&mut self, v: isize) {
        self.message.body.set_field(tag::REPO_COLLATERAL_SECURITY_TYPE, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `RepoCollateralSecurityType`, Tag 239.
    pub fn get_repo_collateral_security_type(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::RepoCollateralSecurityTypeField::new(0);
        self.message.body.get_field(tag::REPO_COLLATERAL_SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RepoCollateralSecurityType` is present, Tag 239.
    pub fn has_repo_collateral_security_type(&self) -> bool {
        self.message.body.has(tag::REPO_COLLATERAL_SECURITY_TYPE)
    }




    /// Sets `RepurchaseRate`, Tag 227.
    pub fn set_repurchase_rate(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::REPURCHASE_RATE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `RepurchaseRate`, Tag 227.
    pub fn get_repurchase_rate(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::RepurchaseRateField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::REPURCHASE_RATE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RepurchaseRate` is present, Tag 227.
    pub fn has_repurchase_rate(&self) -> bool {
        self.message.body.has(tag::REPURCHASE_RATE)
    }




    /// Sets `RepurchaseTerm`, Tag 226.
    pub fn set_repurchase_term(&mut self, v: isize) {
        self.message.body.set_field(tag::REPURCHASE_TERM, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `RepurchaseTerm`, Tag 226.
    pub fn get_repurchase_term(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::RepurchaseTermField::new(0);
        self.message.body.get_field(tag::REPURCHASE_TERM, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RepurchaseTerm` is present, Tag 226.
    pub fn has_repurchase_term(&self) -> bool {
        self.message.body.has(tag::REPURCHASE_TERM)
    }




    /// Sets `RoundingDirection`, Tag 468.
    pub fn set_rounding_direction(&mut self, v: String) {
        self.message.body.set_field(tag::ROUNDING_DIRECTION, FIXString::from(v));
    }

    /// Gets `RoundingDirection`, Tag 468.
    pub fn get_rounding_direction(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::RoundingDirectionField::new(String::new());
        self.message.body.get_field(tag::ROUNDING_DIRECTION, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `RoundingDirection` is present, Tag 468.
    pub fn has_rounding_direction(&self) -> bool {
        self.message.body.has(tag::ROUNDING_DIRECTION)
    }




    /// Sets `RoundingModulus`, Tag 469.
    pub fn set_rounding_modulus(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::ROUNDING_MODULUS, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `RoundingModulus`, Tag 469.
    pub fn get_rounding_modulus(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::RoundingModulusField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::ROUNDING_MODULUS, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `RoundingModulus` is present, Tag 469.
    pub fn has_rounding_modulus(&self) -> bool {
        self.message.body.has(tag::ROUNDING_MODULUS)
    }




    /// Sets `SecondaryExecID`, Tag 527.
    pub fn set_secondary_exec_id(&mut self, v: String) {
        self.message.body.set_field(tag::SECONDARY_EXEC_ID, FIXString::from(v));
    }

    /// Gets `SecondaryExecID`, Tag 527.
    pub fn get_secondary_exec_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecondaryExecIDField::new(String::new());
        self.message.body.get_field(tag::SECONDARY_EXEC_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecondaryExecID` is present, Tag 527.
    pub fn has_secondary_exec_id(&self) -> bool {
        self.message.body.has(tag::SECONDARY_EXEC_ID)
    }




    /// Sets `SecurityDesc`, Tag 107.
    pub fn set_security_desc(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_DESC, FIXString::from(v));
    }

    /// Gets `SecurityDesc`, Tag 107.
    pub fn get_security_desc(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityDescField::new(String::new());
        self.message.body.get_field(tag::SECURITY_DESC, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityDesc` is present, Tag 107.
    pub fn has_security_desc(&self) -> bool {
        self.message.body.has(tag::SECURITY_DESC)
    }




    /// Sets `SecurityExchange`, Tag 207.
    pub fn set_security_exchange(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_EXCHANGE, FIXString::from(v));
    }

    /// Gets `SecurityExchange`, Tag 207.
    pub fn get_security_exchange(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityExchangeField::new(String::new());
        self.message.body.get_field(tag::SECURITY_EXCHANGE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityExchange` is present, Tag 207.
    pub fn has_security_exchange(&self) -> bool {
        self.message.body.has(tag::SECURITY_EXCHANGE)
    }




    /// Sets `SecurityID`, Tag 48.
    pub fn set_security_id(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_ID, FIXString::from(v));
    }

    /// Gets `SecurityID`, Tag 48.
    pub fn get_security_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityIDField::new(String::new());
        self.message.body.get_field(tag::SECURITY_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityID` is present, Tag 48.
    pub fn has_security_id(&self) -> bool {
        self.message.body.has(tag::SECURITY_ID)
    }




    /// Sets `SecurityIDSource`, Tag 22.
    pub fn set_security_id_source(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_ID_SOURCE, FIXString::from(v));
    }

    /// Gets `SecurityIDSource`, Tag 22.
    pub fn get_security_id_source(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityIDSourceField::new(String::new());
        self.message.body.get_field(tag::SECURITY_ID_SOURCE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityIDSource` is present, Tag 22.
    pub fn has_security_id_source(&self) -> bool {
        self.message.body.has(tag::SECURITY_ID_SOURCE)
    }




    /// Sets `SecurityType`, Tag 167.
    pub fn set_security_type(&mut self, v: String) {
        self.message.body.set_field(tag::SECURITY_TYPE, FIXString::from(v));
    }

    /// Gets `SecurityType`, Tag 167.
    pub fn get_security_type(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SecurityTypeField::new(String::new());
        self.message.body.get_field(tag::SECURITY_TYPE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SecurityType` is present, Tag 167.
    pub fn has_security_type(&self) -> bool {
        self.message.body.has(tag::SECURITY_TYPE)
    }




    /// Sets `SettlmntTyp`, Tag 63.
    pub fn set_settlmnt_typ(&mut self, v: String) {
        self.message.body.set_field(tag::SETTLMNT_TYP, FIXString::from(v));
    }

    /// Gets `SettlmntTyp`, Tag 63.
    pub fn get_settlmnt_typ(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SettlmntTypField::new(String::new());
        self.message.body.get_field(tag::SETTLMNT_TYP, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SettlmntTyp` is present, Tag 63.
    pub fn has_settlmnt_typ(&self) -> bool {
        self.message.body.has(tag::SETTLMNT_TYP)
    }




    /// Sets `StateOrProvinceOfIssue`, Tag 471.
    pub fn set_state_or_province_of_issue(&mut self, v: String) {
        self.message.body.set_field(tag::STATE_OR_PROVINCE_OF_ISSUE, FIXString::from(v));
    }

    /// Gets `StateOrProvinceOfIssue`, Tag 471.
    pub fn get_state_or_province_of_issue(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::StateOrProvinceOfIssueField::new(String::new());
        self.message.body.get_field(tag::STATE_OR_PROVINCE_OF_ISSUE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `StateOrProvinceOfIssue` is present, Tag 471.
    pub fn has_state_or_province_of_issue(&self) -> bool {
        self.message.body.has(tag::STATE_OR_PROVINCE_OF_ISSUE)
    }




    /// Sets `StrikePrice`, Tag 202.
    pub fn set_strike_price(&mut self, val: Decimal, scale: i32) {
        self.message.body.set_field(tag::STRIKE_PRICE, fixer::fix_decimal::FIXDecimal { decimal: val, scale });
    }

    /// Gets `StrikePrice`, Tag 202.
    pub fn get_strike_price(&self) -> Result<Decimal, MessageRejectErrorEnum> {
        let mut fld = field::StrikePriceField::new(Decimal::ZERO, 0);
        self.message.body.get_field(tag::STRIKE_PRICE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `StrikePrice` is present, Tag 202.
    pub fn has_strike_price(&self) -> bool {
        self.message.body.has(tag::STRIKE_PRICE)
    }




    /// Sets `Symbol`, Tag 55.
    pub fn set_symbol(&mut self, v: String) {
        self.message.body.set_field(tag::SYMBOL, FIXString::from(v));
    }

    /// Gets `Symbol`, Tag 55.
    pub fn get_symbol(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolField::new(String::new());
        self.message.body.get_field(tag::SYMBOL, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `Symbol` is present, Tag 55.
    pub fn has_symbol(&self) -> bool {
        self.message.body.has(tag::SYMBOL)
    }




    /// Sets `SymbolSfx`, Tag 65.
    pub fn set_symbol_sfx(&mut self, v: String) {
        self.message.body.set_field(tag::SYMBOL_SFX, FIXString::from(v));
    }

    /// Gets `SymbolSfx`, Tag 65.
    pub fn get_symbol_sfx(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::SymbolSfxField::new(String::new());
        self.message.body.get_field(tag::SYMBOL_SFX, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `SymbolSfx` is present, Tag 65.
    pub fn has_symbol_sfx(&self) -> bool {
        self.message.body.has(tag::SYMBOL_SFX)
    }




    /// Sets `TradeDate`, Tag 75.
    pub fn set_trade_date(&mut self, v: String) {
        self.message.body.set_field(tag::TRADE_DATE, FIXString::from(v));
    }

    /// Gets `TradeDate`, Tag 75.
    pub fn get_trade_date(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TradeDateField::new(String::new());
        self.message.body.get_field(tag::TRADE_DATE, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `TradeDate` is present, Tag 75.
    pub fn has_trade_date(&self) -> bool {
        self.message.body.has(tag::TRADE_DATE)
    }




    /// Sets `TradeReportID`, Tag 571.
    pub fn set_trade_report_id(&mut self, v: String) {
        self.message.body.set_field(tag::TRADE_REPORT_ID, FIXString::from(v));
    }

    /// Gets `TradeReportID`, Tag 571.
    pub fn get_trade_report_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TradeReportIDField::new(String::new());
        self.message.body.get_field(tag::TRADE_REPORT_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `TradeReportID` is present, Tag 571.
    pub fn has_trade_report_id(&self) -> bool {
        self.message.body.has(tag::TRADE_REPORT_ID)
    }




    /// Sets `TradeReportRefID`, Tag 572.
    pub fn set_trade_report_ref_id(&mut self, v: String) {
        self.message.body.set_field(tag::TRADE_REPORT_REF_ID, FIXString::from(v));
    }

    /// Gets `TradeReportRefID`, Tag 572.
    pub fn get_trade_report_ref_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TradeReportRefIDField::new(String::new());
        self.message.body.get_field(tag::TRADE_REPORT_REF_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `TradeReportRefID` is present, Tag 572.
    pub fn has_trade_report_ref_id(&self) -> bool {
        self.message.body.has(tag::TRADE_REPORT_REF_ID)
    }




    /// Sets `TradeReportTransType`, Tag 487.
    pub fn set_trade_report_trans_type(&mut self, v: isize) {
        self.message.body.set_field(tag::TRADE_REPORT_TRANS_TYPE, fixer::fix_int::FIXInt::from(v));
    }

    /// Gets `TradeReportTransType`, Tag 487.
    pub fn get_trade_report_trans_type(&self) -> Result<isize, MessageRejectErrorEnum> {
        let mut fld = field::TradeReportTransTypeField::new(0);
        self.message.body.get_field(tag::TRADE_REPORT_TRANS_TYPE, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `TradeReportTransType` is present, Tag 487.
    pub fn has_trade_report_trans_type(&self) -> bool {
        self.message.body.has(tag::TRADE_REPORT_TRANS_TYPE)
    }




    /// Sets `TradeRequestID`, Tag 568.
    pub fn set_trade_request_id(&mut self, v: String) {
        self.message.body.set_field(tag::TRADE_REQUEST_ID, FIXString::from(v));
    }

    /// Gets `TradeRequestID`, Tag 568.
    pub fn get_trade_request_id(&self) -> Result<String, MessageRejectErrorEnum> {
        let mut fld = field::TradeRequestIDField::new(String::new());
        self.message.body.get_field(tag::TRADE_REQUEST_ID, &mut fld.0)?;
        Ok(fld.value().to_string())
    }


    /// Returns true if `TradeRequestID` is present, Tag 568.
    pub fn has_trade_request_id(&self) -> bool {
        self.message.body.has(tag::TRADE_REQUEST_ID)
    }




    /// Sets `TransactTime`, Tag 60.
    pub fn set_transact_time(&mut self, v: Timestamp) {
        self.message.body.set_field(tag::TRANSACT_TIME, fixer::fix_utc_timestamp::FIXUTCTimestamp {
            time: v,
            precision: fixer::fix_utc_timestamp::TimestampPrecision::Millis,
        });
    }

    /// Gets `TransactTime`, Tag 60.
    pub fn get_transact_time(&self) -> Result<Timestamp, MessageRejectErrorEnum> {
        let mut fld = field::TransactTimeField::new(Timestamp::UNIX_EPOCH);
        self.message.body.get_field(tag::TRANSACT_TIME, &mut fld.0)?;
        Ok(fld.value())
    }


    /// Returns true if `TransactTime` is present, Tag 60.
    pub fn has_transact_time(&self) -> bool {
        self.message.body.has(tag::TRANSACT_TIME)
    }


}

/// `RouteOut` is the callback type for routing `TradeCaptureReport` messages.
pub type RouteOut = fn(msg: TradeCaptureReport, session_id: SessionID) -> Result<(), MessageRejectErrorEnum>;

/// Route type returned by the `route` function.
pub type Route = (&'static str, &'static str, Box<dyn Fn(&Message, SessionID) -> Result<(), MessageRejectErrorEnum> + Send>);

/// Returns the begin string, message type, and route function for `TradeCaptureReport`.
pub fn route(router: RouteOut) -> Route {
    let r = move |msg: &Message, session_id: SessionID| -> Result<(), MessageRejectErrorEnum> {
        router(TradeCaptureReport::from_message(msg.clone()), session_id)
    };
    ("FIX.4.3", "AE", Box::new(r))
}
